// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// AgentDiscoveredAppTypeValue represents the possible values for attribute "type".
type AgentDiscoveredAppTypeValue string

const (
	// AgentDiscoveredAppTypeBrowser represents the value Browser.
	AgentDiscoveredAppTypeBrowser AgentDiscoveredAppTypeValue = "Browser"

	// AgentDiscoveredAppTypeIDE represents the value IDE.
	AgentDiscoveredAppTypeIDE AgentDiscoveredAppTypeValue = "IDE"

	// AgentDiscoveredAppTypeNative represents the value Native.
	AgentDiscoveredAppTypeNative AgentDiscoveredAppTypeValue = "Native"
)

// AgentDiscoveredApp represents the model of a agentdiscoveredapp
type AgentDiscoveredApp struct {
	// The list of configured MCP servers for the application.
	MCPServers []*AgentDiscoveredMCP `json:"MCPServers,omitempty" msgpack:"MCPServers,omitempty" bson:"-" mapstructure:"MCPServers,omitempty"`

	// The name of the application.
	Name string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The install path of the application.
	PathInstall string `json:"pathInstall,omitempty" msgpack:"pathInstall,omitempty" bson:"pathinstall,omitempty" mapstructure:"pathInstall,omitempty"`

	// The list of installed genAI plugins/extensions for the application.
	Plugins []string `json:"plugins,omitempty" msgpack:"plugins,omitempty" bson:"-" mapstructure:"plugins,omitempty"`

	// The list of configured skills for the application.
	Skills []*AgentDiscoveredSkill `json:"skills,omitempty" msgpack:"skills,omitempty" bson:"-" mapstructure:"skills,omitempty"`

	// The type of application.
	Type AgentDiscoveredAppTypeValue `json:"type" msgpack:"type" bson:"type" mapstructure:"type,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewAgentDiscoveredApp returns a new *AgentDiscoveredApp
func NewAgentDiscoveredApp() *AgentDiscoveredApp {

	return &AgentDiscoveredApp{
		ModelVersion: 1,
		Plugins:      []string{},
		Type:         AgentDiscoveredAppTypeIDE,
	}
}
func (o *AgentDiscoveredApp) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *AgentDiscoveredApp) Identifier() string {

	return ""
}
func (o *AgentDiscoveredApp) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AgentDiscoveredApp) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesAgentDiscoveredApp{}

	s.Name = o.Name
	s.PathInstall = o.PathInstall
	s.Type = o.Type

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AgentDiscoveredApp) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesAgentDiscoveredApp{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.Name = s.Name
	o.PathInstall = s.PathInstall
	o.Type = s.Type

	return nil
}

// Version returns the hardcoded version of the model.
func (o *AgentDiscoveredApp) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *AgentDiscoveredApp) BleveType() string {

	return "agentdiscoveredapp"
}

// Doc returns the documentation for the object
func (o *AgentDiscoveredApp) Doc() string {

	return `Represents an application that the agent discovered.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *AgentDiscoveredApp) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	for _, sub := range o.MCPServers {
		if sub == nil {
			continue
		}
		if err := sub.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt refList/refMap attribute 'MCPServers' for 'AgentDiscoveredApp' (%s): %s", o.Identifier(), err)
		}
	}

	for _, sub := range o.Skills {
		if sub == nil {
			continue
		}
		if err := sub.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt refList/refMap attribute 'Skills' for 'AgentDiscoveredApp' (%s): %s", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *AgentDiscoveredApp) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	for _, sub := range o.MCPServers {
		if sub == nil {
			continue
		}
		if err := sub.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt refList/refMap attribute 'MCPServers' for 'AgentDiscoveredApp' (%s): %w", o.Identifier(), err)
		}
	}

	for _, sub := range o.Skills {
		if sub == nil {
			continue
		}
		if err := sub.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt refList/refMap attribute 'Skills' for 'AgentDiscoveredApp' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DeepCopy returns a deep copy if the AgentDiscoveredApp.
func (o *AgentDiscoveredApp) DeepCopy() *AgentDiscoveredApp {

	if o == nil {
		return nil
	}

	out := &AgentDiscoveredApp{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *AgentDiscoveredApp.
func (o *AgentDiscoveredApp) DeepCopyInto(out *AgentDiscoveredApp) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy AgentDiscoveredApp: %s", err))
	}

	*out = *target.(*AgentDiscoveredApp)
}

// Validate valides the current information stored into the structure.
func (o *AgentDiscoveredApp) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateStringInList("type", string(o.Type), []string{"IDE", "Browser", "Native"}, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*AgentDiscoveredApp) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := AgentDiscoveredAppAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return AgentDiscoveredAppLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*AgentDiscoveredApp) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return AgentDiscoveredAppAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *AgentDiscoveredApp) ValueForAttribute(name string) any {

	switch name {
	case "MCPServers":
		return o.MCPServers
	case "name":
		return o.Name
	case "pathInstall":
		return o.PathInstall
	case "plugins":
		return o.Plugins
	case "skills":
		return o.Skills
	case "type":
		return o.Type
	}

	return nil
}

// AgentDiscoveredAppAttributesMap represents the map of attribute for AgentDiscoveredApp.
var AgentDiscoveredAppAttributesMap = map[string]elemental.AttributeSpecification{
	"MCPServers": {
		AllowedChoices: []string{},
		ConvertedName:  "MCPServers",
		Description:    `The list of configured MCP servers for the application.`,
		Exposed:        true,
		Name:           "MCPServers",
		SubType:        "agentdiscoveredmcp",
		Transient:      true,
		Type:           "refList",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the application.`,
		Exposed:        true,
		Name:           "name",
		Stored:         true,
		Type:           "string",
	},
	"PathInstall": {
		AllowedChoices: []string{},
		BSONFieldName:  "pathinstall",
		ConvertedName:  "PathInstall",
		Description:    `The install path of the application.`,
		Exposed:        true,
		Name:           "pathInstall",
		Stored:         true,
		Type:           "string",
	},
	"Plugins": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "Plugins",
		Description:    `The list of installed genAI plugins/extensions for the application.`,
		Exposed:        true,
		Name:           "plugins",
		ReadOnly:       true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"Skills": {
		AllowedChoices: []string{},
		ConvertedName:  "Skills",
		Description:    `The list of configured skills for the application.`,
		Exposed:        true,
		Name:           "skills",
		SubType:        "agentdiscoveredskill",
		Transient:      true,
		Type:           "refList",
	},
	"Type": {
		AllowedChoices: []string{"IDE", "Browser", "Native"},
		BSONFieldName:  "type",
		ConvertedName:  "Type",
		DefaultValue:   AgentDiscoveredAppTypeIDE,
		Description:    `The type of application.`,
		Exposed:        true,
		Name:           "type",
		Stored:         true,
		Type:           "enum",
	},
}

// AgentDiscoveredAppLowerCaseAttributesMap represents the map of attribute for AgentDiscoveredApp.
var AgentDiscoveredAppLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"mcpservers": {
		AllowedChoices: []string{},
		ConvertedName:  "MCPServers",
		Description:    `The list of configured MCP servers for the application.`,
		Exposed:        true,
		Name:           "MCPServers",
		SubType:        "agentdiscoveredmcp",
		Transient:      true,
		Type:           "refList",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the application.`,
		Exposed:        true,
		Name:           "name",
		Stored:         true,
		Type:           "string",
	},
	"pathinstall": {
		AllowedChoices: []string{},
		BSONFieldName:  "pathinstall",
		ConvertedName:  "PathInstall",
		Description:    `The install path of the application.`,
		Exposed:        true,
		Name:           "pathInstall",
		Stored:         true,
		Type:           "string",
	},
	"plugins": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "Plugins",
		Description:    `The list of installed genAI plugins/extensions for the application.`,
		Exposed:        true,
		Name:           "plugins",
		ReadOnly:       true,
		SubType:        "string",
		Transient:      true,
		Type:           "list",
	},
	"skills": {
		AllowedChoices: []string{},
		ConvertedName:  "Skills",
		Description:    `The list of configured skills for the application.`,
		Exposed:        true,
		Name:           "skills",
		SubType:        "agentdiscoveredskill",
		Transient:      true,
		Type:           "refList",
	},
	"type": {
		AllowedChoices: []string{"IDE", "Browser", "Native"},
		BSONFieldName:  "type",
		ConvertedName:  "Type",
		DefaultValue:   AgentDiscoveredAppTypeIDE,
		Description:    `The type of application.`,
		Exposed:        true,
		Name:           "type",
		Stored:         true,
		Type:           "enum",
	},
}

type mongoAttributesAgentDiscoveredApp struct {
	Name        string                      `bson:"name,omitempty"`
	PathInstall string                      `bson:"pathinstall,omitempty"`
	Type        AgentDiscoveredAppTypeValue `bson:"type"`
}
