// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// AIDSectionLLMProviderTypeValue represents the possible values for attribute "type".
type AIDSectionLLMProviderTypeValue string

const (
	// AIDSectionLLMProviderTypeBYOM represents the value BYOM.
	AIDSectionLLMProviderTypeBYOM AIDSectionLLMProviderTypeValue = "BYOM"

	// AIDSectionLLMProviderTypeFirstParty represents the value FirstParty.
	AIDSectionLLMProviderTypeFirstParty AIDSectionLLMProviderTypeValue = "FirstParty"

	// AIDSectionLLMProviderTypeHybrid represents the value Hybrid.
	AIDSectionLLMProviderTypeHybrid AIDSectionLLMProviderTypeValue = "Hybrid"

	// AIDSectionLLMProviderTypeThirdParty represents the value ThirdParty.
	AIDSectionLLMProviderTypeThirdParty AIDSectionLLMProviderTypeValue = "ThirdParty"

	// AIDSectionLLMProviderTypeUnknown represents the value Unknown.
	AIDSectionLLMProviderTypeUnknown AIDSectionLLMProviderTypeValue = "Unknown"
)

// AIDSectionLLMProvider represents the model of a aidsectionllmprovider
type AIDSectionLLMProvider struct {
	// The citations used to compute the section.
	Citations []*AIDCitation `json:"citations,omitempty" msgpack:"citations,omitempty" bson:"citations,omitempty" mapstructure:"citations,omitempty"`

	// The description of the section.
	Description string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// List of Models used by the provider.
	Models []string `json:"models,omitempty" msgpack:"models,omitempty" bson:"models,omitempty" mapstructure:"models,omitempty"`

	// The name of the section.
	Name string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The risk associated to the section.
	Risk *AIDRisk `json:"risk,omitempty" msgpack:"risk,omitempty" bson:"risk,omitempty" mapstructure:"risk,omitempty"`

	// Type of LLM Provider.
	Type AIDSectionLLMProviderTypeValue `json:"type" msgpack:"type" bson:"type" mapstructure:"type,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewAIDSectionLLMProvider returns a new *AIDSectionLLMProvider
func NewAIDSectionLLMProvider() *AIDSectionLLMProvider {

	return &AIDSectionLLMProvider{
		ModelVersion: 1,
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AIDSectionLLMProvider) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesAIDSectionLLMProvider{}

	s.Citations = o.Citations
	s.Description = o.Description
	s.Models = o.Models
	s.Name = o.Name
	s.Risk = o.Risk
	s.Type = o.Type

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AIDSectionLLMProvider) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesAIDSectionLLMProvider{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.Citations = s.Citations
	o.Description = s.Description
	o.Models = s.Models
	o.Name = s.Name
	o.Risk = s.Risk
	o.Type = s.Type

	return nil
}

// BleveType implements the bleve.Classifier Interface.
func (o *AIDSectionLLMProvider) BleveType() string {

	return "aidsectionllmprovider"
}

// DeepCopy returns a deep copy if the AIDSectionLLMProvider.
func (o *AIDSectionLLMProvider) DeepCopy() *AIDSectionLLMProvider {

	if o == nil {
		return nil
	}

	out := &AIDSectionLLMProvider{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *AIDSectionLLMProvider.
func (o *AIDSectionLLMProvider) DeepCopyInto(out *AIDSectionLLMProvider) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy AIDSectionLLMProvider: %s", err))
	}

	*out = *target.(*AIDSectionLLMProvider)
}

// Validate valides the current information stored into the structure.
func (o *AIDSectionLLMProvider) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	for _, sub := range o.Citations {
		if sub == nil {
			continue
		}
		elemental.ResetDefaultForZeroValues(sub)
		if err := sub.Validate(); err != nil {
			errors = errors.Append(err)
		}
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if o.Risk != nil {
		elemental.ResetDefaultForZeroValues(o.Risk)
		if err := o.Risk.Validate(); err != nil {
			errors = errors.Append(err)
		}
	}

	if err := elemental.ValidateStringInList("type", string(o.Type), []string{"FirstParty", "ThirdParty", "Hybrid", "BYOM", "Unknown"}, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*AIDSectionLLMProvider) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := AIDSectionLLMProviderAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return AIDSectionLLMProviderLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*AIDSectionLLMProvider) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return AIDSectionLLMProviderAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *AIDSectionLLMProvider) ValueForAttribute(name string) any {

	switch name {
	case "citations":
		return o.Citations
	case "description":
		return o.Description
	case "models":
		return o.Models
	case "name":
		return o.Name
	case "risk":
		return o.Risk
	case "type":
		return o.Type
	}

	return nil
}

// AIDSectionLLMProviderAttributesMap represents the map of attribute for AIDSectionLLMProvider.
var AIDSectionLLMProviderAttributesMap = map[string]elemental.AttributeSpecification{
	"Citations": {
		AllowedChoices: []string{},
		BSONFieldName:  "citations",
		ConvertedName:  "Citations",
		Description:    `The citations used to compute the section.`,
		Exposed:        true,
		Name:           "citations",
		Stored:         true,
		SubType:        "aidcitation",
		Type:           "refList",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the section.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"Models": {
		AllowedChoices: []string{},
		BSONFieldName:  "models",
		ConvertedName:  "Models",
		Description:    `List of Models used by the provider.`,
		Exposed:        true,
		Name:           "models",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the section.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Risk": {
		AllowedChoices: []string{},
		BSONFieldName:  "risk",
		ConvertedName:  "Risk",
		Description:    `The risk associated to the section.`,
		Exposed:        true,
		Name:           "risk",
		Stored:         true,
		SubType:        "aidrisk",
		Type:           "ref",
	},
	"Type": {
		AllowedChoices: []string{"FirstParty", "ThirdParty", "Hybrid", "BYOM", "Unknown"},
		BSONFieldName:  "type",
		ConvertedName:  "Type",
		Description:    `Type of LLM Provider.`,
		Exposed:        true,
		Name:           "type",
		Stored:         true,
		Type:           "enum",
	},
}

// AIDSectionLLMProviderLowerCaseAttributesMap represents the map of attribute for AIDSectionLLMProvider.
var AIDSectionLLMProviderLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"citations": {
		AllowedChoices: []string{},
		BSONFieldName:  "citations",
		ConvertedName:  "Citations",
		Description:    `The citations used to compute the section.`,
		Exposed:        true,
		Name:           "citations",
		Stored:         true,
		SubType:        "aidcitation",
		Type:           "refList",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the section.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"models": {
		AllowedChoices: []string{},
		BSONFieldName:  "models",
		ConvertedName:  "Models",
		Description:    `List of Models used by the provider.`,
		Exposed:        true,
		Name:           "models",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the section.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"risk": {
		AllowedChoices: []string{},
		BSONFieldName:  "risk",
		ConvertedName:  "Risk",
		Description:    `The risk associated to the section.`,
		Exposed:        true,
		Name:           "risk",
		Stored:         true,
		SubType:        "aidrisk",
		Type:           "ref",
	},
	"type": {
		AllowedChoices: []string{"FirstParty", "ThirdParty", "Hybrid", "BYOM", "Unknown"},
		BSONFieldName:  "type",
		ConvertedName:  "Type",
		Description:    `Type of LLM Provider.`,
		Exposed:        true,
		Name:           "type",
		Stored:         true,
		Type:           "enum",
	},
}

type mongoAttributesAIDSectionLLMProvider struct {
	Citations   []*AIDCitation                 `bson:"citations,omitempty"`
	Description string                         `bson:"description,omitempty"`
	Models      []string                       `bson:"models,omitempty"`
	Name        string                         `bson:"name,omitempty"`
	Risk        *AIDRisk                       `bson:"risk,omitempty"`
	Type        AIDSectionLLMProviderTypeValue `bson:"type"`
}
