// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// AISkillSummaryLevelValue represents the possible values for attribute "level".
type AISkillSummaryLevelValue string

const (
	// AISkillSummaryLevelCritical represents the value Critical.
	AISkillSummaryLevelCritical AISkillSummaryLevelValue = "Critical"

	// AISkillSummaryLevelHigh represents the value High.
	AISkillSummaryLevelHigh AISkillSummaryLevelValue = "High"

	// AISkillSummaryLevelLow represents the value Low.
	AISkillSummaryLevelLow AISkillSummaryLevelValue = "Low"

	// AISkillSummaryLevelMedium represents the value Medium.
	AISkillSummaryLevelMedium AISkillSummaryLevelValue = "Medium"
)

// AISkillSummary represents the model of a aiskillsummary
type AISkillSummary struct {
	// The level of the risk.
	Level AISkillSummaryLevelValue `json:"level" msgpack:"level" bson:"level" mapstructure:"level,omitempty"`

	// Short explanation of the overall skill risk level.
	RiskRationale string `json:"riskRationale,omitempty" msgpack:"riskRationale,omitempty" bson:"riskrationale,omitempty" mapstructure:"riskRationale,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewAISkillSummary returns a new *AISkillSummary
func NewAISkillSummary() *AISkillSummary {

	return &AISkillSummary{
		ModelVersion: 1,
	}
}
func (o *AISkillSummary) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *AISkillSummary) Identifier() string {

	return ""
}
func (o *AISkillSummary) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AISkillSummary) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesAISkillSummary{}

	s.Level = o.Level
	s.RiskRationale = o.RiskRationale

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AISkillSummary) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesAISkillSummary{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.Level = s.Level
	o.RiskRationale = s.RiskRationale

	return nil
}

// Version returns the hardcoded version of the model.
func (o *AISkillSummary) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *AISkillSummary) BleveType() string {

	return "aiskillsummary"
}

// Doc returns the documentation for the object
func (o *AISkillSummary) Doc() string {

	return `AI skill risk summary.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *AISkillSummary) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *AISkillSummary) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the AISkillSummary.
func (o *AISkillSummary) DeepCopy() *AISkillSummary {

	if o == nil {
		return nil
	}

	out := &AISkillSummary{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *AISkillSummary.
func (o *AISkillSummary) DeepCopyInto(out *AISkillSummary) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy AISkillSummary: %s", err))
	}

	*out = *target.(*AISkillSummary)
}

// Validate valides the current information stored into the structure.
func (o *AISkillSummary) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("level", string(o.Level)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("level", string(o.Level), []string{"Low", "Medium", "High", "Critical"}, false); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*AISkillSummary) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := AISkillSummaryAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return AISkillSummaryLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*AISkillSummary) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return AISkillSummaryAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *AISkillSummary) ValueForAttribute(name string) any {

	switch name {
	case "level":
		return o.Level
	case "riskRationale":
		return o.RiskRationale
	}

	return nil
}

// AISkillSummaryAttributesMap represents the map of attribute for AISkillSummary.
var AISkillSummaryAttributesMap = map[string]elemental.AttributeSpecification{
	"Level": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		BSONFieldName:  "level",
		ConvertedName:  "Level",
		Description:    `The level of the risk.`,
		Exposed:        true,
		Name:           "level",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"RiskRationale": {
		AllowedChoices: []string{},
		BSONFieldName:  "riskrationale",
		ConvertedName:  "RiskRationale",
		Description:    `Short explanation of the overall skill risk level.`,
		Exposed:        true,
		Name:           "riskRationale",
		Stored:         true,
		Type:           "string",
	},
}

// AISkillSummaryLowerCaseAttributesMap represents the map of attribute for AISkillSummary.
var AISkillSummaryLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"level": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		BSONFieldName:  "level",
		ConvertedName:  "Level",
		Description:    `The level of the risk.`,
		Exposed:        true,
		Name:           "level",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"riskrationale": {
		AllowedChoices: []string{},
		BSONFieldName:  "riskrationale",
		ConvertedName:  "RiskRationale",
		Description:    `Short explanation of the overall skill risk level.`,
		Exposed:        true,
		Name:           "riskRationale",
		Stored:         true,
		Type:           "string",
	},
}

type mongoAttributesAISkillSummary struct {
	Level         AISkillSummaryLevelValue `bson:"level"`
	RiskRationale string                   `bson:"riskrationale,omitempty"`
}
