// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// AppComponentEgressDefaultPolicyActionValue represents the possible values for attribute "defaultPolicyAction".
type AppComponentEgressDefaultPolicyActionValue string

const (
	// AppComponentEgressDefaultPolicyActionAllow represents the value Allow.
	AppComponentEgressDefaultPolicyActionAllow AppComponentEgressDefaultPolicyActionValue = "Allow"

	// AppComponentEgressDefaultPolicyActionDeny represents the value Deny.
	AppComponentEgressDefaultPolicyActionDeny AppComponentEgressDefaultPolicyActionValue = "Deny"
)

// AppComponentEgress represents the model of a appcomponentegress
type AppComponentEgress struct {
	// The message that is sent if the access is denied by the default policy deny
	// action.
	DefaultPolicyAccessDeniedMessage string `json:"defaultPolicyAccessDeniedMessage,omitempty" msgpack:"defaultPolicyAccessDeniedMessage,omitempty" bson:"defaultpolicyaccessdeniedmessage,omitempty" mapstructure:"defaultPolicyAccessDeniedMessage,omitempty"`

	// The default action to take for connections ingressing to the proxy of this
	// workload that do not match any of the policies.
	DefaultPolicyAction AppComponentEgressDefaultPolicyActionValue `json:"defaultPolicyAction" msgpack:"defaultPolicyAction" bson:"defaultpolicyaction" mapstructure:"defaultPolicyAction,omitempty"`

	// If true, when any non-user-facing platform stage fails during request
	// handling (extractor, mapper, analyzer, content policy, body read, etc.),
	// the request is rejected. When false (default), the request is allowed
	// through unanalyzed (fail-open), trading safety for availability.
	// User-facing decisions (Unauthorized, Forbidden, Deny, Ask) are unaffected
	// and continue to be enforced. Default false.
	FailClose bool `json:"failClose" msgpack:"failClose" bson:"failclose" mapstructure:"failClose,omitempty"`

	// The list of policies for egress connections.
	Policies []*EgressPolicy `json:"policies,omitempty" msgpack:"policies,omitempty" bson:"policies,omitempty" mapstructure:"policies,omitempty"`

	// The computed rego access policy for the proxy.
	ProxyAccessPolicy string `json:"proxyAccessPolicy,omitempty" msgpack:"proxyAccessPolicy,omitempty" bson:"-" mapstructure:"proxyAccessPolicy,omitempty"`

	// The computed rego content policy for the proxy.
	ProxyContentPolicy string `json:"proxyContentPolicy,omitempty" msgpack:"proxyContentPolicy,omitempty" bson:"-" mapstructure:"proxyContentPolicy,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewAppComponentEgress returns a new *AppComponentEgress
func NewAppComponentEgress() *AppComponentEgress {

	return &AppComponentEgress{
		ModelVersion:        1,
		DefaultPolicyAction: AppComponentEgressDefaultPolicyActionAllow,
	}
}
func (o *AppComponentEgress) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *AppComponentEgress) Identifier() string {

	return ""
}
func (o *AppComponentEgress) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AppComponentEgress) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesAppComponentEgress{}

	s.DefaultPolicyAccessDeniedMessage = o.DefaultPolicyAccessDeniedMessage
	s.DefaultPolicyAction = o.DefaultPolicyAction
	s.FailClose = o.FailClose
	s.Policies = o.Policies

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AppComponentEgress) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesAppComponentEgress{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.DefaultPolicyAccessDeniedMessage = s.DefaultPolicyAccessDeniedMessage
	o.DefaultPolicyAction = s.DefaultPolicyAction
	o.FailClose = s.FailClose
	o.Policies = s.Policies

	return nil
}

// Version returns the hardcoded version of the model.
func (o *AppComponentEgress) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *AppComponentEgress) BleveType() string {

	return "appcomponentegress"
}

// Doc returns the documentation for the object
func (o *AppComponentEgress) Doc() string {

	return `Represents the egress configuration of an application component.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *AppComponentEgress) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	for _, sub := range o.Policies {
		if sub == nil {
			continue
		}
		if err := sub.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt refList/refMap attribute 'Policies' for 'AppComponentEgress' (%s): %s", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *AppComponentEgress) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	for _, sub := range o.Policies {
		if sub == nil {
			continue
		}
		if err := sub.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt refList/refMap attribute 'Policies' for 'AppComponentEgress' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DeepCopy returns a deep copy if the AppComponentEgress.
func (o *AppComponentEgress) DeepCopy() *AppComponentEgress {

	if o == nil {
		return nil
	}

	out := &AppComponentEgress{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *AppComponentEgress.
func (o *AppComponentEgress) DeepCopyInto(out *AppComponentEgress) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy AppComponentEgress: %s", err))
	}

	*out = *target.(*AppComponentEgress)
}

// Validate valides the current information stored into the structure.
func (o *AppComponentEgress) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateStringInList("defaultPolicyAction", string(o.DefaultPolicyAction), []string{"Allow", "Deny"}, false); err != nil {
		errors = errors.Append(err)
	}

	for i, sub := range o.Policies {
		if sub == nil {
			continue
		}
		if err := sub.Validate(); err != nil {
			errors = errors.Append(err)
			elemental.InjectAttributePath(errors, fmt.Sprintf("%s/%v", "policies", i))
		}
	}

	if err := ValidateAppComponentEgressPolicies("policies", o.Policies); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*AppComponentEgress) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := AppComponentEgressAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return AppComponentEgressLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*AppComponentEgress) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return AppComponentEgressAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *AppComponentEgress) ValueForAttribute(name string) any {

	switch name {
	case "defaultPolicyAccessDeniedMessage":
		return o.DefaultPolicyAccessDeniedMessage
	case "defaultPolicyAction":
		return o.DefaultPolicyAction
	case "failClose":
		return o.FailClose
	case "policies":
		return o.Policies
	case "proxyAccessPolicy":
		return o.ProxyAccessPolicy
	case "proxyContentPolicy":
		return o.ProxyContentPolicy
	}

	return nil
}

// AppComponentEgressAttributesMap represents the map of attribute for AppComponentEgress.
var AppComponentEgressAttributesMap = map[string]elemental.AttributeSpecification{
	"DefaultPolicyAccessDeniedMessage": {
		AllowedChoices: []string{},
		BSONFieldName:  "defaultpolicyaccessdeniedmessage",
		ConvertedName:  "DefaultPolicyAccessDeniedMessage",
		Description: `The message that is sent if the access is denied by the default policy deny
action.`,
		Exposed: true,
		Name:    "defaultPolicyAccessDeniedMessage",
		Stored:  true,
		Type:    "string",
	},
	"DefaultPolicyAction": {
		AllowedChoices: []string{"Allow", "Deny"},
		BSONFieldName:  "defaultpolicyaction",
		ConvertedName:  "DefaultPolicyAction",
		DefaultValue:   AppComponentEgressDefaultPolicyActionAllow,
		Description: `The default action to take for connections ingressing to the proxy of this
workload that do not match any of the policies.`,
		Exposed: true,
		Name:    "defaultPolicyAction",
		Stored:  true,
		Type:    "enum",
	},
	"FailClose": {
		AllowedChoices: []string{},
		BSONFieldName:  "failclose",
		ConvertedName:  "FailClose",
		Description: `If true, when any non-user-facing platform stage fails during request
handling (extractor, mapper, analyzer, content policy, body read, etc.),
the request is rejected. When false (default), the request is allowed
through unanalyzed (fail-open), trading safety for availability.
User-facing decisions (Unauthorized, Forbidden, Deny, Ask) are unaffected
and continue to be enforced. Default false.`,
		Exposed: true,
		Name:    "failClose",
		Stored:  true,
		Type:    "boolean",
	},
	"Policies": {
		AllowedChoices: []string{},
		BSONFieldName:  "policies",
		ConvertedName:  "Policies",
		Description:    `The list of policies for egress connections.`,
		Exposed:        true,
		Name:           "policies",
		Stored:         true,
		SubType:        "egresspolicy",
		Type:           "refList",
	},
	"ProxyAccessPolicy": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ProxyAccessPolicy",
		Description:    `The computed rego access policy for the proxy.`,
		Exposed:        true,
		Name:           "proxyAccessPolicy",
		ReadOnly:       true,
		Transient:      true,
		Type:           "string",
	},
	"ProxyContentPolicy": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ProxyContentPolicy",
		Description:    `The computed rego content policy for the proxy.`,
		Exposed:        true,
		Name:           "proxyContentPolicy",
		ReadOnly:       true,
		Transient:      true,
		Type:           "string",
	},
}

// AppComponentEgressLowerCaseAttributesMap represents the map of attribute for AppComponentEgress.
var AppComponentEgressLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"defaultpolicyaccessdeniedmessage": {
		AllowedChoices: []string{},
		BSONFieldName:  "defaultpolicyaccessdeniedmessage",
		ConvertedName:  "DefaultPolicyAccessDeniedMessage",
		Description: `The message that is sent if the access is denied by the default policy deny
action.`,
		Exposed: true,
		Name:    "defaultPolicyAccessDeniedMessage",
		Stored:  true,
		Type:    "string",
	},
	"defaultpolicyaction": {
		AllowedChoices: []string{"Allow", "Deny"},
		BSONFieldName:  "defaultpolicyaction",
		ConvertedName:  "DefaultPolicyAction",
		DefaultValue:   AppComponentEgressDefaultPolicyActionAllow,
		Description: `The default action to take for connections ingressing to the proxy of this
workload that do not match any of the policies.`,
		Exposed: true,
		Name:    "defaultPolicyAction",
		Stored:  true,
		Type:    "enum",
	},
	"failclose": {
		AllowedChoices: []string{},
		BSONFieldName:  "failclose",
		ConvertedName:  "FailClose",
		Description: `If true, when any non-user-facing platform stage fails during request
handling (extractor, mapper, analyzer, content policy, body read, etc.),
the request is rejected. When false (default), the request is allowed
through unanalyzed (fail-open), trading safety for availability.
User-facing decisions (Unauthorized, Forbidden, Deny, Ask) are unaffected
and continue to be enforced. Default false.`,
		Exposed: true,
		Name:    "failClose",
		Stored:  true,
		Type:    "boolean",
	},
	"policies": {
		AllowedChoices: []string{},
		BSONFieldName:  "policies",
		ConvertedName:  "Policies",
		Description:    `The list of policies for egress connections.`,
		Exposed:        true,
		Name:           "policies",
		Stored:         true,
		SubType:        "egresspolicy",
		Type:           "refList",
	},
	"proxyaccesspolicy": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ProxyAccessPolicy",
		Description:    `The computed rego access policy for the proxy.`,
		Exposed:        true,
		Name:           "proxyAccessPolicy",
		ReadOnly:       true,
		Transient:      true,
		Type:           "string",
	},
	"proxycontentpolicy": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		ConvertedName:  "ProxyContentPolicy",
		Description:    `The computed rego content policy for the proxy.`,
		Exposed:        true,
		Name:           "proxyContentPolicy",
		ReadOnly:       true,
		Transient:      true,
		Type:           "string",
	},
}

type mongoAttributesAppComponentEgress struct {
	DefaultPolicyAccessDeniedMessage string                                     `bson:"defaultpolicyaccessdeniedmessage,omitempty"`
	DefaultPolicyAction              AppComponentEgressDefaultPolicyActionValue `bson:"defaultpolicyaction"`
	FailClose                        bool                                       `bson:"failclose"`
	Policies                         []*EgressPolicy                            `bson:"policies,omitempty"`
}
