// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// EgressPolicyRuleModeValue represents the possible values for attribute "mode".
type EgressPolicyRuleModeValue string

const (
	// EgressPolicyRuleModePassthrough represents the value Passthrough.
	EgressPolicyRuleModePassthrough EgressPolicyRuleModeValue = "Passthrough"

	// EgressPolicyRuleModeProxy represents the value Proxy.
	EgressPolicyRuleModeProxy EgressPolicyRuleModeValue = "Proxy"
)

// EgressPolicyRuleProxyActionValue represents the possible values for attribute "proxyAction".
type EgressPolicyRuleProxyActionValue string

const (
	// EgressPolicyRuleProxyActionAllow represents the value Allow.
	EgressPolicyRuleProxyActionAllow EgressPolicyRuleProxyActionValue = "Allow"

	// EgressPolicyRuleProxyActionDeny represents the value Deny.
	EgressPolicyRuleProxyActionDeny EgressPolicyRuleProxyActionValue = "Deny"

	// EgressPolicyRuleProxyActionNotApplicable represents the value NotApplicable.
	EgressPolicyRuleProxyActionNotApplicable EgressPolicyRuleProxyActionValue = "NotApplicable"
)

// EgressPolicyRule represents the model of a egresspolicyrule
type EgressPolicyRule struct {
	// The list of application components that this rule applies to in the form of
	// app/component. If the component is not specified, then this rule applies to all
	// components of the application.
	AppComponents []string `json:"appComponents,omitempty" msgpack:"appComponents,omitempty" bson:"appcomponents,omitempty" mapstructure:"appComponents,omitempty"`

	// The list of content policies to apply when the workload has access to the
	// provider.
	ContentPolicies []string `json:"contentPolicies,omitempty" msgpack:"contentPolicies,omitempty" bson:"contentpolicies,omitempty" mapstructure:"contentPolicies,omitempty"`

	// The mode of the egress policy rule which determines how traffic is being
	// handled. If set to Proxy, then the traffic will be redirected to the Apex proxy:
	// this enables access policy enforcement as well as content policy redactions. If
	// set to Passthrough, then the traffic will not be touched and simply be passed
	// through to its intended destination.
	Mode EgressPolicyRuleModeValue `json:"mode" msgpack:"mode" bson:"mode" mapstructure:"mode,omitempty"`

	// The list of providers that this rule applies to.
	Providers []string `json:"providers,omitempty" msgpack:"providers,omitempty" bson:"providers,omitempty" mapstructure:"providers,omitempty"`

	// The action to take for connections egressing from this workload that match this
	// rule. This requires the mode to be set to Proxy.
	ProxyAction EgressPolicyRuleProxyActionValue `json:"proxyAction,omitempty" msgpack:"proxyAction,omitempty" bson:"proxyaction,omitempty" mapstructure:"proxyAction,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewEgressPolicyRule returns a new *EgressPolicyRule
func NewEgressPolicyRule() *EgressPolicyRule {

	return &EgressPolicyRule{
		ModelVersion:    1,
		AppComponents:   []string{},
		ContentPolicies: []string{},
		Providers:       []string{},
		ProxyAction:     EgressPolicyRuleProxyActionNotApplicable,
	}
}
func (o *EgressPolicyRule) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *EgressPolicyRule) Identifier() string {

	return ""
}
func (o *EgressPolicyRule) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *EgressPolicyRule) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesEgressPolicyRule{}

	s.AppComponents = o.AppComponents
	s.ContentPolicies = o.ContentPolicies
	s.Mode = o.Mode
	s.Providers = o.Providers
	s.ProxyAction = o.ProxyAction

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *EgressPolicyRule) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesEgressPolicyRule{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.AppComponents = s.AppComponents
	o.ContentPolicies = s.ContentPolicies
	o.Mode = s.Mode
	o.Providers = s.Providers
	o.ProxyAction = s.ProxyAction

	return nil
}

// Version returns the hardcoded version of the model.
func (o *EgressPolicyRule) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *EgressPolicyRule) BleveType() string {

	return "egresspolicyrule"
}

// Doc returns the documentation for the object
func (o *EgressPolicyRule) Doc() string {

	return `Represents a rule for an egress policy of an application component.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *EgressPolicyRule) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *EgressPolicyRule) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the EgressPolicyRule.
func (o *EgressPolicyRule) DeepCopy() *EgressPolicyRule {

	if o == nil {
		return nil
	}

	out := &EgressPolicyRule{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *EgressPolicyRule.
func (o *EgressPolicyRule) DeepCopyInto(out *EgressPolicyRule) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy EgressPolicyRule: %s", err))
	}

	*out = *target.(*EgressPolicyRule)
}

// Validate valides the current information stored into the structure.
func (o *EgressPolicyRule) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := ValidateAppComponentReferences("appComponents", o.AppComponents); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("mode", string(o.Mode)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("mode", string(o.Mode), []string{"Proxy", "Passthrough"}, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateStringInList("proxyAction", string(o.ProxyAction), []string{"NotApplicable", "Allow", "Deny"}, false); err != nil {
		errors = errors.Append(err)
	}

	// Custom object validation.
	if err := ValidateEgressPolicyRule(o); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*EgressPolicyRule) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := EgressPolicyRuleAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return EgressPolicyRuleLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*EgressPolicyRule) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return EgressPolicyRuleAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *EgressPolicyRule) ValueForAttribute(name string) any {

	switch name {
	case "appComponents":
		return o.AppComponents
	case "contentPolicies":
		return o.ContentPolicies
	case "mode":
		return o.Mode
	case "providers":
		return o.Providers
	case "proxyAction":
		return o.ProxyAction
	}

	return nil
}

// EgressPolicyRuleAttributesMap represents the map of attribute for EgressPolicyRule.
var EgressPolicyRuleAttributesMap = map[string]elemental.AttributeSpecification{
	"AppComponents": {
		AllowedChoices: []string{},
		BSONFieldName:  "appcomponents",
		ConvertedName:  "AppComponents",
		Description: `The list of application components that this rule applies to in the form of
app/component. If the component is not specified, then this rule applies to all
components of the application.`,
		Exposed: true,
		Name:    "appComponents",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"ContentPolicies": {
		AllowedChoices: []string{},
		BSONFieldName:  "contentpolicies",
		ConvertedName:  "ContentPolicies",
		Description: `The list of content policies to apply when the workload has access to the
provider.`,
		Exposed: true,
		Name:    "contentPolicies",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"Mode": {
		AllowedChoices: []string{"Proxy", "Passthrough"},
		BSONFieldName:  "mode",
		ConvertedName:  "Mode",
		Description: `The mode of the egress policy rule which determines how traffic is being
handled. If set to Proxy, then the traffic will be redirected to the Apex proxy:
this enables access policy enforcement as well as content policy redactions. If
set to Passthrough, then the traffic will not be touched and simply be passed
through to its intended destination.`,
		Exposed:  true,
		Name:     "mode",
		Required: true,
		Stored:   true,
		Type:     "enum",
	},
	"Providers": {
		AllowedChoices: []string{},
		BSONFieldName:  "providers",
		ConvertedName:  "Providers",
		Description:    `The list of providers that this rule applies to.`,
		Exposed:        true,
		Name:           "providers",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"ProxyAction": {
		AllowedChoices: []string{"NotApplicable", "Allow", "Deny"},
		BSONFieldName:  "proxyaction",
		ConvertedName:  "ProxyAction",
		DefaultValue:   EgressPolicyRuleProxyActionNotApplicable,
		Description: `The action to take for connections egressing from this workload that match this
rule. This requires the mode to be set to Proxy.`,
		Exposed: true,
		Name:    "proxyAction",
		Stored:  true,
		Type:    "enum",
	},
}

// EgressPolicyRuleLowerCaseAttributesMap represents the map of attribute for EgressPolicyRule.
var EgressPolicyRuleLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"appcomponents": {
		AllowedChoices: []string{},
		BSONFieldName:  "appcomponents",
		ConvertedName:  "AppComponents",
		Description: `The list of application components that this rule applies to in the form of
app/component. If the component is not specified, then this rule applies to all
components of the application.`,
		Exposed: true,
		Name:    "appComponents",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"contentpolicies": {
		AllowedChoices: []string{},
		BSONFieldName:  "contentpolicies",
		ConvertedName:  "ContentPolicies",
		Description: `The list of content policies to apply when the workload has access to the
provider.`,
		Exposed: true,
		Name:    "contentPolicies",
		Stored:  true,
		SubType: "string",
		Type:    "list",
	},
	"mode": {
		AllowedChoices: []string{"Proxy", "Passthrough"},
		BSONFieldName:  "mode",
		ConvertedName:  "Mode",
		Description: `The mode of the egress policy rule which determines how traffic is being
handled. If set to Proxy, then the traffic will be redirected to the Apex proxy:
this enables access policy enforcement as well as content policy redactions. If
set to Passthrough, then the traffic will not be touched and simply be passed
through to its intended destination.`,
		Exposed:  true,
		Name:     "mode",
		Required: true,
		Stored:   true,
		Type:     "enum",
	},
	"providers": {
		AllowedChoices: []string{},
		BSONFieldName:  "providers",
		ConvertedName:  "Providers",
		Description:    `The list of providers that this rule applies to.`,
		Exposed:        true,
		Name:           "providers",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"proxyaction": {
		AllowedChoices: []string{"NotApplicable", "Allow", "Deny"},
		BSONFieldName:  "proxyaction",
		ConvertedName:  "ProxyAction",
		DefaultValue:   EgressPolicyRuleProxyActionNotApplicable,
		Description: `The action to take for connections egressing from this workload that match this
rule. This requires the mode to be set to Proxy.`,
		Exposed: true,
		Name:    "proxyAction",
		Stored:  true,
		Type:    "enum",
	},
}

type mongoAttributesEgressPolicyRule struct {
	AppComponents   []string                         `bson:"appcomponents,omitempty"`
	ContentPolicies []string                         `bson:"contentpolicies,omitempty"`
	Mode            EgressPolicyRuleModeValue        `bson:"mode"`
	Providers       []string                         `bson:"providers,omitempty"`
	ProxyAction     EgressPolicyRuleProxyActionValue `bson:"proxyaction,omitempty"`
}
