// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/identities_registry.gotpl)

package api

import "go.acuvity.ai/elemental"

var (
	identityNamesMap = map[string]elemental.Identity{
		"accesspolicy": AccessPolicyIdentity,

		"agent":       AgentIdentity,
		"agentconfig": AgentConfigIdentity,

		"agentdiscovery": AgentDiscoveryIdentity,
		"aiapp":          AIAppIdentity,

		"aidomain": AIDomainIdentity,

		"aiplugin": AIPluginIdentity,

		"aiskill":         AISkillIdentity,
		"alert":           AlertIdentity,
		"alertdefinition": AlertDefinitionIdentity,

		"alerttrigger": AlertTriggerIdentity,

		"analyzer": AnalyzerIdentity,

		"apiauthorization": APIAuthorizationIdentity,
		"app":              AppIdentity,
		"appagent":         AppAgentIdentity,
		"appcomponent":     AppComponentIdentity,

		"appgraphquery": AppGraphQueryIdentity,

		"appreport": AppReportIdentity,

		"apptoken":     AppTokenIdentity,
		"authsettings": AuthSettingsIdentity,

		"contentpolicy":  ContentPolicyIdentity,
		"customdatatype": CustomDataTypeIdentity,
		"dataset":        DataSetIdentity,

		"digestreport":        DigestReportIdentity,
		"digestreportrequest": DigestReportRequestIdentity,

		"errortransformer": ErrorTransformerIdentity,

		"extractor":    ExtractorIdentity,
		"extractorlib": ExtractorLibIdentity,

		"feedback":          FeedbackIdentity,
		"finding":           FindingIdentity,
		"findingdefinition": FindingDefinitionIdentity,
		"gitbooktoken":      GitbookTokenIdentity,

		"identitymodifier": IdentityModifierIdentity,

		"ignoreddomain": IgnoredDomainIdentity,
		"import":        ImportIdentity,
		"ingesttrace":   IngestTraceIdentity,

		"labelvalue": LabelValueIdentity,
		"landing":    LandingIdentity,
		"latency":    LatencyIdentity,
		"logbundle":  LogBundleIdentity,

		"mcpgateway": MCPGatewayIdentity,

		"metric":           MetricIdentity,
		"metriclabelvalue": MetricLabelValueIdentity,
		"metricrange":      MetricRangeIdentity,
		"metricserie":      MetricSerieIdentity,

		"mtlssource": MTLSSourceIdentity,

		"oidcsource":  OIDCSourceIdentity,
		"orgsettings": OrgSettingsIdentity,
		"orgstorage":  OrgStorageIdentity,
		"osprobe":     OSProbeIdentity,

		"pacconfig":    PACConfigIdentity,
		"pagedataview": PageDataViewIdentity,

		"policyref":    PolicyRefIdentity,
		"policyupdate": PolicyUpdateIdentity,

		"principal":         PrincipalIdentity,
		"principalapp":      PrincipalAppIdentity,
		"principalexternal": PrincipalExternalIdentity,
		"principaluser":     PrincipalUserIdentity,
		"project":           ProjectIdentity,
		"provider":          ProviderIdentity,

		"providerteam":  ProviderTeamIdentity,
		"providertoken": ProviderTokenIdentity,

		"proxyconf":      ProxyConfIdentity,
		"proxyroundtrip": ProxyRoundtripIdentity,
		"query":          QueryIdentity,
		"queryrange":     QueryRangeIdentity,
		"resolve":        ResolveIdentity,
		"role":           RoleIdentity,
		"root":           RootIdentity,
		"samlsource":     SAMLSourceIdentity,

		"scanreport": ScanReportIdentity,

		"schemaversion": SchemaVersionIdentity,
		"serie":         SerieIdentity,
		"signup":        SignupIdentity,
		"sink":          SinkIdentity,
		"sinkdatabahn":  SinkDatabahnIdentity,
		"sinkemail":     SinkEmailIdentity,
		"sinkpagerduty": SinkPagerDutyIdentity,
		"sinkslack":     SinkSlackIdentity,
		"sinksplunk":    SinkSplunkIdentity,
		"team":          TeamIdentity,

		"trace":          TraceIdentity,
		"traceref":       TraceRefIdentity,
		"tracesearch":    TraceSearchIdentity,
		"tracetagkeys":   TraceTagKeysIdentity,
		"tracetagvalues": TraceTagValuesIdentity,

		"usertoken":          UserTokenIdentity,
		"validate":           ValidateIdentity,
		"visitedurl":         VisitedURLIdentity,
		"watchedorg":         WatchedOrgIdentity,
		"webextension":       WebExtensionIdentity,
		"webextensionconfig": WebExtensionConfigIdentity,
	}

	identitycategoriesMap = map[string]elemental.Identity{
		"accesspolicies": AccessPolicyIdentity,

		"agents":       AgentIdentity,
		"agentconfigs": AgentConfigIdentity,

		"agentdiscoveries": AgentDiscoveryIdentity,
		"aiapps":           AIAppIdentity,

		"aidomains": AIDomainIdentity,

		"aiplugins": AIPluginIdentity,

		"aiskills":         AISkillIdentity,
		"alerts":           AlertIdentity,
		"alertdefinitions": AlertDefinitionIdentity,

		"alerttriggers": AlertTriggerIdentity,

		"analyzers": AnalyzerIdentity,

		"apiauthorizations": APIAuthorizationIdentity,
		"apps":              AppIdentity,
		"appagents":         AppAgentIdentity,
		"appcomponents":     AppComponentIdentity,

		"appgraphqueries": AppGraphQueryIdentity,

		"appreports": AppReportIdentity,

		"apptokens":    AppTokenIdentity,
		"authsettings": AuthSettingsIdentity,

		"contentpolicies": ContentPolicyIdentity,
		"customdatatypes": CustomDataTypeIdentity,
		"datasets":        DataSetIdentity,

		"digestreports":        DigestReportIdentity,
		"digestreportrequests": DigestReportRequestIdentity,

		"errortransformers": ErrorTransformerIdentity,

		"extractors":    ExtractorIdentity,
		"extractorlibs": ExtractorLibIdentity,

		"feedbacks":          FeedbackIdentity,
		"findings":           FindingIdentity,
		"findingdefinitions": FindingDefinitionIdentity,
		"gitbooktokens":      GitbookTokenIdentity,

		"identitymodifier": IdentityModifierIdentity,

		"ignoreddomains": IgnoredDomainIdentity,
		"import":         ImportIdentity,
		"ingesttraces":   IngestTraceIdentity,

		"labelvalues": LabelValueIdentity,
		"landings":    LandingIdentity,
		"latencies":   LatencyIdentity,
		"logbundles":  LogBundleIdentity,

		"mcpgateways": MCPGatewayIdentity,

		"metrics":           MetricIdentity,
		"metriclabelvalues": MetricLabelValueIdentity,
		"metricranges":      MetricRangeIdentity,
		"metricseries":      MetricSerieIdentity,

		"mtlssources": MTLSSourceIdentity,

		"oidcsources": OIDCSourceIdentity,
		"orgsettings": OrgSettingsIdentity,
		"orgstorages": OrgStorageIdentity,
		"osprobes":    OSProbeIdentity,

		"pacconfigs":    PACConfigIdentity,
		"pagedataviews": PageDataViewIdentity,

		"policyrefs":    PolicyRefIdentity,
		"policyupdates": PolicyUpdateIdentity,

		"principals":         PrincipalIdentity,
		"principalapps":      PrincipalAppIdentity,
		"principalexternals": PrincipalExternalIdentity,
		"principalusers":     PrincipalUserIdentity,
		"projects":           ProjectIdentity,
		"providers":          ProviderIdentity,

		"providerteams":  ProviderTeamIdentity,
		"providertokens": ProviderTokenIdentity,

		"proxyconfs":      ProxyConfIdentity,
		"proxyroundtrips": ProxyRoundtripIdentity,
		"queries":         QueryIdentity,
		"queryranges":     QueryRangeIdentity,
		"resolve":         ResolveIdentity,
		"roles":           RoleIdentity,
		"root":            RootIdentity,
		"samlsources":     SAMLSourceIdentity,

		"scanreports": ScanReportIdentity,

		"schemaversions": SchemaVersionIdentity,
		"series":         SerieIdentity,
		"signups":        SignupIdentity,
		"sinks":          SinkIdentity,
		"sinkdatabahn":   SinkDatabahnIdentity,
		"sinkemail":      SinkEmailIdentity,
		"sinkpagerduty":  SinkPagerDutyIdentity,
		"sinkslack":      SinkSlackIdentity,
		"sinksplunk":     SinkSplunkIdentity,
		"teams":          TeamIdentity,

		"traces":         TraceIdentity,
		"tracerefs":      TraceRefIdentity,
		"tracesearches":  TraceSearchIdentity,
		"tracetagkeys":   TraceTagKeysIdentity,
		"tracetagvalues": TraceTagValuesIdentity,

		"usertokens":          UserTokenIdentity,
		"validate":            ValidateIdentity,
		"visitedurls":         VisitedURLIdentity,
		"watchedorgs":         WatchedOrgIdentity,
		"webextensions":       WebExtensionIdentity,
		"webextensionconfigs": WebExtensionConfigIdentity,
	}

	aliasesMap = map[string]elemental.Identity{}

	indexesMap = map[string][][]string{
		"accesspolicy": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"agent": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "hostname"},
			{"namespace", "importLabel"},
		},
		"agentconfig": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"agentdiscovery": {
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
		},
		"aiapp": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "domain"},
			{"namespace", "importLabel"},
			{"namespace", "processNames"},
		},
		"aidomain": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "domain"},
			{"namespace", "importLabel"},
			{"namespace", "providerName"},
		},
		"aiplugin": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
			{"namespace", "vetted"},
		},
		"aiskill": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"alert": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "alertDefinitionName"},
		},
		"alertdefinition": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"alerttrigger": nil,
		"analyzer": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"apiauthorization": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"app": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
		},
		"appagent": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "hostname"},
			{"namespace", "importLabel"},
		},
		"appcomponent": nil,
		"appgraphquery": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"appreport": {
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
		},
		"apptoken": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "email"},
		},
		"authsettings": nil,
		"contentpolicy": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"customdatatype": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"dataset": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"digestreport": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
		},
		"digestreportrequest": nil,
		"errortransformer":    nil,
		"extractor": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"extractorlib": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"feedback": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "logHash", "key", "value"},
		},
		"finding": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
			{"namespace", "severity"},
			{"namespace", "status"},
		},
		"findingdefinition": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"gitbooktoken":     nil,
		"identitymodifier": nil,
		"ignoreddomain": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "domain"},
			{"namespace", "importLabel"},
		},
		"import": nil,
		"ingesttrace": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"labelvalue": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"landing": nil,
		"latency": nil,
		"logbundle": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
		},
		"mcpgateway": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"metric": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"metriclabelvalue": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"metricrange": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"metricserie": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"mtlssource": {
			{":shard", ":unique", "zone", "zHash"},
			{"fingerprints"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
			{"subjectKeyIDs"},
		},
		"oidcsource": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"orgsettings": {
			{":shard", ":unique", "zone", "zHash"},
			{"fingerprints"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"orgstorage": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"osprobe": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "associatedAppName"},
			{"namespace", "importLabel"},
			{"namespace", "type"},
		},
		"pacconfig": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"pagedataview": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "name"},
			{"namespace", "pageID"},
		},
		"policyref": nil,
		"policyupdate": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"principal":         nil,
		"principalapp":      nil,
		"principalexternal": nil,
		"principaluser":     nil,
		"project": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"provider": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"providerteam": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"providertoken": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"proxyconf": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"proxyroundtrip": {
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
		},
		"query": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"queryrange": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"resolve": nil,
		"role": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"root": nil,
		"samlsource": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"scanreport": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
		},
		"schemaversion": nil,
		"serie": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"signup": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
		},
		"sink": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"sinkdatabahn":  nil,
		"sinkemail":     nil,
		"sinkpagerduty": nil,
		"sinkslack":     nil,
		"sinksplunk":    nil,
		"team": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
		"trace": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"traceref": nil,
		"tracesearch": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"tracetagkeys": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"tracetagvalues": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"usertoken": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "email"},
		},
		"validate": nil,
		"visitedurl": {
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
		},
		"watchedorg": {
			{"namespace"},
			{"namespace", "ID"},
		},
		"webextension": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "installationID"},
		},
		"webextensionconfig": {
			{":shard", ":unique", "zone", "zHash"},
			{"namespace"},
			{"namespace", "ID"},
			{"namespace", "importLabel"},
			{"namespace", "name"},
		},
	}
)

// ModelVersion returns the current version of the model.
func ModelVersion() float64 { return 1 }

type modelManager struct{}

func (f modelManager) IdentityFromName(name string) elemental.Identity {

	return identityNamesMap[name]
}

func (f modelManager) IdentityFromCategory(category string) elemental.Identity {

	return identitycategoriesMap[category]
}

func (f modelManager) IdentityFromAlias(alias string) elemental.Identity {

	return aliasesMap[alias]
}

func (f modelManager) IdentityFromAny(any string) (i elemental.Identity) {

	if i = f.IdentityFromName(any); !i.IsEmpty() {
		return i
	}

	if i = f.IdentityFromCategory(any); !i.IsEmpty() {
		return i
	}

	return f.IdentityFromAlias(any)
}

func (f modelManager) Identifiable(identity elemental.Identity) elemental.Identifiable {

	switch identity {

	case AccessPolicyIdentity:
		return NewAccessPolicy()
	case AgentIdentity:
		return NewAgent()
	case AgentConfigIdentity:
		return NewAgentConfig()
	case AgentDiscoveryIdentity:
		return NewAgentDiscovery()
	case AIAppIdentity:
		return NewAIApp()
	case AIDomainIdentity:
		return NewAIDomain()
	case AIPluginIdentity:
		return NewAIPlugin()
	case AISkillIdentity:
		return NewAISkill()
	case AlertIdentity:
		return NewAlert()
	case AlertDefinitionIdentity:
		return NewAlertDefinition()
	case AlertTriggerIdentity:
		return NewAlertTrigger()
	case AnalyzerIdentity:
		return NewAnalyzer()
	case APIAuthorizationIdentity:
		return NewAPIAuthorization()
	case AppIdentity:
		return NewApp()
	case AppAgentIdentity:
		return NewAppAgent()
	case AppComponentIdentity:
		return NewAppComponent()
	case AppGraphQueryIdentity:
		return NewAppGraphQuery()
	case AppReportIdentity:
		return NewAppReport()
	case AppTokenIdentity:
		return NewAppToken()
	case AuthSettingsIdentity:
		return NewAuthSettings()
	case ContentPolicyIdentity:
		return NewContentPolicy()
	case CustomDataTypeIdentity:
		return NewCustomDataType()
	case DataSetIdentity:
		return NewDataSet()
	case DigestReportIdentity:
		return NewDigestReport()
	case DigestReportRequestIdentity:
		return NewDigestReportRequest()
	case ErrorTransformerIdentity:
		return NewErrorTransformer()
	case ExtractorIdentity:
		return NewExtractor()
	case ExtractorLibIdentity:
		return NewExtractorLib()
	case FeedbackIdentity:
		return NewFeedback()
	case FindingIdentity:
		return NewFinding()
	case FindingDefinitionIdentity:
		return NewFindingDefinition()
	case GitbookTokenIdentity:
		return NewGitbookToken()
	case IdentityModifierIdentity:
		return NewIdentityModifier()
	case IgnoredDomainIdentity:
		return NewIgnoredDomain()
	case ImportIdentity:
		return NewImport()
	case IngestTraceIdentity:
		return NewIngestTrace()
	case LabelValueIdentity:
		return NewLabelValue()
	case LandingIdentity:
		return NewLanding()
	case LatencyIdentity:
		return NewLatency()
	case LogBundleIdentity:
		return NewLogBundle()
	case MCPGatewayIdentity:
		return NewMCPGateway()
	case MetricIdentity:
		return NewMetric()
	case MetricLabelValueIdentity:
		return NewMetricLabelValue()
	case MetricRangeIdentity:
		return NewMetricRange()
	case MetricSerieIdentity:
		return NewMetricSerie()
	case MTLSSourceIdentity:
		return NewMTLSSource()
	case OIDCSourceIdentity:
		return NewOIDCSource()
	case OrgSettingsIdentity:
		return NewOrgSettings()
	case OrgStorageIdentity:
		return NewOrgStorage()
	case OSProbeIdentity:
		return NewOSProbe()
	case PACConfigIdentity:
		return NewPACConfig()
	case PageDataViewIdentity:
		return NewPageDataView()
	case PolicyRefIdentity:
		return NewPolicyRef()
	case PolicyUpdateIdentity:
		return NewPolicyUpdate()
	case PrincipalIdentity:
		return NewPrincipal()
	case PrincipalAppIdentity:
		return NewPrincipalApp()
	case PrincipalExternalIdentity:
		return NewPrincipalExternal()
	case PrincipalUserIdentity:
		return NewPrincipalUser()
	case ProjectIdentity:
		return NewProject()
	case ProviderIdentity:
		return NewProvider()
	case ProviderTeamIdentity:
		return NewProviderTeam()
	case ProviderTokenIdentity:
		return NewProviderToken()
	case ProxyConfIdentity:
		return NewProxyConf()
	case ProxyRoundtripIdentity:
		return NewProxyRoundtrip()
	case QueryIdentity:
		return NewQuery()
	case QueryRangeIdentity:
		return NewQueryRange()
	case ResolveIdentity:
		return NewResolve()
	case RoleIdentity:
		return NewRole()
	case RootIdentity:
		return NewRoot()
	case SAMLSourceIdentity:
		return NewSAMLSource()
	case ScanReportIdentity:
		return NewScanReport()
	case SchemaVersionIdentity:
		return NewSchemaVersion()
	case SerieIdentity:
		return NewSerie()
	case SignupIdentity:
		return NewSignup()
	case SinkIdentity:
		return NewSink()
	case SinkDatabahnIdentity:
		return NewSinkDatabahn()
	case SinkEmailIdentity:
		return NewSinkEmail()
	case SinkPagerDutyIdentity:
		return NewSinkPagerDuty()
	case SinkSlackIdentity:
		return NewSinkSlack()
	case SinkSplunkIdentity:
		return NewSinkSplunk()
	case TeamIdentity:
		return NewTeam()
	case TraceIdentity:
		return NewTrace()
	case TraceRefIdentity:
		return NewTraceRef()
	case TraceSearchIdentity:
		return NewTraceSearch()
	case TraceTagKeysIdentity:
		return NewTraceTagKeys()
	case TraceTagValuesIdentity:
		return NewTraceTagValues()
	case UserTokenIdentity:
		return NewUserToken()
	case ValidateIdentity:
		return NewValidate()
	case VisitedURLIdentity:
		return NewVisitedURL()
	case WatchedOrgIdentity:
		return NewWatchedOrg()
	case WebExtensionIdentity:
		return NewWebExtension()
	case WebExtensionConfigIdentity:
		return NewWebExtensionConfig()
	default:
		return nil
	}
}

func (f modelManager) SparseIdentifiable(identity elemental.Identity) elemental.SparseIdentifiable {

	switch identity {

	case AccessPolicyIdentity:
		return NewSparseAccessPolicy()
	case AgentIdentity:
		return NewSparseAgent()
	case AgentConfigIdentity:
		return NewSparseAgentConfig()
	case AgentDiscoveryIdentity:
		return NewSparseAgentDiscovery()
	case AIAppIdentity:
		return NewSparseAIApp()
	case AIDomainIdentity:
		return NewSparseAIDomain()
	case AIPluginIdentity:
		return NewSparseAIPlugin()
	case AISkillIdentity:
		return NewSparseAISkill()
	case AlertIdentity:
		return NewSparseAlert()
	case AlertDefinitionIdentity:
		return NewSparseAlertDefinition()
	case AlertTriggerIdentity:
		return NewSparseAlertTrigger()
	case AnalyzerIdentity:
		return NewSparseAnalyzer()
	case APIAuthorizationIdentity:
		return NewSparseAPIAuthorization()
	case AppIdentity:
		return NewSparseApp()
	case AppAgentIdentity:
		return NewSparseAppAgent()
	case AppComponentIdentity:
		return NewSparseAppComponent()
	case AppGraphQueryIdentity:
		return NewSparseAppGraphQuery()
	case AppReportIdentity:
		return NewSparseAppReport()
	case AppTokenIdentity:
		return NewSparseAppToken()
	case AuthSettingsIdentity:
		return NewSparseAuthSettings()
	case ContentPolicyIdentity:
		return NewSparseContentPolicy()
	case CustomDataTypeIdentity:
		return NewSparseCustomDataType()
	case DataSetIdentity:
		return NewSparseDataSet()
	case DigestReportIdentity:
		return NewSparseDigestReport()
	case DigestReportRequestIdentity:
		return NewSparseDigestReportRequest()
	case ErrorTransformerIdentity:
		return NewSparseErrorTransformer()
	case ExtractorIdentity:
		return NewSparseExtractor()
	case ExtractorLibIdentity:
		return NewSparseExtractorLib()
	case FeedbackIdentity:
		return NewSparseFeedback()
	case FindingIdentity:
		return NewSparseFinding()
	case FindingDefinitionIdentity:
		return NewSparseFindingDefinition()
	case GitbookTokenIdentity:
		return NewSparseGitbookToken()
	case IdentityModifierIdentity:
		return NewSparseIdentityModifier()
	case IgnoredDomainIdentity:
		return NewSparseIgnoredDomain()
	case ImportIdentity:
		return NewSparseImport()
	case IngestTraceIdentity:
		return NewSparseIngestTrace()
	case LabelValueIdentity:
		return NewSparseLabelValue()
	case LandingIdentity:
		return NewSparseLanding()
	case LatencyIdentity:
		return NewSparseLatency()
	case LogBundleIdentity:
		return NewSparseLogBundle()
	case MCPGatewayIdentity:
		return NewSparseMCPGateway()
	case MetricIdentity:
		return NewSparseMetric()
	case MetricLabelValueIdentity:
		return NewSparseMetricLabelValue()
	case MetricRangeIdentity:
		return NewSparseMetricRange()
	case MetricSerieIdentity:
		return NewSparseMetricSerie()
	case MTLSSourceIdentity:
		return NewSparseMTLSSource()
	case OIDCSourceIdentity:
		return NewSparseOIDCSource()
	case OrgSettingsIdentity:
		return NewSparseOrgSettings()
	case OrgStorageIdentity:
		return NewSparseOrgStorage()
	case OSProbeIdentity:
		return NewSparseOSProbe()
	case PACConfigIdentity:
		return NewSparsePACConfig()
	case PageDataViewIdentity:
		return NewSparsePageDataView()
	case PolicyRefIdentity:
		return NewSparsePolicyRef()
	case PolicyUpdateIdentity:
		return NewSparsePolicyUpdate()
	case PrincipalIdentity:
		return NewSparsePrincipal()
	case PrincipalAppIdentity:
		return NewSparsePrincipalApp()
	case PrincipalExternalIdentity:
		return NewSparsePrincipalExternal()
	case PrincipalUserIdentity:
		return NewSparsePrincipalUser()
	case ProjectIdentity:
		return NewSparseProject()
	case ProviderIdentity:
		return NewSparseProvider()
	case ProviderTeamIdentity:
		return NewSparseProviderTeam()
	case ProviderTokenIdentity:
		return NewSparseProviderToken()
	case ProxyConfIdentity:
		return NewSparseProxyConf()
	case ProxyRoundtripIdentity:
		return NewSparseProxyRoundtrip()
	case QueryIdentity:
		return NewSparseQuery()
	case QueryRangeIdentity:
		return NewSparseQueryRange()
	case ResolveIdentity:
		return NewSparseResolve()
	case RoleIdentity:
		return NewSparseRole()
	case SAMLSourceIdentity:
		return NewSparseSAMLSource()
	case ScanReportIdentity:
		return NewSparseScanReport()
	case SchemaVersionIdentity:
		return NewSparseSchemaVersion()
	case SerieIdentity:
		return NewSparseSerie()
	case SignupIdentity:
		return NewSparseSignup()
	case SinkIdentity:
		return NewSparseSink()
	case SinkDatabahnIdentity:
		return NewSparseSinkDatabahn()
	case SinkEmailIdentity:
		return NewSparseSinkEmail()
	case SinkPagerDutyIdentity:
		return NewSparseSinkPagerDuty()
	case SinkSlackIdentity:
		return NewSparseSinkSlack()
	case SinkSplunkIdentity:
		return NewSparseSinkSplunk()
	case TeamIdentity:
		return NewSparseTeam()
	case TraceIdentity:
		return NewSparseTrace()
	case TraceRefIdentity:
		return NewSparseTraceRef()
	case TraceSearchIdentity:
		return NewSparseTraceSearch()
	case TraceTagKeysIdentity:
		return NewSparseTraceTagKeys()
	case TraceTagValuesIdentity:
		return NewSparseTraceTagValues()
	case UserTokenIdentity:
		return NewSparseUserToken()
	case ValidateIdentity:
		return NewSparseValidate()
	case VisitedURLIdentity:
		return NewSparseVisitedURL()
	case WatchedOrgIdentity:
		return NewSparseWatchedOrg()
	case WebExtensionIdentity:
		return NewSparseWebExtension()
	case WebExtensionConfigIdentity:
		return NewSparseWebExtensionConfig()
	default:
		return nil
	}
}

func (f modelManager) Indexes(identity elemental.Identity) [][]string {

	return indexesMap[identity.Name]
}

func (f modelManager) IdentifiableFromString(any string) elemental.Identifiable {

	return f.Identifiable(f.IdentityFromAny(any))
}

func (f modelManager) Identifiables(identity elemental.Identity) elemental.Identifiables {

	switch identity {

	case AccessPolicyIdentity:
		return &AccessPoliciesList{}
	case AgentIdentity:
		return &AgentsList{}
	case AgentConfigIdentity:
		return &AgentConfigsList{}
	case AgentDiscoveryIdentity:
		return &AgentDiscoveriesList{}
	case AIAppIdentity:
		return &AIAppsList{}
	case AIDomainIdentity:
		return &AIDomainsList{}
	case AIPluginIdentity:
		return &AIPluginsList{}
	case AISkillIdentity:
		return &AISkillsList{}
	case AlertIdentity:
		return &AlertsList{}
	case AlertDefinitionIdentity:
		return &AlertDefinitionsList{}
	case AlertTriggerIdentity:
		return &AlertTriggersList{}
	case AnalyzerIdentity:
		return &AnalyzersList{}
	case APIAuthorizationIdentity:
		return &APIAuthorizationsList{}
	case AppIdentity:
		return &AppsList{}
	case AppAgentIdentity:
		return &AppAgentsList{}
	case AppComponentIdentity:
		return &AppComponentsList{}
	case AppGraphQueryIdentity:
		return &AppGraphQueriesList{}
	case AppReportIdentity:
		return &AppReportsList{}
	case AppTokenIdentity:
		return &AppTokensList{}
	case AuthSettingsIdentity:
		return &AuthSettingsList{}
	case ContentPolicyIdentity:
		return &ContentPoliciesList{}
	case CustomDataTypeIdentity:
		return &CustomDataTypesList{}
	case DataSetIdentity:
		return &DataSetsList{}
	case DigestReportIdentity:
		return &DigestReportsList{}
	case DigestReportRequestIdentity:
		return &DigestReportRequestsList{}
	case ErrorTransformerIdentity:
		return &ErrorTransformersList{}
	case ExtractorIdentity:
		return &ExtractorsList{}
	case ExtractorLibIdentity:
		return &ExtractorLibsList{}
	case FeedbackIdentity:
		return &FeedbacksList{}
	case FindingIdentity:
		return &FindingsList{}
	case FindingDefinitionIdentity:
		return &FindingDefinitionsList{}
	case GitbookTokenIdentity:
		return &GitbookTokensList{}
	case IdentityModifierIdentity:
		return &IdentityModifiersList{}
	case IgnoredDomainIdentity:
		return &IgnoredDomainsList{}
	case ImportIdentity:
		return &ImportsList{}
	case IngestTraceIdentity:
		return &IngestTracesList{}
	case LabelValueIdentity:
		return &LabelValuesList{}
	case LandingIdentity:
		return &LandingsList{}
	case LatencyIdentity:
		return &LatenciesList{}
	case LogBundleIdentity:
		return &LogBundlesList{}
	case MCPGatewayIdentity:
		return &MCPGatewaysList{}
	case MetricIdentity:
		return &MetricsList{}
	case MetricLabelValueIdentity:
		return &MetricLabelValuesList{}
	case MetricRangeIdentity:
		return &MetricRangesList{}
	case MetricSerieIdentity:
		return &MetricSeriesList{}
	case MTLSSourceIdentity:
		return &MTLSSourcesList{}
	case OIDCSourceIdentity:
		return &OIDCSourcesList{}
	case OrgSettingsIdentity:
		return &OrgSettingsList{}
	case OrgStorageIdentity:
		return &OrgStoragesList{}
	case OSProbeIdentity:
		return &OSProbesList{}
	case PACConfigIdentity:
		return &PACConfigsList{}
	case PageDataViewIdentity:
		return &PageDataViewsList{}
	case PolicyRefIdentity:
		return &PolicyRefsList{}
	case PolicyUpdateIdentity:
		return &PolicyUpdatesList{}
	case PrincipalIdentity:
		return &PrincipalsList{}
	case PrincipalAppIdentity:
		return &PrincipalAppsList{}
	case PrincipalExternalIdentity:
		return &PrincipalExternalsList{}
	case PrincipalUserIdentity:
		return &PrincipalUsersList{}
	case ProjectIdentity:
		return &ProjectsList{}
	case ProviderIdentity:
		return &ProvidersList{}
	case ProviderTeamIdentity:
		return &ProviderTeamsList{}
	case ProviderTokenIdentity:
		return &ProviderTokensList{}
	case ProxyConfIdentity:
		return &ProxyConfsList{}
	case ProxyRoundtripIdentity:
		return &ProxyRoundtripsList{}
	case QueryIdentity:
		return &QueriesList{}
	case QueryRangeIdentity:
		return &QueryRangesList{}
	case ResolveIdentity:
		return &ResolvesList{}
	case RoleIdentity:
		return &RolesList{}
	case SAMLSourceIdentity:
		return &SAMLSourcesList{}
	case ScanReportIdentity:
		return &ScanReportsList{}
	case SchemaVersionIdentity:
		return &SchemaVersionsList{}
	case SerieIdentity:
		return &SeriesList{}
	case SignupIdentity:
		return &SignupsList{}
	case SinkIdentity:
		return &SinksList{}
	case SinkDatabahnIdentity:
		return &SinkDatabahnsList{}
	case SinkEmailIdentity:
		return &SinkEmailsList{}
	case SinkPagerDutyIdentity:
		return &SinkPagerDutiesList{}
	case SinkSlackIdentity:
		return &SinkSlacksList{}
	case SinkSplunkIdentity:
		return &SinkSplunksList{}
	case TeamIdentity:
		return &TeamsList{}
	case TraceIdentity:
		return &TracesList{}
	case TraceRefIdentity:
		return &TraceRefsList{}
	case TraceSearchIdentity:
		return &TraceSearchesList{}
	case TraceTagKeysIdentity:
		return &TraceTagKeysList{}
	case TraceTagValuesIdentity:
		return &TraceTagValuesList{}
	case UserTokenIdentity:
		return &UserTokensList{}
	case ValidateIdentity:
		return &ValidatesList{}
	case VisitedURLIdentity:
		return &VisitedURLsList{}
	case WatchedOrgIdentity:
		return &WatchedOrgsList{}
	case WebExtensionIdentity:
		return &WebExtensionsList{}
	case WebExtensionConfigIdentity:
		return &WebExtensionConfigsList{}
	default:
		return nil
	}
}

func (f modelManager) SparseIdentifiables(identity elemental.Identity) elemental.SparseIdentifiables {

	switch identity {

	case AccessPolicyIdentity:
		return &SparseAccessPoliciesList{}
	case AgentIdentity:
		return &SparseAgentsList{}
	case AgentConfigIdentity:
		return &SparseAgentConfigsList{}
	case AgentDiscoveryIdentity:
		return &SparseAgentDiscoveriesList{}
	case AIAppIdentity:
		return &SparseAIAppsList{}
	case AIDomainIdentity:
		return &SparseAIDomainsList{}
	case AIPluginIdentity:
		return &SparseAIPluginsList{}
	case AISkillIdentity:
		return &SparseAISkillsList{}
	case AlertIdentity:
		return &SparseAlertsList{}
	case AlertDefinitionIdentity:
		return &SparseAlertDefinitionsList{}
	case AlertTriggerIdentity:
		return &SparseAlertTriggersList{}
	case AnalyzerIdentity:
		return &SparseAnalyzersList{}
	case APIAuthorizationIdentity:
		return &SparseAPIAuthorizationsList{}
	case AppIdentity:
		return &SparseAppsList{}
	case AppAgentIdentity:
		return &SparseAppAgentsList{}
	case AppComponentIdentity:
		return &SparseAppComponentsList{}
	case AppGraphQueryIdentity:
		return &SparseAppGraphQueriesList{}
	case AppReportIdentity:
		return &SparseAppReportsList{}
	case AppTokenIdentity:
		return &SparseAppTokensList{}
	case AuthSettingsIdentity:
		return &SparseAuthSettingsList{}
	case ContentPolicyIdentity:
		return &SparseContentPoliciesList{}
	case CustomDataTypeIdentity:
		return &SparseCustomDataTypesList{}
	case DataSetIdentity:
		return &SparseDataSetsList{}
	case DigestReportIdentity:
		return &SparseDigestReportsList{}
	case DigestReportRequestIdentity:
		return &SparseDigestReportRequestsList{}
	case ErrorTransformerIdentity:
		return &SparseErrorTransformersList{}
	case ExtractorIdentity:
		return &SparseExtractorsList{}
	case ExtractorLibIdentity:
		return &SparseExtractorLibsList{}
	case FeedbackIdentity:
		return &SparseFeedbacksList{}
	case FindingIdentity:
		return &SparseFindingsList{}
	case FindingDefinitionIdentity:
		return &SparseFindingDefinitionsList{}
	case GitbookTokenIdentity:
		return &SparseGitbookTokensList{}
	case IdentityModifierIdentity:
		return &SparseIdentityModifiersList{}
	case IgnoredDomainIdentity:
		return &SparseIgnoredDomainsList{}
	case ImportIdentity:
		return &SparseImportsList{}
	case IngestTraceIdentity:
		return &SparseIngestTracesList{}
	case LabelValueIdentity:
		return &SparseLabelValuesList{}
	case LandingIdentity:
		return &SparseLandingsList{}
	case LatencyIdentity:
		return &SparseLatenciesList{}
	case LogBundleIdentity:
		return &SparseLogBundlesList{}
	case MCPGatewayIdentity:
		return &SparseMCPGatewaysList{}
	case MetricIdentity:
		return &SparseMetricsList{}
	case MetricLabelValueIdentity:
		return &SparseMetricLabelValuesList{}
	case MetricRangeIdentity:
		return &SparseMetricRangesList{}
	case MetricSerieIdentity:
		return &SparseMetricSeriesList{}
	case MTLSSourceIdentity:
		return &SparseMTLSSourcesList{}
	case OIDCSourceIdentity:
		return &SparseOIDCSourcesList{}
	case OrgSettingsIdentity:
		return &SparseOrgSettingsList{}
	case OrgStorageIdentity:
		return &SparseOrgStoragesList{}
	case OSProbeIdentity:
		return &SparseOSProbesList{}
	case PACConfigIdentity:
		return &SparsePACConfigsList{}
	case PageDataViewIdentity:
		return &SparsePageDataViewsList{}
	case PolicyRefIdentity:
		return &SparsePolicyRefsList{}
	case PolicyUpdateIdentity:
		return &SparsePolicyUpdatesList{}
	case PrincipalIdentity:
		return &SparsePrincipalsList{}
	case PrincipalAppIdentity:
		return &SparsePrincipalAppsList{}
	case PrincipalExternalIdentity:
		return &SparsePrincipalExternalsList{}
	case PrincipalUserIdentity:
		return &SparsePrincipalUsersList{}
	case ProjectIdentity:
		return &SparseProjectsList{}
	case ProviderIdentity:
		return &SparseProvidersList{}
	case ProviderTeamIdentity:
		return &SparseProviderTeamsList{}
	case ProviderTokenIdentity:
		return &SparseProviderTokensList{}
	case ProxyConfIdentity:
		return &SparseProxyConfsList{}
	case ProxyRoundtripIdentity:
		return &SparseProxyRoundtripsList{}
	case QueryIdentity:
		return &SparseQueriesList{}
	case QueryRangeIdentity:
		return &SparseQueryRangesList{}
	case ResolveIdentity:
		return &SparseResolvesList{}
	case RoleIdentity:
		return &SparseRolesList{}
	case SAMLSourceIdentity:
		return &SparseSAMLSourcesList{}
	case ScanReportIdentity:
		return &SparseScanReportsList{}
	case SchemaVersionIdentity:
		return &SparseSchemaVersionsList{}
	case SerieIdentity:
		return &SparseSeriesList{}
	case SignupIdentity:
		return &SparseSignupsList{}
	case SinkIdentity:
		return &SparseSinksList{}
	case SinkDatabahnIdentity:
		return &SparseSinkDatabahnsList{}
	case SinkEmailIdentity:
		return &SparseSinkEmailsList{}
	case SinkPagerDutyIdentity:
		return &SparseSinkPagerDutiesList{}
	case SinkSlackIdentity:
		return &SparseSinkSlacksList{}
	case SinkSplunkIdentity:
		return &SparseSinkSplunksList{}
	case TeamIdentity:
		return &SparseTeamsList{}
	case TraceIdentity:
		return &SparseTracesList{}
	case TraceRefIdentity:
		return &SparseTraceRefsList{}
	case TraceSearchIdentity:
		return &SparseTraceSearchesList{}
	case TraceTagKeysIdentity:
		return &SparseTraceTagKeysList{}
	case TraceTagValuesIdentity:
		return &SparseTraceTagValuesList{}
	case UserTokenIdentity:
		return &SparseUserTokensList{}
	case ValidateIdentity:
		return &SparseValidatesList{}
	case VisitedURLIdentity:
		return &SparseVisitedURLsList{}
	case WatchedOrgIdentity:
		return &SparseWatchedOrgsList{}
	case WebExtensionIdentity:
		return &SparseWebExtensionsList{}
	case WebExtensionConfigIdentity:
		return &SparseWebExtensionConfigsList{}
	default:
		return nil
	}
}

func (f modelManager) IdentifiablesFromString(any string) elemental.Identifiables {

	return f.Identifiables(f.IdentityFromAny(any))
}

func (f modelManager) Relationships() elemental.RelationshipsRegistry {

	return relationshipsRegistry
}

func (f modelManager) AllIdentities() []elemental.Identity {
	return AllIdentities()
}

func (f modelManager) DetachedFromString(name string) any {

	switch name {

	case "agentdiscoveredapp", "AgentDiscoveredApp":
		return NewAgentDiscoveredApp()
	case "agentdiscoveredmcp", "AgentDiscoveredMCP":
		return NewAgentDiscoveredMCP()
	case "agentdiscoveredskill", "AgentDiscoveredSkill":
		return NewAgentDiscoveredSkill()
	case "aidcitation", "AIDCitation":
		return NewAIDCitation()
	case "aidrisk", "AIDRisk":
		return NewAIDRisk()
	case "aidsection", "AIDSection":
		return NewAIDSection()
	case "aidsectioncompliance", "AIDSectionCompliance":
		return NewAIDSectionCompliance()
	case "aidsectiondatapolicy", "AIDSectionDataPolicy":
		return NewAIDSectionDataPolicy()
	case "aidsectiondataprocessor", "AIDSectionDataProcessor":
		return NewAIDSectionDataProcessor()
	case "aidsectionllmprovider", "AIDSectionLLMProvider":
		return NewAIDSectionLLMProvider()
	case "aidsectionplan", "AIDSectionPlan":
		return NewAIDSectionPlan()
	case "aidsummary", "AIDSummary":
		return NewAIDSummary()
	case "aipluginide", "AIPluginIDE":
		return NewAIPluginIDE()
	case "aipluginwebext", "AIPluginWebExt":
		return NewAIPluginWebExt()
	case "alertevent", "AlertEvent":
		return NewAlertEvent()
	case "analysis", "Analysis":
		return NewAnalysis()
	case "analyzermatcher", "Matcher":
		return NewMatcher()
	case "analyzermodel", "AnalyzerModel":
		return NewAnalyzerModel()
	case "appcomponentegress", "AppComponentEgress":
		return NewAppComponentEgress()
	case "appcomponentingress", "AppComponentIngress":
		return NewAppComponentIngress()
	case "appcomponentselector", "AppComponentSelector":
		return NewAppComponentSelector()
	case "appgraph", "AppGraph":
		return NewAppGraph()
	case "appgraphlink", "AppGraphLink":
		return NewAppGraphLink()
	case "appgraphlinkconnection", "AppGraphLinkConnection":
		return NewAppGraphLinkConnection()
	case "appgraphlinkdns", "AppGraphLinkDNS":
		return NewAppGraphLinkDNS()
	case "appgraphlinklogentry", "AppGraphLinkLogEntry":
		return NewAppGraphLinkLogEntry()
	case "appgraphlinklogs", "AppGraphLinkLogs":
		return NewAppGraphLinkLogs()
	case "appgraphlinks", "AppGraphLinks":
		return NewAppGraphLinks()
	case "appgraphnode", "AppGraphNode":
		return NewAppGraphNode()
	case "appgraphtracelink", "AppGraphTraceLink":
		return NewAppGraphTraceLink()
	case "appselector", "AppSelector":
		return NewAppSelector()
	case "connectionencryption", "ConnectionEncryption":
		return NewConnectionEncryption()
	case "connectionreport", "ConnectionReport":
		return NewConnectionReport()
	case "destination", "Destination":
		return NewDestination()
	case "detection", "Detection":
		return NewDetection()
	case "detector", "Detector":
		return NewDetector()
	case "dnsreport", "DNSReport":
		return NewDNSReport()
	case "domainhits", "DomainHits":
		return NewDomainHits()
	case "egressdefaultpolicy", "EgressDefaultPolicy":
		return NewEgressDefaultPolicy()
	case "egresspolicy", "EgressPolicy":
		return NewEgressPolicy()
	case "egresspolicyacl", "EgressPolicyACL":
		return NewEgressPolicyACL()
	case "egresspolicyrule", "EgressPolicyRule":
		return NewEgressPolicyRule()
	case "extraction", "Extraction":
		return NewExtraction()
	case "extractioninformation", "ExtractionInformation":
		return NewExtractionInformation()
	case "extractionsummary", "ExtractionSummary":
		return NewExtractionSummary()
	case "extractorref", "ExtractorRef":
		return NewExtractorRef()
	case "host", "Host":
		return NewHost()
	case "identityref", "IdentityRef":
		return NewIdentityRef()
	case "ingressacl", "IngressACL":
		return NewIngressACL()
	case "ingresslistener", "IngressListener":
		return NewIngressListener()
	case "ingresspolicy", "IngressPolicy":
		return NewIngressPolicy()
	case "ingresspolicyrule", "IngressPolicyRule":
		return NewIngressPolicyRule()
	case "ingressproxyconfig", "IngressProxyConfig":
		return NewIngressProxyConfig()
	case "injector", "Injector":
		return NewInjector()
	case "kubernetesworkloadgroupselector", "KubernetesWorkloadGroupSelector":
		return NewKubernetesWorkloadGroupSelector()
	case "kubernetesworkloadgroupselectorcustomtype", "KubernetesWorkloadGroupSelectorCustomType":
		return NewKubernetesWorkloadGroupSelectorCustomType()
	case "kubernetesworkloadgroupsetselector", "KubernetesWorkloadGroupSetSelector":
		return NewKubernetesWorkloadGroupSetSelector()
	case "mapper", "Mapper":
		return NewMapper()
	case "mcpgatewayserver", "MCPGatewayServer":
		return NewMCPGatewayServer()
	case "mcpmessage", "MCPMessage":
		return NewMCPMessage()
	case "mcpserver", "MCPServer":
		return NewMCPServer()
	case "mcptoolannotations", "MCPToolAnnotations":
		return NewMCPToolAnnotations()
	case "modality", "Modality":
		return NewModality()
	case "moderation", "Moderation":
		return NewModeration()
	case "mtlssourceentra", "MTLSSourceEntra":
		return NewMTLSSourceEntra()
	case "mtlssourceokta", "MTLSSourceOkta":
		return NewMTLSSourceOkta()
	case "otlpendpoint", "OTLPEndpoint":
		return NewOTLPEndpoint()
	case "otlpreceiver", "OTLPReceiver":
		return NewOTLPReceiver()
	case "pagedataviewpredicate", "PageDataViewPredicate":
		return NewPageDataViewPredicate()
	case "predicate", "Predicate":
		return NewPredicate()
	case "providerretentionpolicy", "ProviderRetentionPolicy":
		return NewProviderRetentionPolicy()
	case "providertrainingpolicy", "ProviderTrainingPolicy":
		return NewProviderTrainingPolicy()
	case "scandomain", "ScanDomain":
		return NewScanDomain()
	case "scanresultadvanced", "ScanResultAdvanced":
		return NewScanResultAdvanced()
	case "scanresulthttp", "ScanResultHTTP":
		return NewScanResultHTTP()
	case "scanresultping", "ScanResultPing":
		return NewScanResultPing()
	case "scanresulttls", "ScanResultTLS":
		return NewScanResultTLS()
	case "scanuser", "ScanUser":
		return NewScanUser()
	case "textualdetection", "TextualDetection":
		return NewTextualDetection()
	case "tlscertinfo", "TLSCertInfo":
		return NewTLSCertInfo()
	case "tlsstate", "TLSState":
		return NewTLSState()
	case "tool", "Tool":
		return NewTool()
	case "toolchoice", "ToolChoice":
		return NewToolChoice()
	case "toolresult", "ToolResult":
		return NewToolResult()
	case "tooluse", "ToolUse":
		return NewToolUse()
	case "tunnelproxyauth", "TunnelProxyAuth":
		return NewTunnelProxyAuth()
	case "tunnelproxyauthbasic", "TunnelProxyAuthBasic":
		return NewTunnelProxyAuthBasic()
	case "workload", "Workload":
		return NewWorkload()
	case "workloadstatus", "WorkloadStatus":
		return NewWorkloadStatus()
	default:
		return nil
	}
}

var manager = modelManager{}

// Manager returns the model elemental.ModelManager.
func Manager() elemental.ModelManager { return manager }

// AllIdentities returns all existing identities.
func AllIdentities() []elemental.Identity {

	return []elemental.Identity{
		AccessPolicyIdentity,
		AgentIdentity,
		AgentConfigIdentity,
		AgentDiscoveryIdentity,
		AIAppIdentity,
		AIDomainIdentity,
		AIPluginIdentity,
		AISkillIdentity,
		AlertIdentity,
		AlertDefinitionIdentity,
		AlertTriggerIdentity,
		AnalyzerIdentity,
		APIAuthorizationIdentity,
		AppIdentity,
		AppAgentIdentity,
		AppComponentIdentity,
		AppGraphQueryIdentity,
		AppReportIdentity,
		AppTokenIdentity,
		AuthSettingsIdentity,
		ContentPolicyIdentity,
		CustomDataTypeIdentity,
		DataSetIdentity,
		DigestReportIdentity,
		DigestReportRequestIdentity,
		ErrorTransformerIdentity,
		ExtractorIdentity,
		ExtractorLibIdentity,
		FeedbackIdentity,
		FindingIdentity,
		FindingDefinitionIdentity,
		GitbookTokenIdentity,
		IdentityModifierIdentity,
		IgnoredDomainIdentity,
		ImportIdentity,
		IngestTraceIdentity,
		LabelValueIdentity,
		LandingIdentity,
		LatencyIdentity,
		LogBundleIdentity,
		MCPGatewayIdentity,
		MetricIdentity,
		MetricLabelValueIdentity,
		MetricRangeIdentity,
		MetricSerieIdentity,
		MTLSSourceIdentity,
		OIDCSourceIdentity,
		OrgSettingsIdentity,
		OrgStorageIdentity,
		OSProbeIdentity,
		PACConfigIdentity,
		PageDataViewIdentity,
		PolicyRefIdentity,
		PolicyUpdateIdentity,
		PrincipalIdentity,
		PrincipalAppIdentity,
		PrincipalExternalIdentity,
		PrincipalUserIdentity,
		ProjectIdentity,
		ProviderIdentity,
		ProviderTeamIdentity,
		ProviderTokenIdentity,
		ProxyConfIdentity,
		ProxyRoundtripIdentity,
		QueryIdentity,
		QueryRangeIdentity,
		ResolveIdentity,
		RoleIdentity,
		RootIdentity,
		SAMLSourceIdentity,
		ScanReportIdentity,
		SchemaVersionIdentity,
		SerieIdentity,
		SignupIdentity,
		SinkIdentity,
		SinkDatabahnIdentity,
		SinkEmailIdentity,
		SinkPagerDutyIdentity,
		SinkSlackIdentity,
		SinkSplunkIdentity,
		TeamIdentity,
		TraceIdentity,
		TraceRefIdentity,
		TraceSearchIdentity,
		TraceTagKeysIdentity,
		TraceTagValuesIdentity,
		UserTokenIdentity,
		ValidateIdentity,
		VisitedURLIdentity,
		WatchedOrgIdentity,
		WebExtensionIdentity,
		WebExtensionConfigIdentity,
	}
}

// AliasesForIdentity returns all the aliases for the given identity.
func AliasesForIdentity(identity elemental.Identity) []string {

	switch identity {
	case AccessPolicyIdentity:
		return []string{}
	case AgentIdentity:
		return []string{}
	case AgentConfigIdentity:
		return []string{}
	case AgentDiscoveryIdentity:
		return []string{}
	case AIAppIdentity:
		return []string{}
	case AIDomainIdentity:
		return []string{}
	case AIPluginIdentity:
		return []string{}
	case AISkillIdentity:
		return []string{}
	case AlertIdentity:
		return []string{}
	case AlertDefinitionIdentity:
		return []string{}
	case AlertTriggerIdentity:
		return []string{}
	case AnalyzerIdentity:
		return []string{}
	case APIAuthorizationIdentity:
		return []string{}
	case AppIdentity:
		return []string{}
	case AppAgentIdentity:
		return []string{}
	case AppComponentIdentity:
		return []string{}
	case AppGraphQueryIdentity:
		return []string{}
	case AppReportIdentity:
		return []string{}
	case AppTokenIdentity:
		return []string{}
	case AuthSettingsIdentity:
		return []string{}
	case ContentPolicyIdentity:
		return []string{}
	case CustomDataTypeIdentity:
		return []string{}
	case DataSetIdentity:
		return []string{}
	case DigestReportIdentity:
		return []string{}
	case DigestReportRequestIdentity:
		return []string{}
	case ErrorTransformerIdentity:
		return []string{}
	case ExtractorIdentity:
		return []string{}
	case ExtractorLibIdentity:
		return []string{}
	case FeedbackIdentity:
		return []string{}
	case FindingIdentity:
		return []string{}
	case FindingDefinitionIdentity:
		return []string{}
	case GitbookTokenIdentity:
		return []string{}
	case IdentityModifierIdentity:
		return []string{}
	case IgnoredDomainIdentity:
		return []string{}
	case ImportIdentity:
		return []string{}
	case IngestTraceIdentity:
		return []string{}
	case LabelValueIdentity:
		return []string{}
	case LandingIdentity:
		return []string{}
	case LatencyIdentity:
		return []string{}
	case LogBundleIdentity:
		return []string{}
	case MCPGatewayIdentity:
		return []string{}
	case MetricIdentity:
		return []string{}
	case MetricLabelValueIdentity:
		return []string{}
	case MetricRangeIdentity:
		return []string{}
	case MetricSerieIdentity:
		return []string{}
	case MTLSSourceIdentity:
		return []string{}
	case OIDCSourceIdentity:
		return []string{}
	case OrgSettingsIdentity:
		return []string{}
	case OrgStorageIdentity:
		return []string{}
	case OSProbeIdentity:
		return []string{}
	case PACConfigIdentity:
		return []string{}
	case PageDataViewIdentity:
		return []string{}
	case PolicyRefIdentity:
		return []string{}
	case PolicyUpdateIdentity:
		return []string{}
	case PrincipalIdentity:
		return []string{}
	case PrincipalAppIdentity:
		return []string{}
	case PrincipalExternalIdentity:
		return []string{}
	case PrincipalUserIdentity:
		return []string{}
	case ProjectIdentity:
		return []string{}
	case ProviderIdentity:
		return []string{}
	case ProviderTeamIdentity:
		return []string{}
	case ProviderTokenIdentity:
		return []string{}
	case ProxyConfIdentity:
		return []string{}
	case ProxyRoundtripIdentity:
		return []string{}
	case QueryIdentity:
		return []string{}
	case QueryRangeIdentity:
		return []string{}
	case ResolveIdentity:
		return []string{}
	case RoleIdentity:
		return []string{}
	case RootIdentity:
		return []string{}
	case SAMLSourceIdentity:
		return []string{}
	case ScanReportIdentity:
		return []string{}
	case SchemaVersionIdentity:
		return []string{}
	case SerieIdentity:
		return []string{}
	case SignupIdentity:
		return []string{}
	case SinkIdentity:
		return []string{}
	case SinkDatabahnIdentity:
		return []string{}
	case SinkEmailIdentity:
		return []string{}
	case SinkPagerDutyIdentity:
		return []string{}
	case SinkSlackIdentity:
		return []string{}
	case SinkSplunkIdentity:
		return []string{}
	case TeamIdentity:
		return []string{}
	case TraceIdentity:
		return []string{}
	case TraceRefIdentity:
		return []string{}
	case TraceSearchIdentity:
		return []string{}
	case TraceTagKeysIdentity:
		return []string{}
	case TraceTagValuesIdentity:
		return []string{}
	case UserTokenIdentity:
		return []string{}
	case ValidateIdentity:
		return []string{}
	case VisitedURLIdentity:
		return []string{}
	case WatchedOrgIdentity:
		return []string{}
	case WebExtensionIdentity:
		return []string{}
	case WebExtensionConfigIdentity:
		return []string{}
	}

	return nil
}
