// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// MCPToolIdentity represents the Identity of the object.
var MCPToolIdentity = elemental.Identity{
	Name:     "mcptool",
	Category: "mcptools",
	Package:  "lain",
	Private:  false,
}

// MCPToolsList represents a list of MCPTools
type MCPToolsList []*MCPTool

// Identity returns the identity of the objects in the list.
func (o MCPToolsList) Identity() elemental.Identity {

	return MCPToolIdentity
}

// Copy returns a pointer to a copy the MCPToolsList.
func (o MCPToolsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the MCPToolsList.
func (o MCPToolsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*MCPTool))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o MCPToolsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o MCPToolsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the MCPToolsList converted to SparseMCPToolsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o MCPToolsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseMCPToolsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseMCPTool)
	}

	return out
}

// Version returns the version of the content.
func (o MCPToolsList) Version() int {

	return 1
}

// MCPTool represents the model of a mcptool
type MCPTool struct {
	// The optional annotations defined for the tool.
	Annotations *MCPToolAnnotations `json:"annotations,omitempty" msgpack:"annotations,omitempty" bson:"-" mapstructure:"annotations,omitempty"`

	// The description of the tool.
	Description string `json:"description,omitempty" msgpack:"description,omitempty" bson:"-" mapstructure:"description,omitempty"`

	// The JSON schema of the tool input arguments.
	InputSchema map[string]any `json:"inputSchema,omitempty" msgpack:"inputSchema,omitempty" bson:"-" mapstructure:"inputSchema,omitempty"`

	// The name of the tool.
	Name string `json:"name,omitempty" msgpack:"name,omitempty" bson:"-" mapstructure:"name,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewMCPTool returns a new *MCPTool
func NewMCPTool() *MCPTool {

	return &MCPTool{
		ModelVersion: 1,
		InputSchema:  map[string]any{},
	}
}

// Identity returns the Identity of the object.
func (o *MCPTool) Identity() elemental.Identity {

	return MCPToolIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *MCPTool) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *MCPTool) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *MCPTool) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesMCPTool{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *MCPTool) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesMCPTool{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *MCPTool) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *MCPTool) BleveType() string {

	return "mcptool"
}

// DefaultOrder returns the list of default ordering fields.
func (o *MCPTool) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *MCPTool) Doc() string {

	return `The rendered tool shape from upstream MCP providers.`
}

func (o *MCPTool) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *MCPTool) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseMCPTool{
			Annotations: o.Annotations,
			Description: &o.Description,
			InputSchema: &o.InputSchema,
			Name:        &o.Name,
		}
	}

	sp := &SparseMCPTool{}
	for _, f := range fields {
		switch f {
		case "annotations":
			sp.Annotations = o.Annotations
		case "description":
			sp.Description = &(o.Description)
		case "inputSchema":
			sp.InputSchema = &(o.InputSchema)
		case "name":
			sp.Name = &(o.Name)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseMCPTool to the object.
func (o *MCPTool) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseMCPTool)
	if so.Annotations != nil {
		o.Annotations = so.Annotations
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.InputSchema != nil {
		o.InputSchema = *so.InputSchema
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *MCPTool) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.Annotations != nil {
		if err := o.Annotations.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'Annotations' for 'MCPTool' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *MCPTool) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.Annotations != nil {
		if err := o.Annotations.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'Annotations' for 'MCPTool' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DeepCopy returns a deep copy if the MCPTool.
func (o *MCPTool) DeepCopy() *MCPTool {

	if o == nil {
		return nil
	}

	out := &MCPTool{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *MCPTool.
func (o *MCPTool) DeepCopyInto(out *MCPTool) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy MCPTool: %s", err))
	}

	*out = *target.(*MCPTool)
}

// Validate valides the current information stored into the structure.
func (o *MCPTool) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if o.Annotations != nil {
		if err := o.Annotations.Validate(); err != nil {
			errors = errors.Append(err)
			elemental.InjectAttributePath(errors, "annotations")
		}
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*MCPTool) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := MCPToolAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return MCPToolLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*MCPTool) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return MCPToolAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *MCPTool) ValueForAttribute(name string) any {

	switch name {
	case "annotations":
		return o.Annotations
	case "description":
		return o.Description
	case "inputSchema":
		return o.InputSchema
	case "name":
		return o.Name
	}

	return nil
}

// MCPToolAttributesMap represents the map of attribute for MCPTool.
var MCPToolAttributesMap = map[string]elemental.AttributeSpecification{
	"Annotations": {
		AllowedChoices: []string{},
		ConvertedName:  "Annotations",
		Description:    `The optional annotations defined for the tool.`,
		Exposed:        true,
		Name:           "annotations",
		SubType:        "mcptoolannotations",
		Type:           "ref",
	},
	"Description": {
		AllowedChoices: []string{},
		ConvertedName:  "Description",
		Description:    `The description of the tool.`,
		Exposed:        true,
		Name:           "description",
		Type:           "string",
	},
	"InputSchema": {
		AllowedChoices: []string{},
		ConvertedName:  "InputSchema",
		Description:    `The JSON schema of the tool input arguments.`,
		Exposed:        true,
		Name:           "inputSchema",
		SubType:        "map[string]any",
		Type:           "external",
	},
	"Name": {
		AllowedChoices: []string{},
		ConvertedName:  "Name",
		Description:    `The name of the tool.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Type:           "string",
	},
}

// MCPToolLowerCaseAttributesMap represents the map of attribute for MCPTool.
var MCPToolLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"annotations": {
		AllowedChoices: []string{},
		ConvertedName:  "Annotations",
		Description:    `The optional annotations defined for the tool.`,
		Exposed:        true,
		Name:           "annotations",
		SubType:        "mcptoolannotations",
		Type:           "ref",
	},
	"description": {
		AllowedChoices: []string{},
		ConvertedName:  "Description",
		Description:    `The description of the tool.`,
		Exposed:        true,
		Name:           "description",
		Type:           "string",
	},
	"inputschema": {
		AllowedChoices: []string{},
		ConvertedName:  "InputSchema",
		Description:    `The JSON schema of the tool input arguments.`,
		Exposed:        true,
		Name:           "inputSchema",
		SubType:        "map[string]any",
		Type:           "external",
	},
	"name": {
		AllowedChoices: []string{},
		ConvertedName:  "Name",
		Description:    `The name of the tool.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Type:           "string",
	},
}

// SparseMCPToolsList represents a list of SparseMCPTools
type SparseMCPToolsList []*SparseMCPTool

// Identity returns the identity of the objects in the list.
func (o SparseMCPToolsList) Identity() elemental.Identity {

	return MCPToolIdentity
}

// Copy returns a pointer to a copy the SparseMCPToolsList.
func (o SparseMCPToolsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseMCPToolsList.
func (o SparseMCPToolsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseMCPTool))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseMCPToolsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseMCPToolsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseMCPToolsList converted to MCPToolsList.
func (o SparseMCPToolsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseMCPToolsList) Version() int {

	return 1
}

// SparseMCPTool represents the sparse version of a mcptool.
type SparseMCPTool struct {
	// The optional annotations defined for the tool.
	Annotations *MCPToolAnnotations `json:"annotations,omitempty" msgpack:"annotations,omitempty" bson:"-" mapstructure:"annotations,omitempty"`

	// The description of the tool.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"-" mapstructure:"description,omitempty"`

	// The JSON schema of the tool input arguments.
	InputSchema *map[string]any `json:"inputSchema,omitempty" msgpack:"inputSchema,omitempty" bson:"-" mapstructure:"inputSchema,omitempty"`

	// The name of the tool.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"-" mapstructure:"name,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseMCPTool returns a new  SparseMCPTool.
func NewSparseMCPTool() *SparseMCPTool {
	return &SparseMCPTool{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseMCPTool) Identity() elemental.Identity {

	return MCPToolIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseMCPTool) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseMCPTool) SetIdentifier(id string) {

}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseMCPTool) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseMCPTool{}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseMCPTool) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseMCPTool{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseMCPTool) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseMCPTool) ToPlain() elemental.PlainIdentifiable {

	out := NewMCPTool()
	if o.Annotations != nil {
		out.Annotations = o.Annotations
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.InputSchema != nil {
		out.InputSchema = *o.InputSchema
	}
	if o.Name != nil {
		out.Name = *o.Name
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseMCPTool) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.Annotations != nil {
		if err := o.Annotations.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'Annotations' for 'MCPTool' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseMCPTool) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.Annotations != nil {
		if err := o.Annotations.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'Annotations' for 'MCPTool' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DeepCopy returns a deep copy if the SparseMCPTool.
func (o *SparseMCPTool) DeepCopy() *SparseMCPTool {

	if o == nil {
		return nil
	}

	out := &SparseMCPTool{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseMCPTool.
func (o *SparseMCPTool) DeepCopyInto(out *SparseMCPTool) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseMCPTool: %s", err))
	}

	*out = *target.(*SparseMCPTool)
}

type mongoAttributesMCPTool struct {
}
type mongoAttributesSparseMCPTool struct {
}
