// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// PublicKeyIdentity represents the Identity of the object.
var PublicKeyIdentity = elemental.Identity{
	Name:     "publickey",
	Category: "publickeys",
	Package:  "lain",
	Private:  false,
}

// PublicKeysList represents a list of PublicKeys
type PublicKeysList []*PublicKey

// Identity returns the identity of the objects in the list.
func (o PublicKeysList) Identity() elemental.Identity {

	return PublicKeyIdentity
}

// Copy returns a pointer to a copy the PublicKeysList.
func (o PublicKeysList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the PublicKeysList.
func (o PublicKeysList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*PublicKey))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o PublicKeysList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o PublicKeysList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the PublicKeysList converted to SparsePublicKeysList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o PublicKeysList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparsePublicKeysList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparsePublicKey)
	}

	return out
}

// Version returns the version of the content.
func (o PublicKeysList) Version() int {

	return 1
}

// PublicKey represents the model of a publickey
type PublicKey struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// The name of the deployments whose instances hold the corresponding private key.
	Deployments []string `json:"deployments" msgpack:"deployments" bson:"deployments" mapstructure:"deployments,omitempty"`

	// The description of the public key.
	Description string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The key ID used to reference this public key.
	KeyID string `json:"keyID" msgpack:"keyID" bson:"keyid" mapstructure:"keyID,omitempty"`

	// The name of the public key.
	Name string `json:"name" msgpack:"name" bson:"name" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Propagates the object to all child namespaces. This is always true.
	Propagate bool `json:"propagate" msgpack:"propagate" bson:"propagate" mapstructure:"propagate,omitempty"`

	// PEM encoded public key.
	PublicKey string `json:"publicKey" msgpack:"publicKey" bson:"publickey" mapstructure:"publicKey,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewPublicKey returns a new *PublicKey
func NewPublicKey() *PublicKey {

	return &PublicKey{
		ModelVersion: 1,
		Deployments:  []string{},
		Propagate:    true,
	}
}

// Identity returns the Identity of the object.
func (o *PublicKey) Identity() elemental.Identity {

	return PublicKeyIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *PublicKey) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *PublicKey) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *PublicKey) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesPublicKey{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.CreateTime = o.CreateTime
	s.Deployments = o.Deployments
	s.Description = o.Description
	s.ImportHash = o.ImportHash
	s.ImportLabel = o.ImportLabel
	s.KeyID = o.KeyID
	s.Name = o.Name
	s.Namespace = o.Namespace
	s.Propagate = o.Propagate
	s.PublicKey = o.PublicKey
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *PublicKey) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesPublicKey{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.CreateTime = s.CreateTime
	o.Deployments = s.Deployments
	o.Description = s.Description
	o.ImportHash = s.ImportHash
	o.ImportLabel = s.ImportLabel
	o.KeyID = s.KeyID
	o.Name = s.Name
	o.Namespace = s.Namespace
	o.Propagate = s.Propagate
	o.PublicKey = s.PublicKey
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *PublicKey) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *PublicKey) BleveType() string {

	return "publickey"
}

// DefaultOrder returns the list of default ordering fields.
func (o *PublicKey) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *PublicKey) Doc() string {

	return `Represents a public key to which the corresponding private key must only be
available on deployment instances.`
}

func (o *PublicKey) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *PublicKey) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *PublicKey) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *PublicKey) GetImportHash() string {

	return o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the given value.
func (o *PublicKey) SetImportHash(importHash string) {

	o.ImportHash = importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *PublicKey) GetImportLabel() string {

	return o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the given value.
func (o *PublicKey) SetImportLabel(importLabel string) {

	o.ImportLabel = importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *PublicKey) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *PublicKey) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetPropagate returns the Propagate of the receiver.
func (o *PublicKey) GetPropagate() bool {

	return o.Propagate
}

// SetPropagate sets the property Propagate of the receiver using the given value.
func (o *PublicKey) SetPropagate(propagate bool) {

	o.Propagate = propagate
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *PublicKey) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *PublicKey) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *PublicKey) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparsePublicKey{
			ID:          &o.ID,
			CreateTime:  &o.CreateTime,
			Deployments: &o.Deployments,
			Description: &o.Description,
			ImportHash:  &o.ImportHash,
			ImportLabel: &o.ImportLabel,
			KeyID:       &o.KeyID,
			Name:        &o.Name,
			Namespace:   &o.Namespace,
			Propagate:   &o.Propagate,
			PublicKey:   &o.PublicKey,
			UpdateTime:  &o.UpdateTime,
			ZHash:       &o.ZHash,
			Zone:        &o.Zone,
		}
	}

	sp := &SparsePublicKey{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "deployments":
			sp.Deployments = &(o.Deployments)
		case "description":
			sp.Description = &(o.Description)
		case "importHash":
			sp.ImportHash = &(o.ImportHash)
		case "importLabel":
			sp.ImportLabel = &(o.ImportLabel)
		case "keyID":
			sp.KeyID = &(o.KeyID)
		case "name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "propagate":
			sp.Propagate = &(o.Propagate)
		case "publicKey":
			sp.PublicKey = &(o.PublicKey)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparsePublicKey to the object.
func (o *PublicKey) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparsePublicKey)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.Deployments != nil {
		o.Deployments = *so.Deployments
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.ImportHash != nil {
		o.ImportHash = *so.ImportHash
	}
	if so.ImportLabel != nil {
		o.ImportLabel = *so.ImportLabel
	}
	if so.KeyID != nil {
		o.KeyID = *so.KeyID
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.Propagate != nil {
		o.Propagate = *so.Propagate
	}
	if so.PublicKey != nil {
		o.PublicKey = *so.PublicKey
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *PublicKey) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *PublicKey) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the PublicKey.
func (o *PublicKey) DeepCopy() *PublicKey {

	if o == nil {
		return nil
	}

	out := &PublicKey{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *PublicKey.
func (o *PublicKey) DeepCopyInto(out *PublicKey) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy PublicKey: %s", err))
	}

	*out = *target.(*PublicKey)
}

// Validate valides the current information stored into the structure.
func (o *PublicKey) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("keyID", o.KeyID); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateRequiredString("publicKey", o.PublicKey); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := ValidatePEM("publicKey", o.PublicKey); err != nil {
		errors = errors.Append(err)
	}
	if err := ValidateRSAKey("publicKey", o.PublicKey); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*PublicKey) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := PublicKeyAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return PublicKeyLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*PublicKey) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return PublicKeyAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *PublicKey) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "createTime":
		return o.CreateTime
	case "deployments":
		return o.Deployments
	case "description":
		return o.Description
	case "importHash":
		return o.ImportHash
	case "importLabel":
		return o.ImportLabel
	case "keyID":
		return o.KeyID
	case "name":
		return o.Name
	case "namespace":
		return o.Namespace
	case "propagate":
		return o.Propagate
	case "publicKey":
		return o.PublicKey
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// PublicKeyAttributesMap represents the map of attribute for PublicKey.
var PublicKeyAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"Deployments": {
		AllowedChoices: []string{},
		BSONFieldName:  "deployments",
		ConvertedName:  "Deployments",
		Description:    `The name of the deployments whose instances hold the corresponding private key.`,
		Exposed:        true,
		Name:           "deployments",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the public key.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"ImportHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportLabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"KeyID": {
		AllowedChoices: []string{},
		BSONFieldName:  "keyid",
		ConvertedName:  "KeyID",
		CreationOnly:   true,
		Description:    `The key ID used to reference this public key.`,
		Exposed:        true,
		Name:           "keyID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the public key.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"Propagate": {
		AllowedChoices: []string{},
		BSONFieldName:  "propagate",
		ConvertedName:  "Propagate",
		DefaultValue:   true,
		Description:    `Propagates the object to all child namespaces. This is always true.`,
		Exposed:        true,
		Getter:         true,
		Name:           "propagate",
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},
	"PublicKey": {
		AllowedChoices: []string{},
		BSONFieldName:  "publickey",
		ConvertedName:  "PublicKey",
		CreationOnly:   true,
		Description:    `PEM encoded public key.`,
		Exposed:        true,
		Name:           "publicKey",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// PublicKeyLowerCaseAttributesMap represents the map of attribute for PublicKey.
var PublicKeyLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"deployments": {
		AllowedChoices: []string{},
		BSONFieldName:  "deployments",
		ConvertedName:  "Deployments",
		Description:    `The name of the deployments whose instances hold the corresponding private key.`,
		Exposed:        true,
		Name:           "deployments",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the public key.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"importhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importlabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"keyid": {
		AllowedChoices: []string{},
		BSONFieldName:  "keyid",
		ConvertedName:  "KeyID",
		CreationOnly:   true,
		Description:    `The key ID used to reference this public key.`,
		Exposed:        true,
		Name:           "keyID",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the public key.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"propagate": {
		AllowedChoices: []string{},
		BSONFieldName:  "propagate",
		ConvertedName:  "Propagate",
		DefaultValue:   true,
		Description:    `Propagates the object to all child namespaces. This is always true.`,
		Exposed:        true,
		Getter:         true,
		Name:           "propagate",
		Setter:         true,
		Stored:         true,
		Type:           "boolean",
	},
	"publickey": {
		AllowedChoices: []string{},
		BSONFieldName:  "publickey",
		ConvertedName:  "PublicKey",
		CreationOnly:   true,
		Description:    `PEM encoded public key.`,
		Exposed:        true,
		Name:           "publicKey",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
}

// SparsePublicKeysList represents a list of SparsePublicKeys
type SparsePublicKeysList []*SparsePublicKey

// Identity returns the identity of the objects in the list.
func (o SparsePublicKeysList) Identity() elemental.Identity {

	return PublicKeyIdentity
}

// Copy returns a pointer to a copy the SparsePublicKeysList.
func (o SparsePublicKeysList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparsePublicKeysList.
func (o SparsePublicKeysList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparsePublicKey))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparsePublicKeysList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparsePublicKeysList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparsePublicKeysList converted to PublicKeysList.
func (o SparsePublicKeysList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparsePublicKeysList) Version() int {

	return 1
}

// SparsePublicKey represents the sparse version of a publickey.
type SparsePublicKey struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// The name of the deployments whose instances hold the corresponding private key.
	Deployments *[]string `json:"deployments,omitempty" msgpack:"deployments,omitempty" bson:"deployments,omitempty" mapstructure:"deployments,omitempty"`

	// The description of the public key.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash *string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel *string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The key ID used to reference this public key.
	KeyID *string `json:"keyID,omitempty" msgpack:"keyID,omitempty" bson:"keyid,omitempty" mapstructure:"keyID,omitempty"`

	// The name of the public key.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Propagates the object to all child namespaces. This is always true.
	Propagate *bool `json:"propagate,omitempty" msgpack:"propagate,omitempty" bson:"propagate,omitempty" mapstructure:"propagate,omitempty"`

	// PEM encoded public key.
	PublicKey *string `json:"publicKey,omitempty" msgpack:"publicKey,omitempty" bson:"publickey,omitempty" mapstructure:"publicKey,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparsePublicKey returns a new  SparsePublicKey.
func NewSparsePublicKey() *SparsePublicKey {
	return &SparsePublicKey{}
}

// Identity returns the Identity of the sparse object.
func (o *SparsePublicKey) Identity() elemental.Identity {

	return PublicKeyIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparsePublicKey) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparsePublicKey) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparsePublicKey) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparsePublicKey{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.Deployments != nil {
		s.Deployments = o.Deployments
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.ImportHash != nil {
		s.ImportHash = o.ImportHash
	}
	if o.ImportLabel != nil {
		s.ImportLabel = o.ImportLabel
	}
	if o.KeyID != nil {
		s.KeyID = o.KeyID
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.Propagate != nil {
		s.Propagate = o.Propagate
	}
	if o.PublicKey != nil {
		s.PublicKey = o.PublicKey
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparsePublicKey) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparsePublicKey{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.Deployments != nil {
		o.Deployments = s.Deployments
	}
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.ImportHash != nil {
		o.ImportHash = s.ImportHash
	}
	if s.ImportLabel != nil {
		o.ImportLabel = s.ImportLabel
	}
	if s.KeyID != nil {
		o.KeyID = s.KeyID
	}
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.Propagate != nil {
		o.Propagate = s.Propagate
	}
	if s.PublicKey != nil {
		o.PublicKey = s.PublicKey
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparsePublicKey) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparsePublicKey) ToPlain() elemental.PlainIdentifiable {

	out := NewPublicKey()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.Deployments != nil {
		out.Deployments = *o.Deployments
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.ImportHash != nil {
		out.ImportHash = *o.ImportHash
	}
	if o.ImportLabel != nil {
		out.ImportLabel = *o.ImportLabel
	}
	if o.KeyID != nil {
		out.KeyID = *o.KeyID
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.Propagate != nil {
		out.Propagate = *o.Propagate
	}
	if o.PublicKey != nil {
		out.PublicKey = *o.PublicKey
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparsePublicKey) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparsePublicKey) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparsePublicKey) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparsePublicKey) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *SparsePublicKey) GetImportHash() (out string) {

	if o.ImportHash == nil {
		return
	}

	return *o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the address of the given value.
func (o *SparsePublicKey) SetImportHash(importHash string) {

	o.ImportHash = &importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *SparsePublicKey) GetImportLabel() (out string) {

	if o.ImportLabel == nil {
		return
	}

	return *o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the address of the given value.
func (o *SparsePublicKey) SetImportLabel(importLabel string) {

	o.ImportLabel = &importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparsePublicKey) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparsePublicKey) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetPropagate returns the Propagate of the receiver.
func (o *SparsePublicKey) GetPropagate() (out bool) {

	if o.Propagate == nil {
		return
	}

	return *o.Propagate
}

// SetPropagate sets the property Propagate of the receiver using the address of the given value.
func (o *SparsePublicKey) SetPropagate(propagate bool) {

	o.Propagate = &propagate
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparsePublicKey) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparsePublicKey) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// DeepCopy returns a deep copy if the SparsePublicKey.
func (o *SparsePublicKey) DeepCopy() *SparsePublicKey {

	if o == nil {
		return nil
	}

	out := &SparsePublicKey{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparsePublicKey.
func (o *SparsePublicKey) DeepCopyInto(out *SparsePublicKey) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparsePublicKey: %s", err))
	}

	*out = *target.(*SparsePublicKey)
}

type mongoAttributesPublicKey struct {
	ID          bson.ObjectId `bson:"_id,omitempty"`
	CreateTime  time.Time     `bson:"createtime"`
	Deployments []string      `bson:"deployments"`
	Description string        `bson:"description,omitempty"`
	ImportHash  string        `bson:"importhash,omitempty"`
	ImportLabel string        `bson:"importlabel,omitempty"`
	KeyID       string        `bson:"keyid"`
	Name        string        `bson:"name"`
	Namespace   string        `bson:"namespace,omitempty"`
	Propagate   bool          `bson:"propagate"`
	PublicKey   string        `bson:"publickey"`
	UpdateTime  time.Time     `bson:"updatetime"`
	ZHash       int           `bson:"zhash"`
	Zone        int           `bson:"zone"`
}
type mongoAttributesSparsePublicKey struct {
	ID          bson.ObjectId `bson:"_id,omitempty"`
	CreateTime  *time.Time    `bson:"createtime,omitempty"`
	Deployments *[]string     `bson:"deployments,omitempty"`
	Description *string       `bson:"description,omitempty"`
	ImportHash  *string       `bson:"importhash,omitempty"`
	ImportLabel *string       `bson:"importlabel,omitempty"`
	KeyID       *string       `bson:"keyid,omitempty"`
	Name        *string       `bson:"name,omitempty"`
	Namespace   *string       `bson:"namespace,omitempty"`
	Propagate   *bool         `bson:"propagate,omitempty"`
	PublicKey   *string       `bson:"publickey,omitempty"`
	UpdateTime  *time.Time    `bson:"updatetime,omitempty"`
	ZHash       *int          `bson:"zhash,omitempty"`
	Zone        *int          `bson:"zone,omitempty"`
}
