// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// RiskFindingSeverityValue represents the possible values for attribute "severity".
type RiskFindingSeverityValue string

const (
	// RiskFindingSeverityCritical represents the value Critical.
	RiskFindingSeverityCritical RiskFindingSeverityValue = "Critical"

	// RiskFindingSeverityHigh represents the value High.
	RiskFindingSeverityHigh RiskFindingSeverityValue = "High"

	// RiskFindingSeverityLow represents the value Low.
	RiskFindingSeverityLow RiskFindingSeverityValue = "Low"

	// RiskFindingSeverityMedium represents the value Medium.
	RiskFindingSeverityMedium RiskFindingSeverityValue = "Medium"
)

// RiskFindingStatusValue represents the possible values for attribute "status".
type RiskFindingStatusValue string

const (
	// RiskFindingStatusArchived represents the value Archived.
	RiskFindingStatusArchived RiskFindingStatusValue = "Archived"

	// RiskFindingStatusOpen represents the value Open.
	RiskFindingStatusOpen RiskFindingStatusValue = "Open"

	// RiskFindingStatusRejected represents the value Rejected.
	RiskFindingStatusRejected RiskFindingStatusValue = "Rejected"

	// RiskFindingStatusResolved represents the value Resolved.
	RiskFindingStatusResolved RiskFindingStatusValue = "Resolved"
)

// RiskFindingSystemGeneratedSeverityValue represents the possible values for attribute "systemGeneratedSeverity".
type RiskFindingSystemGeneratedSeverityValue string

const (
	// RiskFindingSystemGeneratedSeverityCritical represents the value Critical.
	RiskFindingSystemGeneratedSeverityCritical RiskFindingSystemGeneratedSeverityValue = "Critical"

	// RiskFindingSystemGeneratedSeverityHigh represents the value High.
	RiskFindingSystemGeneratedSeverityHigh RiskFindingSystemGeneratedSeverityValue = "High"

	// RiskFindingSystemGeneratedSeverityLow represents the value Low.
	RiskFindingSystemGeneratedSeverityLow RiskFindingSystemGeneratedSeverityValue = "Low"

	// RiskFindingSystemGeneratedSeverityMedium represents the value Medium.
	RiskFindingSystemGeneratedSeverityMedium RiskFindingSystemGeneratedSeverityValue = "Medium"
)

// RiskFindingIdentity represents the Identity of the object.
var RiskFindingIdentity = elemental.Identity{
	Name:     "riskfinding",
	Category: "riskfindings",
	Package:  "hanni",
	Private:  false,
}

// RiskFindingsList represents a list of RiskFindings
type RiskFindingsList []*RiskFinding

// Identity returns the identity of the objects in the list.
func (o RiskFindingsList) Identity() elemental.Identity {

	return RiskFindingIdentity
}

// Copy returns a pointer to a copy the RiskFindingsList.
func (o RiskFindingsList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the RiskFindingsList.
func (o RiskFindingsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*RiskFinding))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o RiskFindingsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o RiskFindingsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the RiskFindingsList converted to SparseRiskFindingsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o RiskFindingsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseRiskFindingsList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseRiskFinding)
	}

	return out
}

// Version returns the version of the content.
func (o RiskFindingsList) Version() int {

	return 1
}

// RiskFinding represents the model of a riskfinding
type RiskFinding struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The analyzer group.
	AnalyzerGroup string `json:"analyzerGroup,omitempty" msgpack:"analyzerGroup,omitempty" bson:"analyzergroup,omitempty" mapstructure:"analyzerGroup,omitempty"`

	// The analyzer name.
	AnalyzerName string `json:"analyzerName,omitempty" msgpack:"analyzerName,omitempty" bson:"analyzername,omitempty" mapstructure:"analyzerName,omitempty"`

	// Reference to the asset this finding applies to.
	AssetRef *AssetRef `json:"assetRef,omitempty" msgpack:"assetRef,omitempty" bson:"assetref,omitempty" mapstructure:"assetRef,omitempty"`

	// The description of the finding.
	Description string `json:"description" msgpack:"description" bson:"description" mapstructure:"description,omitempty"`

	// First time the finding was seen.
	FirstSeenTime time.Time `json:"firstSeenTime" msgpack:"firstSeenTime" bson:"firstseentime" mapstructure:"firstSeenTime,omitempty"`

	// Friendly name of the object.
	FriendlyName string `json:"friendlyName" msgpack:"friendlyName" bson:"friendlyname" mapstructure:"friendlyName,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// Comment about the last resolution.
	LastResolutionComment string `json:"lastResolutionComment,omitempty" msgpack:"lastResolutionComment,omitempty" bson:"lastresolutioncomment,omitempty" mapstructure:"lastResolutionComment,omitempty"`

	// Last time the finding was seen.
	LastSeenTime time.Time `json:"lastSeenTime" msgpack:"lastSeenTime" bson:"lastseentime" mapstructure:"lastSeenTime,omitempty"`

	// The internal reference name of the object. It is a sanitized version of Friendly
	// Name if empty.
	Name string `json:"name" msgpack:"name" bson:"name" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The identities that can resolve this finding.
	ResolutionIdentities []string `json:"resolutionIdentities" msgpack:"resolutionIdentities" bson:"resolutionidentities" mapstructure:"resolutionIdentities,omitempty"`

	// The severity of the finding.
	Severity RiskFindingSeverityValue `json:"severity" msgpack:"severity" bson:"severity" mapstructure:"severity,omitempty"`

	// User override of the system generated severity. When set, the severity
	// attribute reflects the override.
	SeverityOverride *SeverityOverride `json:"severityOverride,omitempty" msgpack:"severityOverride,omitempty" bson:"severityoverride,omitempty" mapstructure:"severityOverride,omitempty"`

	// The state of the finding.
	State map[string]any `json:"state,omitempty" msgpack:"state,omitempty" bson:"state,omitempty" mapstructure:"state,omitempty"`

	// The status of the finding.
	Status RiskFindingStatusValue `json:"status" msgpack:"status" bson:"status" mapstructure:"status,omitempty"`

	// The severity computed by the system when the finding was created. Not
	// affected by user overrides.
	SystemGeneratedSeverity RiskFindingSystemGeneratedSeverityValue `json:"systemGeneratedSeverity,omitempty" msgpack:"systemGeneratedSeverity,omitempty" bson:"systemgeneratedseverity,omitempty" mapstructure:"systemGeneratedSeverity,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewRiskFinding returns a new *RiskFinding
func NewRiskFinding() *RiskFinding {

	return &RiskFinding{
		ModelVersion:         1,
		ResolutionIdentities: []string{},
		State:                map[string]any{},
	}
}

// Identity returns the Identity of the object.
func (o *RiskFinding) Identity() elemental.Identity {

	return RiskFindingIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *RiskFinding) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *RiskFinding) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *RiskFinding) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesRiskFinding{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.AnalyzerGroup = o.AnalyzerGroup
	s.AnalyzerName = o.AnalyzerName
	s.AssetRef = o.AssetRef
	s.Description = o.Description
	s.FirstSeenTime = o.FirstSeenTime
	s.FriendlyName = o.FriendlyName
	s.ImportHash = o.ImportHash
	s.ImportLabel = o.ImportLabel
	s.LastResolutionComment = o.LastResolutionComment
	s.LastSeenTime = o.LastSeenTime
	s.Name = o.Name
	s.Namespace = o.Namespace
	s.ResolutionIdentities = o.ResolutionIdentities
	s.Severity = o.Severity
	s.SeverityOverride = o.SeverityOverride
	s.State = o.State
	s.Status = o.Status
	s.SystemGeneratedSeverity = o.SystemGeneratedSeverity
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *RiskFinding) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesRiskFinding{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.AnalyzerGroup = s.AnalyzerGroup
	o.AnalyzerName = s.AnalyzerName
	o.AssetRef = s.AssetRef
	o.Description = s.Description
	o.FirstSeenTime = s.FirstSeenTime
	o.FriendlyName = s.FriendlyName
	o.ImportHash = s.ImportHash
	o.ImportLabel = s.ImportLabel
	o.LastResolutionComment = s.LastResolutionComment
	o.LastSeenTime = s.LastSeenTime
	o.Name = s.Name
	o.Namespace = s.Namespace
	o.ResolutionIdentities = s.ResolutionIdentities
	o.Severity = s.Severity
	o.SeverityOverride = s.SeverityOverride
	o.State = s.State
	o.Status = s.Status
	o.SystemGeneratedSeverity = s.SystemGeneratedSeverity
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *RiskFinding) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *RiskFinding) BleveType() string {

	return "riskfinding"
}

// DefaultOrder returns the list of default ordering fields.
func (o *RiskFinding) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *RiskFinding) Doc() string {

	return `Defines a risk finding instantiated from a risk definition that matched a
discovered AI asset.`
}

func (o *RiskFinding) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetFriendlyName returns the FriendlyName of the receiver.
func (o *RiskFinding) GetFriendlyName() string {

	return o.FriendlyName
}

// SetFriendlyName sets the property FriendlyName of the receiver using the given value.
func (o *RiskFinding) SetFriendlyName(friendlyName string) {

	o.FriendlyName = friendlyName
}

// GetImportHash returns the ImportHash of the receiver.
func (o *RiskFinding) GetImportHash() string {

	return o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the given value.
func (o *RiskFinding) SetImportHash(importHash string) {

	o.ImportHash = importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *RiskFinding) GetImportLabel() string {

	return o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the given value.
func (o *RiskFinding) SetImportLabel(importLabel string) {

	o.ImportLabel = importLabel
}

// GetName returns the Name of the receiver.
func (o *RiskFinding) GetName() string {

	return o.Name
}

// SetName sets the property Name of the receiver using the given value.
func (o *RiskFinding) SetName(name string) {

	o.Name = name
}

// GetNamespace returns the Namespace of the receiver.
func (o *RiskFinding) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *RiskFinding) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *RiskFinding) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseRiskFinding{
			ID:                      &o.ID,
			AnalyzerGroup:           &o.AnalyzerGroup,
			AnalyzerName:            &o.AnalyzerName,
			AssetRef:                o.AssetRef,
			Description:             &o.Description,
			FirstSeenTime:           &o.FirstSeenTime,
			FriendlyName:            &o.FriendlyName,
			ImportHash:              &o.ImportHash,
			ImportLabel:             &o.ImportLabel,
			LastResolutionComment:   &o.LastResolutionComment,
			LastSeenTime:            &o.LastSeenTime,
			Name:                    &o.Name,
			Namespace:               &o.Namespace,
			ResolutionIdentities:    &o.ResolutionIdentities,
			Severity:                &o.Severity,
			SeverityOverride:        o.SeverityOverride,
			State:                   &o.State,
			Status:                  &o.Status,
			SystemGeneratedSeverity: &o.SystemGeneratedSeverity,
			ZHash:                   &o.ZHash,
			Zone:                    &o.Zone,
		}
	}

	sp := &SparseRiskFinding{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "analyzerGroup":
			sp.AnalyzerGroup = &(o.AnalyzerGroup)
		case "analyzerName":
			sp.AnalyzerName = &(o.AnalyzerName)
		case "assetRef":
			sp.AssetRef = o.AssetRef
		case "description":
			sp.Description = &(o.Description)
		case "firstSeenTime":
			sp.FirstSeenTime = &(o.FirstSeenTime)
		case "friendlyName":
			sp.FriendlyName = &(o.FriendlyName)
		case "importHash":
			sp.ImportHash = &(o.ImportHash)
		case "importLabel":
			sp.ImportLabel = &(o.ImportLabel)
		case "lastResolutionComment":
			sp.LastResolutionComment = &(o.LastResolutionComment)
		case "lastSeenTime":
			sp.LastSeenTime = &(o.LastSeenTime)
		case "name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "resolutionIdentities":
			sp.ResolutionIdentities = &(o.ResolutionIdentities)
		case "severity":
			sp.Severity = &(o.Severity)
		case "severityOverride":
			sp.SeverityOverride = o.SeverityOverride
		case "state":
			sp.State = &(o.State)
		case "status":
			sp.Status = &(o.Status)
		case "systemGeneratedSeverity":
			sp.SystemGeneratedSeverity = &(o.SystemGeneratedSeverity)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseRiskFinding to the object.
func (o *RiskFinding) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseRiskFinding)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.AnalyzerGroup != nil {
		o.AnalyzerGroup = *so.AnalyzerGroup
	}
	if so.AnalyzerName != nil {
		o.AnalyzerName = *so.AnalyzerName
	}
	if so.AssetRef != nil {
		o.AssetRef = so.AssetRef
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.FirstSeenTime != nil {
		o.FirstSeenTime = *so.FirstSeenTime
	}
	if so.FriendlyName != nil {
		o.FriendlyName = *so.FriendlyName
	}
	if so.ImportHash != nil {
		o.ImportHash = *so.ImportHash
	}
	if so.ImportLabel != nil {
		o.ImportLabel = *so.ImportLabel
	}
	if so.LastResolutionComment != nil {
		o.LastResolutionComment = *so.LastResolutionComment
	}
	if so.LastSeenTime != nil {
		o.LastSeenTime = *so.LastSeenTime
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.ResolutionIdentities != nil {
		o.ResolutionIdentities = *so.ResolutionIdentities
	}
	if so.Severity != nil {
		o.Severity = *so.Severity
	}
	if so.SeverityOverride != nil {
		o.SeverityOverride = so.SeverityOverride
	}
	if so.State != nil {
		o.State = *so.State
	}
	if so.Status != nil {
		o.Status = *so.Status
	}
	if so.SystemGeneratedSeverity != nil {
		o.SystemGeneratedSeverity = *so.SystemGeneratedSeverity
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *RiskFinding) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.AssetRef != nil {
		if err := o.AssetRef.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'AssetRef' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	if o.SeverityOverride != nil {
		if err := o.SeverityOverride.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'SeverityOverride' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *RiskFinding) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.AssetRef != nil {
		if err := o.AssetRef.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'AssetRef' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	if o.SeverityOverride != nil {
		if err := o.SeverityOverride.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'SeverityOverride' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DeepCopy returns a deep copy if the RiskFinding.
func (o *RiskFinding) DeepCopy() *RiskFinding {

	if o == nil {
		return nil
	}

	out := &RiskFinding{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *RiskFinding.
func (o *RiskFinding) DeepCopyInto(out *RiskFinding) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy RiskFinding: %s", err))
	}

	*out = *target.(*RiskFinding)
}

// Validate valides the current information stored into the structure.
func (o *RiskFinding) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if o.AssetRef != nil {
		if err := o.AssetRef.Validate(); err != nil {
			errors = errors.Append(err)
			elemental.InjectAttributePath(errors, "assetRef")
		}
	}

	if err := elemental.ValidateRequiredString("friendlyName", o.FriendlyName); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := ValidateFriendlyName("friendlyName", o.FriendlyName); err != nil {
		errors = errors.Append(err)
	}
	if err := ValidateTrimmed("friendlyName", o.FriendlyName); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidatePattern("name", o.Name, `^[a-zA-Z0-9-_]+$`, `must only contain alpha numerical characters, '-' or '_'.`, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("severity", string(o.Severity)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("severity", string(o.Severity), []string{"Low", "Medium", "High", "Critical"}, false); err != nil {
		errors = errors.Append(err)
	}

	if o.SeverityOverride != nil {
		if err := o.SeverityOverride.Validate(); err != nil {
			errors = errors.Append(err)
			elemental.InjectAttributePath(errors, "severityOverride")
		}
	}

	if err := elemental.ValidateRequiredString("status", string(o.Status)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("status", string(o.Status), []string{"Open", "Resolved", "Rejected", "Archived"}, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateStringInList("systemGeneratedSeverity", string(o.SystemGeneratedSeverity), []string{"Low", "Medium", "High", "Critical"}, true); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*RiskFinding) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := RiskFindingAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return RiskFindingLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*RiskFinding) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return RiskFindingAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *RiskFinding) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "analyzerGroup":
		return o.AnalyzerGroup
	case "analyzerName":
		return o.AnalyzerName
	case "assetRef":
		return o.AssetRef
	case "description":
		return o.Description
	case "firstSeenTime":
		return o.FirstSeenTime
	case "friendlyName":
		return o.FriendlyName
	case "importHash":
		return o.ImportHash
	case "importLabel":
		return o.ImportLabel
	case "lastResolutionComment":
		return o.LastResolutionComment
	case "lastSeenTime":
		return o.LastSeenTime
	case "name":
		return o.Name
	case "namespace":
		return o.Namespace
	case "resolutionIdentities":
		return o.ResolutionIdentities
	case "severity":
		return o.Severity
	case "severityOverride":
		return o.SeverityOverride
	case "state":
		return o.State
	case "status":
		return o.Status
	case "systemGeneratedSeverity":
		return o.SystemGeneratedSeverity
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// RiskFindingAttributesMap represents the map of attribute for RiskFinding.
var RiskFindingAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"AnalyzerGroup": {
		AllowedChoices: []string{},
		BSONFieldName:  "analyzergroup",
		ConvertedName:  "AnalyzerGroup",
		Description:    `The analyzer group.`,
		Exposed:        true,
		Name:           "analyzerGroup",
		Stored:         true,
		Type:           "string",
	},
	"AnalyzerName": {
		AllowedChoices: []string{},
		BSONFieldName:  "analyzername",
		ConvertedName:  "AnalyzerName",
		Description:    `The analyzer name.`,
		Exposed:        true,
		Name:           "analyzerName",
		Stored:         true,
		Type:           "string",
	},
	"AssetRef": {
		AllowedChoices: []string{},
		BSONFieldName:  "assetref",
		ConvertedName:  "AssetRef",
		Description:    `Reference to the asset this finding applies to.`,
		Exposed:        true,
		Name:           "assetRef",
		Stored:         true,
		SubType:        "assetref",
		Type:           "ref",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the finding.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"FirstSeenTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "firstseentime",
		ConvertedName:  "FirstSeenTime",
		Description:    `First time the finding was seen.`,
		Exposed:        true,
		Name:           "firstSeenTime",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"FriendlyName": {
		AllowedChoices: []string{},
		BSONFieldName:  "friendlyname",
		ConvertedName:  "FriendlyName",
		Description:    `Friendly name of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "friendlyName",
		Required:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportLabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"LastResolutionComment": {
		AllowedChoices: []string{},
		BSONFieldName:  "lastresolutioncomment",
		ConvertedName:  "LastResolutionComment",
		Description:    `Comment about the last resolution.`,
		Exposed:        true,
		Name:           "lastResolutionComment",
		Stored:         true,
		Type:           "string",
	},
	"LastSeenTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "lastseentime",
		ConvertedName:  "LastSeenTime",
		Description:    `Last time the finding was seen.`,
		Exposed:        true,
		Name:           "lastSeenTime",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"Name": {
		AllowedChars:   `^[a-zA-Z0-9-_]+$`,
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		CreationOnly:   true,
		Description: `The internal reference name of the object. It is a sanitized version of Friendly
Name if empty.`,
		Exposed: true,
		Getter:  true,
		Name:    "name",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ResolutionIdentities": {
		AllowedChoices: []string{},
		BSONFieldName:  "resolutionidentities",
		ConvertedName:  "ResolutionIdentities",
		Description:    `The identities that can resolve this finding.`,
		Exposed:        true,
		Name:           "resolutionIdentities",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"Severity": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		BSONFieldName:  "severity",
		ConvertedName:  "Severity",
		Description:    `The severity of the finding.`,
		Exposed:        true,
		Name:           "severity",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"SeverityOverride": {
		AllowedChoices: []string{},
		BSONFieldName:  "severityoverride",
		ConvertedName:  "SeverityOverride",
		Description: `User override of the system generated severity. When set, the severity
attribute reflects the override.`,
		Exposed: true,
		Name:    "severityOverride",
		Stored:  true,
		SubType: "severityoverride",
		Type:    "ref",
	},
	"State": {
		AllowedChoices: []string{},
		BSONFieldName:  "state",
		ConvertedName:  "State",
		Description:    `The state of the finding.`,
		Exposed:        true,
		Name:           "state",
		Stored:         true,
		SubType:        "map[string]any",
		Type:           "external",
	},
	"Status": {
		AllowedChoices: []string{"Open", "Resolved", "Rejected", "Archived"},
		BSONFieldName:  "status",
		ConvertedName:  "Status",
		Description:    `The status of the finding.`,
		Exposed:        true,
		Name:           "status",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"SystemGeneratedSeverity": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		Autogenerated:  true,
		BSONFieldName:  "systemgeneratedseverity",
		ConvertedName:  "SystemGeneratedSeverity",
		Description: `The severity computed by the system when the finding was created. Not
affected by user overrides.`,
		Exposed: true,
		Name:    "systemGeneratedSeverity",
		Stored:  true,
		Type:    "enum",
	},
}

// RiskFindingLowerCaseAttributesMap represents the map of attribute for RiskFinding.
var RiskFindingLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"analyzergroup": {
		AllowedChoices: []string{},
		BSONFieldName:  "analyzergroup",
		ConvertedName:  "AnalyzerGroup",
		Description:    `The analyzer group.`,
		Exposed:        true,
		Name:           "analyzerGroup",
		Stored:         true,
		Type:           "string",
	},
	"analyzername": {
		AllowedChoices: []string{},
		BSONFieldName:  "analyzername",
		ConvertedName:  "AnalyzerName",
		Description:    `The analyzer name.`,
		Exposed:        true,
		Name:           "analyzerName",
		Stored:         true,
		Type:           "string",
	},
	"assetref": {
		AllowedChoices: []string{},
		BSONFieldName:  "assetref",
		ConvertedName:  "AssetRef",
		Description:    `Reference to the asset this finding applies to.`,
		Exposed:        true,
		Name:           "assetRef",
		Stored:         true,
		SubType:        "assetref",
		Type:           "ref",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `The description of the finding.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"firstseentime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "firstseentime",
		ConvertedName:  "FirstSeenTime",
		Description:    `First time the finding was seen.`,
		Exposed:        true,
		Name:           "firstSeenTime",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"friendlyname": {
		AllowedChoices: []string{},
		BSONFieldName:  "friendlyname",
		ConvertedName:  "FriendlyName",
		Description:    `Friendly name of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "friendlyName",
		Required:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importlabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"lastresolutioncomment": {
		AllowedChoices: []string{},
		BSONFieldName:  "lastresolutioncomment",
		ConvertedName:  "LastResolutionComment",
		Description:    `Comment about the last resolution.`,
		Exposed:        true,
		Name:           "lastResolutionComment",
		Stored:         true,
		Type:           "string",
	},
	"lastseentime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "lastseentime",
		ConvertedName:  "LastSeenTime",
		Description:    `Last time the finding was seen.`,
		Exposed:        true,
		Name:           "lastSeenTime",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"name": {
		AllowedChars:   `^[a-zA-Z0-9-_]+$`,
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		CreationOnly:   true,
		Description: `The internal reference name of the object. It is a sanitized version of Friendly
Name if empty.`,
		Exposed: true,
		Getter:  true,
		Name:    "name",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"resolutionidentities": {
		AllowedChoices: []string{},
		BSONFieldName:  "resolutionidentities",
		ConvertedName:  "ResolutionIdentities",
		Description:    `The identities that can resolve this finding.`,
		Exposed:        true,
		Name:           "resolutionIdentities",
		Stored:         true,
		SubType:        "string",
		Type:           "list",
	},
	"severity": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		BSONFieldName:  "severity",
		ConvertedName:  "Severity",
		Description:    `The severity of the finding.`,
		Exposed:        true,
		Name:           "severity",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"severityoverride": {
		AllowedChoices: []string{},
		BSONFieldName:  "severityoverride",
		ConvertedName:  "SeverityOverride",
		Description: `User override of the system generated severity. When set, the severity
attribute reflects the override.`,
		Exposed: true,
		Name:    "severityOverride",
		Stored:  true,
		SubType: "severityoverride",
		Type:    "ref",
	},
	"state": {
		AllowedChoices: []string{},
		BSONFieldName:  "state",
		ConvertedName:  "State",
		Description:    `The state of the finding.`,
		Exposed:        true,
		Name:           "state",
		Stored:         true,
		SubType:        "map[string]any",
		Type:           "external",
	},
	"status": {
		AllowedChoices: []string{"Open", "Resolved", "Rejected", "Archived"},
		BSONFieldName:  "status",
		ConvertedName:  "Status",
		Description:    `The status of the finding.`,
		Exposed:        true,
		Name:           "status",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"systemgeneratedseverity": {
		AllowedChoices: []string{"Low", "Medium", "High", "Critical"},
		Autogenerated:  true,
		BSONFieldName:  "systemgeneratedseverity",
		ConvertedName:  "SystemGeneratedSeverity",
		Description: `The severity computed by the system when the finding was created. Not
affected by user overrides.`,
		Exposed: true,
		Name:    "systemGeneratedSeverity",
		Stored:  true,
		Type:    "enum",
	},
}

// SparseRiskFindingsList represents a list of SparseRiskFindings
type SparseRiskFindingsList []*SparseRiskFinding

// Identity returns the identity of the objects in the list.
func (o SparseRiskFindingsList) Identity() elemental.Identity {

	return RiskFindingIdentity
}

// Copy returns a pointer to a copy the SparseRiskFindingsList.
func (o SparseRiskFindingsList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseRiskFindingsList.
func (o SparseRiskFindingsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseRiskFinding))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseRiskFindingsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseRiskFindingsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseRiskFindingsList converted to RiskFindingsList.
func (o SparseRiskFindingsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseRiskFindingsList) Version() int {

	return 1
}

// SparseRiskFinding represents the sparse version of a riskfinding.
type SparseRiskFinding struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The analyzer group.
	AnalyzerGroup *string `json:"analyzerGroup,omitempty" msgpack:"analyzerGroup,omitempty" bson:"analyzergroup,omitempty" mapstructure:"analyzerGroup,omitempty"`

	// The analyzer name.
	AnalyzerName *string `json:"analyzerName,omitempty" msgpack:"analyzerName,omitempty" bson:"analyzername,omitempty" mapstructure:"analyzerName,omitempty"`

	// Reference to the asset this finding applies to.
	AssetRef *AssetRef `json:"assetRef,omitempty" msgpack:"assetRef,omitempty" bson:"assetref,omitempty" mapstructure:"assetRef,omitempty"`

	// The description of the finding.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// First time the finding was seen.
	FirstSeenTime *time.Time `json:"firstSeenTime,omitempty" msgpack:"firstSeenTime,omitempty" bson:"firstseentime,omitempty" mapstructure:"firstSeenTime,omitempty"`

	// Friendly name of the object.
	FriendlyName *string `json:"friendlyName,omitempty" msgpack:"friendlyName,omitempty" bson:"friendlyname,omitempty" mapstructure:"friendlyName,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash *string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel *string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// Comment about the last resolution.
	LastResolutionComment *string `json:"lastResolutionComment,omitempty" msgpack:"lastResolutionComment,omitempty" bson:"lastresolutioncomment,omitempty" mapstructure:"lastResolutionComment,omitempty"`

	// Last time the finding was seen.
	LastSeenTime *time.Time `json:"lastSeenTime,omitempty" msgpack:"lastSeenTime,omitempty" bson:"lastseentime,omitempty" mapstructure:"lastSeenTime,omitempty"`

	// The internal reference name of the object. It is a sanitized version of Friendly
	// Name if empty.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The identities that can resolve this finding.
	ResolutionIdentities *[]string `json:"resolutionIdentities,omitempty" msgpack:"resolutionIdentities,omitempty" bson:"resolutionidentities,omitempty" mapstructure:"resolutionIdentities,omitempty"`

	// The severity of the finding.
	Severity *RiskFindingSeverityValue `json:"severity,omitempty" msgpack:"severity,omitempty" bson:"severity,omitempty" mapstructure:"severity,omitempty"`

	// User override of the system generated severity. When set, the severity
	// attribute reflects the override.
	SeverityOverride *SeverityOverride `json:"severityOverride,omitempty" msgpack:"severityOverride,omitempty" bson:"severityoverride,omitempty" mapstructure:"severityOverride,omitempty"`

	// The state of the finding.
	State *map[string]any `json:"state,omitempty" msgpack:"state,omitempty" bson:"state,omitempty" mapstructure:"state,omitempty"`

	// The status of the finding.
	Status *RiskFindingStatusValue `json:"status,omitempty" msgpack:"status,omitempty" bson:"status,omitempty" mapstructure:"status,omitempty"`

	// The severity computed by the system when the finding was created. Not
	// affected by user overrides.
	SystemGeneratedSeverity *RiskFindingSystemGeneratedSeverityValue `json:"systemGeneratedSeverity,omitempty" msgpack:"systemGeneratedSeverity,omitempty" bson:"systemgeneratedseverity,omitempty" mapstructure:"systemGeneratedSeverity,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseRiskFinding returns a new  SparseRiskFinding.
func NewSparseRiskFinding() *SparseRiskFinding {
	return &SparseRiskFinding{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseRiskFinding) Identity() elemental.Identity {

	return RiskFindingIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseRiskFinding) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseRiskFinding) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseRiskFinding) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseRiskFinding{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.AnalyzerGroup != nil {
		s.AnalyzerGroup = o.AnalyzerGroup
	}
	if o.AnalyzerName != nil {
		s.AnalyzerName = o.AnalyzerName
	}
	if o.AssetRef != nil {
		s.AssetRef = o.AssetRef
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.FirstSeenTime != nil {
		s.FirstSeenTime = o.FirstSeenTime
	}
	if o.FriendlyName != nil {
		s.FriendlyName = o.FriendlyName
	}
	if o.ImportHash != nil {
		s.ImportHash = o.ImportHash
	}
	if o.ImportLabel != nil {
		s.ImportLabel = o.ImportLabel
	}
	if o.LastResolutionComment != nil {
		s.LastResolutionComment = o.LastResolutionComment
	}
	if o.LastSeenTime != nil {
		s.LastSeenTime = o.LastSeenTime
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.ResolutionIdentities != nil {
		s.ResolutionIdentities = o.ResolutionIdentities
	}
	if o.Severity != nil {
		s.Severity = o.Severity
	}
	if o.SeverityOverride != nil {
		s.SeverityOverride = o.SeverityOverride
	}
	if o.State != nil {
		s.State = o.State
	}
	if o.Status != nil {
		s.Status = o.Status
	}
	if o.SystemGeneratedSeverity != nil {
		s.SystemGeneratedSeverity = o.SystemGeneratedSeverity
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseRiskFinding) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseRiskFinding{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.AnalyzerGroup != nil {
		o.AnalyzerGroup = s.AnalyzerGroup
	}
	if s.AnalyzerName != nil {
		o.AnalyzerName = s.AnalyzerName
	}
	if s.AssetRef != nil {
		o.AssetRef = s.AssetRef
	}
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.FirstSeenTime != nil {
		o.FirstSeenTime = s.FirstSeenTime
	}
	if s.FriendlyName != nil {
		o.FriendlyName = s.FriendlyName
	}
	if s.ImportHash != nil {
		o.ImportHash = s.ImportHash
	}
	if s.ImportLabel != nil {
		o.ImportLabel = s.ImportLabel
	}
	if s.LastResolutionComment != nil {
		o.LastResolutionComment = s.LastResolutionComment
	}
	if s.LastSeenTime != nil {
		o.LastSeenTime = s.LastSeenTime
	}
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.ResolutionIdentities != nil {
		o.ResolutionIdentities = s.ResolutionIdentities
	}
	if s.Severity != nil {
		o.Severity = s.Severity
	}
	if s.SeverityOverride != nil {
		o.SeverityOverride = s.SeverityOverride
	}
	if s.State != nil {
		o.State = s.State
	}
	if s.Status != nil {
		o.Status = s.Status
	}
	if s.SystemGeneratedSeverity != nil {
		o.SystemGeneratedSeverity = s.SystemGeneratedSeverity
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseRiskFinding) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseRiskFinding) ToPlain() elemental.PlainIdentifiable {

	out := NewRiskFinding()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.AnalyzerGroup != nil {
		out.AnalyzerGroup = *o.AnalyzerGroup
	}
	if o.AnalyzerName != nil {
		out.AnalyzerName = *o.AnalyzerName
	}
	if o.AssetRef != nil {
		out.AssetRef = o.AssetRef
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.FirstSeenTime != nil {
		out.FirstSeenTime = *o.FirstSeenTime
	}
	if o.FriendlyName != nil {
		out.FriendlyName = *o.FriendlyName
	}
	if o.ImportHash != nil {
		out.ImportHash = *o.ImportHash
	}
	if o.ImportLabel != nil {
		out.ImportLabel = *o.ImportLabel
	}
	if o.LastResolutionComment != nil {
		out.LastResolutionComment = *o.LastResolutionComment
	}
	if o.LastSeenTime != nil {
		out.LastSeenTime = *o.LastSeenTime
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.ResolutionIdentities != nil {
		out.ResolutionIdentities = *o.ResolutionIdentities
	}
	if o.Severity != nil {
		out.Severity = *o.Severity
	}
	if o.SeverityOverride != nil {
		out.SeverityOverride = o.SeverityOverride
	}
	if o.State != nil {
		out.State = *o.State
	}
	if o.Status != nil {
		out.Status = *o.Status
	}
	if o.SystemGeneratedSeverity != nil {
		out.SystemGeneratedSeverity = *o.SystemGeneratedSeverity
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *SparseRiskFinding) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.AssetRef != nil {
		if err := o.AssetRef.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'AssetRef' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	if o.SeverityOverride != nil {
		if err := o.SeverityOverride.EncryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to encrypt ref attribute 'SeverityOverride' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *SparseRiskFinding) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	if o.AssetRef != nil {
		if err := o.AssetRef.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'AssetRef' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	if o.SeverityOverride != nil {
		if err := o.SeverityOverride.DecryptAttributes(encrypter); err != nil {
			return fmt.Errorf("unable to decrypt ref attribute 'SeverityOverride' for 'RiskFinding' (%s): %w", o.Identifier(), err)
		}
	}

	return nil
}

// GetFriendlyName returns the FriendlyName of the receiver.
func (o *SparseRiskFinding) GetFriendlyName() (out string) {

	if o.FriendlyName == nil {
		return
	}

	return *o.FriendlyName
}

// SetFriendlyName sets the property FriendlyName of the receiver using the address of the given value.
func (o *SparseRiskFinding) SetFriendlyName(friendlyName string) {

	o.FriendlyName = &friendlyName
}

// GetImportHash returns the ImportHash of the receiver.
func (o *SparseRiskFinding) GetImportHash() (out string) {

	if o.ImportHash == nil {
		return
	}

	return *o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the address of the given value.
func (o *SparseRiskFinding) SetImportHash(importHash string) {

	o.ImportHash = &importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *SparseRiskFinding) GetImportLabel() (out string) {

	if o.ImportLabel == nil {
		return
	}

	return *o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the address of the given value.
func (o *SparseRiskFinding) SetImportLabel(importLabel string) {

	o.ImportLabel = &importLabel
}

// GetName returns the Name of the receiver.
func (o *SparseRiskFinding) GetName() (out string) {

	if o.Name == nil {
		return
	}

	return *o.Name
}

// SetName sets the property Name of the receiver using the address of the given value.
func (o *SparseRiskFinding) SetName(name string) {

	o.Name = &name
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseRiskFinding) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseRiskFinding) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// DeepCopy returns a deep copy if the SparseRiskFinding.
func (o *SparseRiskFinding) DeepCopy() *SparseRiskFinding {

	if o == nil {
		return nil
	}

	out := &SparseRiskFinding{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseRiskFinding.
func (o *SparseRiskFinding) DeepCopyInto(out *SparseRiskFinding) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseRiskFinding: %s", err))
	}

	*out = *target.(*SparseRiskFinding)
}

type mongoAttributesRiskFinding struct {
	ID                      bson.ObjectId                           `bson:"_id,omitempty"`
	AnalyzerGroup           string                                  `bson:"analyzergroup,omitempty"`
	AnalyzerName            string                                  `bson:"analyzername,omitempty"`
	AssetRef                *AssetRef                               `bson:"assetref,omitempty"`
	Description             string                                  `bson:"description"`
	FirstSeenTime           time.Time                               `bson:"firstseentime"`
	FriendlyName            string                                  `bson:"friendlyname"`
	ImportHash              string                                  `bson:"importhash,omitempty"`
	ImportLabel             string                                  `bson:"importlabel,omitempty"`
	LastResolutionComment   string                                  `bson:"lastresolutioncomment,omitempty"`
	LastSeenTime            time.Time                               `bson:"lastseentime"`
	Name                    string                                  `bson:"name"`
	Namespace               string                                  `bson:"namespace,omitempty"`
	ResolutionIdentities    []string                                `bson:"resolutionidentities"`
	Severity                RiskFindingSeverityValue                `bson:"severity"`
	SeverityOverride        *SeverityOverride                       `bson:"severityoverride,omitempty"`
	State                   map[string]any                          `bson:"state,omitempty"`
	Status                  RiskFindingStatusValue                  `bson:"status"`
	SystemGeneratedSeverity RiskFindingSystemGeneratedSeverityValue `bson:"systemgeneratedseverity,omitempty"`
	ZHash                   int                                     `bson:"zhash"`
	Zone                    int                                     `bson:"zone"`
}
type mongoAttributesSparseRiskFinding struct {
	ID                      bson.ObjectId                            `bson:"_id,omitempty"`
	AnalyzerGroup           *string                                  `bson:"analyzergroup,omitempty"`
	AnalyzerName            *string                                  `bson:"analyzername,omitempty"`
	AssetRef                *AssetRef                                `bson:"assetref,omitempty"`
	Description             *string                                  `bson:"description,omitempty"`
	FirstSeenTime           *time.Time                               `bson:"firstseentime,omitempty"`
	FriendlyName            *string                                  `bson:"friendlyname,omitempty"`
	ImportHash              *string                                  `bson:"importhash,omitempty"`
	ImportLabel             *string                                  `bson:"importlabel,omitempty"`
	LastResolutionComment   *string                                  `bson:"lastresolutioncomment,omitempty"`
	LastSeenTime            *time.Time                               `bson:"lastseentime,omitempty"`
	Name                    *string                                  `bson:"name,omitempty"`
	Namespace               *string                                  `bson:"namespace,omitempty"`
	ResolutionIdentities    *[]string                                `bson:"resolutionidentities,omitempty"`
	Severity                *RiskFindingSeverityValue                `bson:"severity,omitempty"`
	SeverityOverride        *SeverityOverride                        `bson:"severityoverride,omitempty"`
	State                   *map[string]any                          `bson:"state,omitempty"`
	Status                  *RiskFindingStatusValue                  `bson:"status,omitempty"`
	SystemGeneratedSeverity *RiskFindingSystemGeneratedSeverityValue `bson:"systemgeneratedseverity,omitempty"`
	ZHash                   *int                                     `bson:"zhash,omitempty"`
	Zone                    *int                                     `bson:"zone,omitempty"`
}
