// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// TLSStateTLSVersionValue represents the possible values for attribute "TLSVersion".
type TLSStateTLSVersionValue string

const (
	// TLSStateTLSVersionTLS10 represents the value TLS10.
	TLSStateTLSVersionTLS10 TLSStateTLSVersionValue = "TLS10"

	// TLSStateTLSVersionTLS11 represents the value TLS11.
	TLSStateTLSVersionTLS11 TLSStateTLSVersionValue = "TLS11"

	// TLSStateTLSVersionTLS12 represents the value TLS12.
	TLSStateTLSVersionTLS12 TLSStateTLSVersionValue = "TLS12"

	// TLSStateTLSVersionTLS13 represents the value TLS13.
	TLSStateTLSVersionTLS13 TLSStateTLSVersionValue = "TLS13"
)

// TLSState represents the model of a tlsstate
type TLSState struct {
	// The application protocol being used that was negotiated with ALPN for this
	// connection.
	ALPNNegotiatedProtocol string `json:"ALPNNegotiatedProtocol,omitempty" msgpack:"ALPNNegotiatedProtocol,omitempty" bson:"alpnnegotiatedprotocol,omitempty" mapstructure:"ALPNNegotiatedProtocol,omitempty"`

	// The TLS protocol version used for the connection.
	TLSVersion TLSStateTLSVersionValue `json:"TLSVersion" msgpack:"TLSVersion" bson:"tlsversion" mapstructure:"TLSVersion,omitempty"`

	// The negotiated cipher suite of the connection.
	CipherSuite string `json:"cipherSuite" msgpack:"cipherSuite" bson:"ciphersuite" mapstructure:"cipherSuite,omitempty"`

	// The TLS library/provider/implementation used for the connection if known.
	Implementation string `json:"implementation,omitempty" msgpack:"implementation,omitempty" bson:"implementation,omitempty" mapstructure:"implementation,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewTLSState returns a new *TLSState
func NewTLSState() *TLSState {

	return &TLSState{
		ModelVersion: 1,
	}
}
func (o *TLSState) Identity() elemental.Identity {

	return elemental.Identity{}
}
func (o *TLSState) Identifier() string {

	return ""
}
func (o *TLSState) SetIdentifier(id string) {
	panic("you cannot set identifier on a detached object")
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *TLSState) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesTLSState{}

	s.ALPNNegotiatedProtocol = o.ALPNNegotiatedProtocol
	s.TLSVersion = o.TLSVersion
	s.CipherSuite = o.CipherSuite
	s.Implementation = o.Implementation

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *TLSState) SetBSON(raw bson.Raw) error {

	if o == nil || raw.Kind == bson.ElementNil {
		return bson.ErrSetZero
	}

	s := &mongoAttributesTLSState{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ALPNNegotiatedProtocol = s.ALPNNegotiatedProtocol
	o.TLSVersion = s.TLSVersion
	o.CipherSuite = s.CipherSuite
	o.Implementation = s.Implementation

	return nil
}

// Version returns the hardcoded version of the model.
func (o *TLSState) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *TLSState) BleveType() string {

	return "tlsstate"
}

// Doc returns the documentation for the object
func (o *TLSState) Doc() string {

	return `Represents the TLS state of a connection.`
}

// EncryptAttributes encrypts the attributes marked as `encrypted` using the given encrypter.
func (o *TLSState) EncryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DecryptAttributes decrypts the attributes marked as `encrypted` using the given decrypter.
func (o *TLSState) DecryptAttributes(encrypter elemental.AttributeEncrypter) (err error) {

	return nil
}

// DeepCopy returns a deep copy if the TLSState.
func (o *TLSState) DeepCopy() *TLSState {

	if o == nil {
		return nil
	}

	out := &TLSState{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *TLSState.
func (o *TLSState) DeepCopyInto(out *TLSState) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy TLSState: %s", err))
	}

	*out = *target.(*TLSState)
}

// Validate valides the current information stored into the structure.
func (o *TLSState) Validate() error {

	elemental.ResetDefaultForZeroValues(o)

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("TLSVersion", string(o.TLSVersion)); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := elemental.ValidateStringInList("TLSVersion", string(o.TLSVersion), []string{"TLS10", "TLS11", "TLS12", "TLS13"}, false); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("cipherSuite", o.CipherSuite); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*TLSState) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := TLSStateAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return TLSStateLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*TLSState) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return TLSStateAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *TLSState) ValueForAttribute(name string) any {

	switch name {
	case "ALPNNegotiatedProtocol":
		return o.ALPNNegotiatedProtocol
	case "TLSVersion":
		return o.TLSVersion
	case "cipherSuite":
		return o.CipherSuite
	case "implementation":
		return o.Implementation
	}

	return nil
}

// TLSStateAttributesMap represents the map of attribute for TLSState.
var TLSStateAttributesMap = map[string]elemental.AttributeSpecification{
	"ALPNNegotiatedProtocol": {
		AllowedChoices: []string{},
		BSONFieldName:  "alpnnegotiatedprotocol",
		ConvertedName:  "ALPNNegotiatedProtocol",
		Description: `The application protocol being used that was negotiated with ALPN for this
connection.`,
		Exposed: true,
		Name:    "ALPNNegotiatedProtocol",
		Stored:  true,
		Type:    "string",
	},
	"TLSVersion": {
		AllowedChoices: []string{"TLS10", "TLS11", "TLS12", "TLS13"},
		BSONFieldName:  "tlsversion",
		ConvertedName:  "TLSVersion",
		Description:    `The TLS protocol version used for the connection.`,
		Exposed:        true,
		Name:           "TLSVersion",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"CipherSuite": {
		AllowedChoices: []string{},
		BSONFieldName:  "ciphersuite",
		ConvertedName:  "CipherSuite",
		Description:    `The negotiated cipher suite of the connection.`,
		Exposed:        true,
		Name:           "cipherSuite",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Implementation": {
		AllowedChoices: []string{},
		BSONFieldName:  "implementation",
		ConvertedName:  "Implementation",
		Description:    `The TLS library/provider/implementation used for the connection if known.`,
		Exposed:        true,
		Name:           "implementation",
		Stored:         true,
		Type:           "string",
	},
}

// TLSStateLowerCaseAttributesMap represents the map of attribute for TLSState.
var TLSStateLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"alpnnegotiatedprotocol": {
		AllowedChoices: []string{},
		BSONFieldName:  "alpnnegotiatedprotocol",
		ConvertedName:  "ALPNNegotiatedProtocol",
		Description: `The application protocol being used that was negotiated with ALPN for this
connection.`,
		Exposed: true,
		Name:    "ALPNNegotiatedProtocol",
		Stored:  true,
		Type:    "string",
	},
	"tlsversion": {
		AllowedChoices: []string{"TLS10", "TLS11", "TLS12", "TLS13"},
		BSONFieldName:  "tlsversion",
		ConvertedName:  "TLSVersion",
		Description:    `The TLS protocol version used for the connection.`,
		Exposed:        true,
		Name:           "TLSVersion",
		Required:       true,
		Stored:         true,
		Type:           "enum",
	},
	"ciphersuite": {
		AllowedChoices: []string{},
		BSONFieldName:  "ciphersuite",
		ConvertedName:  "CipherSuite",
		Description:    `The negotiated cipher suite of the connection.`,
		Exposed:        true,
		Name:           "cipherSuite",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"implementation": {
		AllowedChoices: []string{},
		BSONFieldName:  "implementation",
		ConvertedName:  "Implementation",
		Description:    `The TLS library/provider/implementation used for the connection if known.`,
		Exposed:        true,
		Name:           "implementation",
		Stored:         true,
		Type:           "string",
	},
}

type mongoAttributesTLSState struct {
	ALPNNegotiatedProtocol string                  `bson:"alpnnegotiatedprotocol,omitempty"`
	TLSVersion             TLSStateTLSVersionValue `bson:"tlsversion"`
	CipherSuite            string                  `bson:"ciphersuite"`
	Implementation         string                  `bson:"implementation,omitempty"`
}
