// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"slices"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// TraceSearchIdentity represents the Identity of the object.
var TraceSearchIdentity = elemental.Identity{
	Name:     "tracesearch",
	Category: "tracesearches",
	Package:  "snitch",
	Private:  false,
}

// TraceSearchesList represents a list of TraceSearches
type TraceSearchesList []*TraceSearch

// Identity returns the identity of the objects in the list.
func (o TraceSearchesList) Identity() elemental.Identity {

	return TraceSearchIdentity
}

// Copy returns a pointer to a copy the TraceSearchesList.
func (o TraceSearchesList) Copy() elemental.Identifiables {

	out := slices.Clone(o)
	return &out
}

// Append appends the objects to the a new copy of the TraceSearchesList.
func (o TraceSearchesList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*TraceSearch))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o TraceSearchesList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o TraceSearchesList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the TraceSearchesList converted to SparseTraceSearchesList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o TraceSearchesList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseTraceSearchesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToSparse(fields...).(*SparseTraceSearch)
	}

	return out
}

// Version returns the version of the content.
func (o TraceSearchesList) Version() int {

	return 1
}

// TraceSearch represents the model of a tracesearch
type TraceSearch struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The end of the time window in any format supported by
	// https://github.com/araddon/dateparse.
	End string `json:"end,omitempty" msgpack:"end,omitempty" bson:"-" mapstructure:"end,omitempty"`

	// The relative end of the time window as time.Duration.
	EndRelative string `json:"endRelative,omitempty" msgpack:"endRelative,omitempty" bson:"-" mapstructure:"endRelative,omitempty"`

	// Limit the number of search result.
	Limit int `json:"limit,omitempty" msgpack:"limit,omitempty" bson:"-" mapstructure:"limit,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The query in TraceQL format.
	Query string `json:"query" msgpack:"query" bson:"-" mapstructure:"query,omitempty"`

	// The result of the request.
	Result []map[string]any `json:"result" msgpack:"result" bson:"-" mapstructure:"result,omitempty"`

	// The max number of spans to return per span set. If set to -1, it means no span
	// at all. 0 will use the default value (3).
	SpansPerSpanSet int `json:"spansPerSpanSet,omitempty" msgpack:"spansPerSpanSet,omitempty" bson:"-" mapstructure:"spansPerSpanSet,omitempty"`

	// The start of the time window in any format supported by
	// https://github.com/araddon/dateparse.
	Start string `json:"start,omitempty" msgpack:"start,omitempty" bson:"-" mapstructure:"start,omitempty"`

	// The relative start of the time window as time.Duration.
	StartRelative string `json:"startRelative,omitempty" msgpack:"startRelative,omitempty" bson:"-" mapstructure:"startRelative,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewTraceSearch returns a new *TraceSearch
func NewTraceSearch() *TraceSearch {

	return &TraceSearch{
		ModelVersion:    1,
		Limit:           20,
		Result:          []map[string]any{},
		SpansPerSpanSet: 3,
	}
}

// Identity returns the Identity of the object.
func (o *TraceSearch) Identity() elemental.Identity {

	return TraceSearchIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *TraceSearch) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *TraceSearch) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *TraceSearch) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesTraceSearch{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Namespace = o.Namespace

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *TraceSearch) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesTraceSearch{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Namespace = s.Namespace

	return nil
}

// Version returns the hardcoded version of the model.
func (o *TraceSearch) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *TraceSearch) BleveType() string {

	return "tracesearch"
}

// DefaultOrder returns the list of default ordering fields.
func (o *TraceSearch) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *TraceSearch) Doc() string {

	return `This is a OTEL TraceQL query wrapper.`
}

func (o *TraceSearch) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetEnd returns the End of the receiver.
func (o *TraceSearch) GetEnd() string {

	return o.End
}

// SetEnd sets the property End of the receiver using the given value.
func (o *TraceSearch) SetEnd(end string) {

	o.End = end
}

// GetEndRelative returns the EndRelative of the receiver.
func (o *TraceSearch) GetEndRelative() string {

	return o.EndRelative
}

// GetNamespace returns the Namespace of the receiver.
func (o *TraceSearch) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *TraceSearch) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetStart returns the Start of the receiver.
func (o *TraceSearch) GetStart() string {

	return o.Start
}

// SetStart sets the property Start of the receiver using the given value.
func (o *TraceSearch) SetStart(start string) {

	o.Start = start
}

// GetStartRelative returns the StartRelative of the receiver.
func (o *TraceSearch) GetStartRelative() string {

	return o.StartRelative
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *TraceSearch) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseTraceSearch{
			ID:              &o.ID,
			End:             &o.End,
			EndRelative:     &o.EndRelative,
			Limit:           &o.Limit,
			Namespace:       &o.Namespace,
			Query:           &o.Query,
			Result:          &o.Result,
			SpansPerSpanSet: &o.SpansPerSpanSet,
			Start:           &o.Start,
			StartRelative:   &o.StartRelative,
		}
	}

	sp := &SparseTraceSearch{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "end":
			sp.End = &(o.End)
		case "endRelative":
			sp.EndRelative = &(o.EndRelative)
		case "limit":
			sp.Limit = &(o.Limit)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "query":
			sp.Query = &(o.Query)
		case "result":
			sp.Result = &(o.Result)
		case "spansPerSpanSet":
			sp.SpansPerSpanSet = &(o.SpansPerSpanSet)
		case "start":
			sp.Start = &(o.Start)
		case "startRelative":
			sp.StartRelative = &(o.StartRelative)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseTraceSearch to the object.
func (o *TraceSearch) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseTraceSearch)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.End != nil {
		o.End = *so.End
	}
	if so.EndRelative != nil {
		o.EndRelative = *so.EndRelative
	}
	if so.Limit != nil {
		o.Limit = *so.Limit
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.Query != nil {
		o.Query = *so.Query
	}
	if so.Result != nil {
		o.Result = *so.Result
	}
	if so.SpansPerSpanSet != nil {
		o.SpansPerSpanSet = *so.SpansPerSpanSet
	}
	if so.Start != nil {
		o.Start = *so.Start
	}
	if so.StartRelative != nil {
		o.StartRelative = *so.StartRelative
	}
}

// DeepCopy returns a deep copy if the TraceSearch.
func (o *TraceSearch) DeepCopy() *TraceSearch {

	if o == nil {
		return nil
	}

	out := &TraceSearch{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *TraceSearch.
func (o *TraceSearch) DeepCopyInto(out *TraceSearch) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy TraceSearch: %s", err))
	}

	*out = *target.(*TraceSearch)
}

// Validate valides the current information stored into the structure.
func (o *TraceSearch) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := ValidateDuration("endRelative", o.EndRelative); err != nil {
		errors = errors.Append(err)
	}

	if err := elemental.ValidateRequiredString("query", o.Query); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if err := ValidateDuration("startRelative", o.StartRelative); err != nil {
		errors = errors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*TraceSearch) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := TraceSearchAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return TraceSearchLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*TraceSearch) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return TraceSearchAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *TraceSearch) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "end":
		return o.End
	case "endRelative":
		return o.EndRelative
	case "limit":
		return o.Limit
	case "namespace":
		return o.Namespace
	case "query":
		return o.Query
	case "result":
		return o.Result
	case "spansPerSpanSet":
		return o.SpansPerSpanSet
	case "start":
		return o.Start
	case "startRelative":
		return o.StartRelative
	}

	return nil
}

// TraceSearchAttributesMap represents the map of attribute for TraceSearch.
var TraceSearchAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"End": {
		AllowedChoices: []string{},
		ConvertedName:  "End",
		Description: `The end of the time window in any format supported by
https://github.com/araddon/dateparse.`,
		Exposed: true,
		Getter:  true,
		Name:    "end",
		Setter:  true,
		Type:    "string",
	},
	"EndRelative": {
		AllowedChoices: []string{},
		ConvertedName:  "EndRelative",
		Description:    `The relative end of the time window as time.Duration.`,
		Exposed:        true,
		Getter:         true,
		Name:           "endRelative",
		Type:           "string",
	},
	"Limit": {
		AllowedChoices: []string{},
		ConvertedName:  "Limit",
		DefaultValue:   20,
		Description:    `Limit the number of search result.`,
		Exposed:        true,
		Name:           "limit",
		Type:           "integer",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"Query": {
		AllowedChoices: []string{},
		ConvertedName:  "Query",
		Description:    `The query in TraceQL format.`,
		Exposed:        true,
		Name:           "query",
		Required:       true,
		Type:           "string",
	},
	"Result": {
		AllowedChoices: []string{},
		ConvertedName:  "Result",
		Description:    `The result of the request.`,
		Exposed:        true,
		Name:           "result",
		SubType:        "[]map[string]any",
		Type:           "external",
	},
	"SpansPerSpanSet": {
		AllowedChoices: []string{},
		ConvertedName:  "SpansPerSpanSet",
		DefaultValue:   3,
		Description: `The max number of spans to return per span set. If set to -1, it means no span
at all. 0 will use the default value (3).`,
		Exposed:  true,
		MinValue: -1,
		Name:     "spansPerSpanSet",
		Type:     "integer",
	},
	"Start": {
		AllowedChoices: []string{},
		ConvertedName:  "Start",
		Description: `The start of the time window in any format supported by
https://github.com/araddon/dateparse.`,
		Exposed: true,
		Getter:  true,
		Name:    "start",
		Setter:  true,
		Type:    "string",
	},
	"StartRelative": {
		AllowedChoices: []string{},
		ConvertedName:  "StartRelative",
		Description:    `The relative start of the time window as time.Duration.`,
		Exposed:        true,
		Getter:         true,
		Name:           "startRelative",
		Type:           "string",
	},
}

// TraceSearchLowerCaseAttributesMap represents the map of attribute for TraceSearch.
var TraceSearchLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"end": {
		AllowedChoices: []string{},
		ConvertedName:  "End",
		Description: `The end of the time window in any format supported by
https://github.com/araddon/dateparse.`,
		Exposed: true,
		Getter:  true,
		Name:    "end",
		Setter:  true,
		Type:    "string",
	},
	"endrelative": {
		AllowedChoices: []string{},
		ConvertedName:  "EndRelative",
		Description:    `The relative end of the time window as time.Duration.`,
		Exposed:        true,
		Getter:         true,
		Name:           "endRelative",
		Type:           "string",
	},
	"limit": {
		AllowedChoices: []string{},
		ConvertedName:  "Limit",
		DefaultValue:   20,
		Description:    `Limit the number of search result.`,
		Exposed:        true,
		Name:           "limit",
		Type:           "integer",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"query": {
		AllowedChoices: []string{},
		ConvertedName:  "Query",
		Description:    `The query in TraceQL format.`,
		Exposed:        true,
		Name:           "query",
		Required:       true,
		Type:           "string",
	},
	"result": {
		AllowedChoices: []string{},
		ConvertedName:  "Result",
		Description:    `The result of the request.`,
		Exposed:        true,
		Name:           "result",
		SubType:        "[]map[string]any",
		Type:           "external",
	},
	"spansperspanset": {
		AllowedChoices: []string{},
		ConvertedName:  "SpansPerSpanSet",
		DefaultValue:   3,
		Description: `The max number of spans to return per span set. If set to -1, it means no span
at all. 0 will use the default value (3).`,
		Exposed:  true,
		MinValue: -1,
		Name:     "spansPerSpanSet",
		Type:     "integer",
	},
	"start": {
		AllowedChoices: []string{},
		ConvertedName:  "Start",
		Description: `The start of the time window in any format supported by
https://github.com/araddon/dateparse.`,
		Exposed: true,
		Getter:  true,
		Name:    "start",
		Setter:  true,
		Type:    "string",
	},
	"startrelative": {
		AllowedChoices: []string{},
		ConvertedName:  "StartRelative",
		Description:    `The relative start of the time window as time.Duration.`,
		Exposed:        true,
		Getter:         true,
		Name:           "startRelative",
		Type:           "string",
	},
}

// SparseTraceSearchesList represents a list of SparseTraceSearches
type SparseTraceSearchesList []*SparseTraceSearch

// Identity returns the identity of the objects in the list.
func (o SparseTraceSearchesList) Identity() elemental.Identity {

	return TraceSearchIdentity
}

// Copy returns a pointer to a copy the SparseTraceSearchesList.
func (o SparseTraceSearchesList) Copy() elemental.Identifiables {

	copy := slices.Clone(o)
	return &copy
}

// Append appends the objects to the a new copy of the SparseTraceSearchesList.
func (o SparseTraceSearchesList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := slices.Clone(o)
	for _, obj := range objects {
		out = append(out, obj.(*SparseTraceSearch))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseTraceSearchesList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseTraceSearchesList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseTraceSearchesList converted to TraceSearchesList.
func (o SparseTraceSearchesList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := range len(o) {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseTraceSearchesList) Version() int {

	return 1
}

// SparseTraceSearch represents the sparse version of a tracesearch.
type SparseTraceSearch struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The end of the time window in any format supported by
	// https://github.com/araddon/dateparse.
	End *string `json:"end,omitempty" msgpack:"end,omitempty" bson:"-" mapstructure:"end,omitempty"`

	// The relative end of the time window as time.Duration.
	EndRelative *string `json:"endRelative,omitempty" msgpack:"endRelative,omitempty" bson:"-" mapstructure:"endRelative,omitempty"`

	// Limit the number of search result.
	Limit *int `json:"limit,omitempty" msgpack:"limit,omitempty" bson:"-" mapstructure:"limit,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The query in TraceQL format.
	Query *string `json:"query,omitempty" msgpack:"query,omitempty" bson:"-" mapstructure:"query,omitempty"`

	// The result of the request.
	Result *[]map[string]any `json:"result,omitempty" msgpack:"result,omitempty" bson:"-" mapstructure:"result,omitempty"`

	// The max number of spans to return per span set. If set to -1, it means no span
	// at all. 0 will use the default value (3).
	SpansPerSpanSet *int `json:"spansPerSpanSet,omitempty" msgpack:"spansPerSpanSet,omitempty" bson:"-" mapstructure:"spansPerSpanSet,omitempty"`

	// The start of the time window in any format supported by
	// https://github.com/araddon/dateparse.
	Start *string `json:"start,omitempty" msgpack:"start,omitempty" bson:"-" mapstructure:"start,omitempty"`

	// The relative start of the time window as time.Duration.
	StartRelative *string `json:"startRelative,omitempty" msgpack:"startRelative,omitempty" bson:"-" mapstructure:"startRelative,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseTraceSearch returns a new  SparseTraceSearch.
func NewSparseTraceSearch() *SparseTraceSearch {
	return &SparseTraceSearch{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseTraceSearch) Identity() elemental.Identity {

	return TraceSearchIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseTraceSearch) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseTraceSearch) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseTraceSearch) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseTraceSearch{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseTraceSearch) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseTraceSearch{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseTraceSearch) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseTraceSearch) ToPlain() elemental.PlainIdentifiable {

	out := NewTraceSearch()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.End != nil {
		out.End = *o.End
	}
	if o.EndRelative != nil {
		out.EndRelative = *o.EndRelative
	}
	if o.Limit != nil {
		out.Limit = *o.Limit
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.Query != nil {
		out.Query = *o.Query
	}
	if o.Result != nil {
		out.Result = *o.Result
	}
	if o.SpansPerSpanSet != nil {
		out.SpansPerSpanSet = *o.SpansPerSpanSet
	}
	if o.Start != nil {
		out.Start = *o.Start
	}
	if o.StartRelative != nil {
		out.StartRelative = *o.StartRelative
	}

	return out
}

// GetEnd returns the End of the receiver.
func (o *SparseTraceSearch) GetEnd() (out string) {

	if o.End == nil {
		return
	}

	return *o.End
}

// SetEnd sets the property End of the receiver using the address of the given value.
func (o *SparseTraceSearch) SetEnd(end string) {

	o.End = &end
}

// GetEndRelative returns the EndRelative of the receiver.
func (o *SparseTraceSearch) GetEndRelative() (out string) {

	if o.EndRelative == nil {
		return
	}

	return *o.EndRelative
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseTraceSearch) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseTraceSearch) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetStart returns the Start of the receiver.
func (o *SparseTraceSearch) GetStart() (out string) {

	if o.Start == nil {
		return
	}

	return *o.Start
}

// SetStart sets the property Start of the receiver using the address of the given value.
func (o *SparseTraceSearch) SetStart(start string) {

	o.Start = &start
}

// GetStartRelative returns the StartRelative of the receiver.
func (o *SparseTraceSearch) GetStartRelative() (out string) {

	if o.StartRelative == nil {
		return
	}

	return *o.StartRelative
}

// DeepCopy returns a deep copy if the SparseTraceSearch.
func (o *SparseTraceSearch) DeepCopy() *SparseTraceSearch {

	if o == nil {
		return nil
	}

	out := &SparseTraceSearch{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseTraceSearch.
func (o *SparseTraceSearch) DeepCopyInto(out *SparseTraceSearch) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseTraceSearch: %s", err))
	}

	*out = *target.(*SparseTraceSearch)
}

type mongoAttributesTraceSearch struct {
	ID        bson.ObjectId `bson:"_id,omitempty"`
	Namespace string        `bson:"namespace,omitempty"`
}
type mongoAttributesSparseTraceSearch struct {
	ID        bson.ObjectId `bson:"_id,omitempty"`
	Namespace *string       `bson:"namespace,omitempty"`
}
