// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"
	"time"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// WebExtensionConfigIdentity represents the Identity of the object.
var WebExtensionConfigIdentity = elemental.Identity{
	Name:     "webextensionconfig",
	Category: "webextensionconfigs",
	Package:  "lain",
	Private:  false,
}

// WebExtensionConfigsList represents a list of WebExtensionConfigs
type WebExtensionConfigsList []*WebExtensionConfig

// Identity returns the identity of the objects in the list.
func (o WebExtensionConfigsList) Identity() elemental.Identity {

	return WebExtensionConfigIdentity
}

// Copy returns a pointer to a copy the WebExtensionConfigsList.
func (o WebExtensionConfigsList) Copy() elemental.Identifiables {

	out := append(WebExtensionConfigsList{}, o...)
	return &out
}

// Append appends the objects to the a new copy of the WebExtensionConfigsList.
func (o WebExtensionConfigsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(WebExtensionConfigsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*WebExtensionConfig))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o WebExtensionConfigsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o WebExtensionConfigsList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the WebExtensionConfigsList converted to SparseWebExtensionConfigsList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o WebExtensionConfigsList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseWebExtensionConfigsList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToSparse(fields...).(*SparseWebExtensionConfig)
	}

	return out
}

// Version returns the version of the content.
func (o WebExtensionConfigsList) Version() int {

	return 1
}

// WebExtensionConfig represents the model of a webextensionconfig
type WebExtensionConfig struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Allow the webextension to set the proxy settings in the employee browser.
	AllowProxySettings bool `json:"allowProxySettings" msgpack:"allowProxySettings" bson:"allowproxysettings" mapstructure:"allowProxySettings,omitempty"`

	// Creation date of the object.
	CreateTime time.Time `json:"createTime" msgpack:"createTime" bson:"createtime" mapstructure:"createTime,omitempty"`

	// Description of the webextension configuration.
	Description string `json:"description" msgpack:"description" bson:"description" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The name of the webextension configuration.
	Name string `json:"name" msgpack:"name" bson:"name" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Define the interval in minutes to refresh the configuration browser.
	RefreshWebExtensionConfigInterval int `json:"refreshWebExtensionConfigInterval" msgpack:"refreshWebExtensionConfigInterval" bson:"refreshwebextensionconfiginterval" mapstructure:"refreshWebExtensionConfigInterval,omitempty"`

	// Define the interval in minutes between two reports of the visited urls.
	ReportVisitedURLsInterval int `json:"reportVisitedURLsInterval" msgpack:"reportVisitedURLsInterval" bson:"reportvisitedurlsinterval" mapstructure:"reportVisitedURLsInterval,omitempty"`

	// Last update date of the object.
	UpdateTime time.Time `json:"updateTime" msgpack:"updateTime" bson:"updatetime" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash int `json:"-" msgpack:"-" bson:"zhash" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone int `json:"-" msgpack:"-" bson:"zone" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewWebExtensionConfig returns a new *WebExtensionConfig
func NewWebExtensionConfig() *WebExtensionConfig {

	return &WebExtensionConfig{
		ModelVersion:                      1,
		RefreshWebExtensionConfigInterval: 120,
		ReportVisitedURLsInterval:         60,
	}
}

// Identity returns the Identity of the object.
func (o *WebExtensionConfig) Identity() elemental.Identity {

	return WebExtensionConfigIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *WebExtensionConfig) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *WebExtensionConfig) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *WebExtensionConfig) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesWebExtensionConfig{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.AllowProxySettings = o.AllowProxySettings
	s.CreateTime = o.CreateTime
	s.Description = o.Description
	s.ImportHash = o.ImportHash
	s.ImportLabel = o.ImportLabel
	s.Name = o.Name
	s.Namespace = o.Namespace
	s.RefreshWebExtensionConfigInterval = o.RefreshWebExtensionConfigInterval
	s.ReportVisitedURLsInterval = o.ReportVisitedURLsInterval
	s.UpdateTime = o.UpdateTime
	s.ZHash = o.ZHash
	s.Zone = o.Zone

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *WebExtensionConfig) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesWebExtensionConfig{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.AllowProxySettings = s.AllowProxySettings
	o.CreateTime = s.CreateTime
	o.Description = s.Description
	o.ImportHash = s.ImportHash
	o.ImportLabel = s.ImportLabel
	o.Name = s.Name
	o.Namespace = s.Namespace
	o.RefreshWebExtensionConfigInterval = s.RefreshWebExtensionConfigInterval
	o.ReportVisitedURLsInterval = s.ReportVisitedURLsInterval
	o.UpdateTime = s.UpdateTime
	o.ZHash = s.ZHash
	o.Zone = s.Zone

	return nil
}

// Version returns the hardcoded version of the model.
func (o *WebExtensionConfig) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *WebExtensionConfig) BleveType() string {

	return "webextensionconfig"
}

// DefaultOrder returns the list of default ordering fields.
func (o *WebExtensionConfig) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *WebExtensionConfig) Doc() string {

	return `WebExtensionConfig stores the configuration information for the webextension.`
}

func (o *WebExtensionConfig) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *WebExtensionConfig) GetCreateTime() time.Time {

	return o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the given value.
func (o *WebExtensionConfig) SetCreateTime(createTime time.Time) {

	o.CreateTime = createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *WebExtensionConfig) GetImportHash() string {

	return o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the given value.
func (o *WebExtensionConfig) SetImportHash(importHash string) {

	o.ImportHash = importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *WebExtensionConfig) GetImportLabel() string {

	return o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the given value.
func (o *WebExtensionConfig) SetImportLabel(importLabel string) {

	o.ImportLabel = importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *WebExtensionConfig) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *WebExtensionConfig) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *WebExtensionConfig) GetUpdateTime() time.Time {

	return o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the given value.
func (o *WebExtensionConfig) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *WebExtensionConfig) GetZHash() int {

	return o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the given value.
func (o *WebExtensionConfig) SetZHash(zHash int) {

	o.ZHash = zHash
}

// GetZone returns the Zone of the receiver.
func (o *WebExtensionConfig) GetZone() int {

	return o.Zone
}

// SetZone sets the property Zone of the receiver using the given value.
func (o *WebExtensionConfig) SetZone(zone int) {

	o.Zone = zone
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *WebExtensionConfig) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseWebExtensionConfig{
			ID:                                &o.ID,
			AllowProxySettings:                &o.AllowProxySettings,
			CreateTime:                        &o.CreateTime,
			Description:                       &o.Description,
			ImportHash:                        &o.ImportHash,
			ImportLabel:                       &o.ImportLabel,
			Name:                              &o.Name,
			Namespace:                         &o.Namespace,
			RefreshWebExtensionConfigInterval: &o.RefreshWebExtensionConfigInterval,
			ReportVisitedURLsInterval:         &o.ReportVisitedURLsInterval,
			UpdateTime:                        &o.UpdateTime,
			ZHash:                             &o.ZHash,
			Zone:                              &o.Zone,
		}
	}

	sp := &SparseWebExtensionConfig{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "allowProxySettings":
			sp.AllowProxySettings = &(o.AllowProxySettings)
		case "createTime":
			sp.CreateTime = &(o.CreateTime)
		case "description":
			sp.Description = &(o.Description)
		case "importHash":
			sp.ImportHash = &(o.ImportHash)
		case "importLabel":
			sp.ImportLabel = &(o.ImportLabel)
		case "name":
			sp.Name = &(o.Name)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "refreshWebExtensionConfigInterval":
			sp.RefreshWebExtensionConfigInterval = &(o.RefreshWebExtensionConfigInterval)
		case "reportVisitedURLsInterval":
			sp.ReportVisitedURLsInterval = &(o.ReportVisitedURLsInterval)
		case "updateTime":
			sp.UpdateTime = &(o.UpdateTime)
		case "zHash":
			sp.ZHash = &(o.ZHash)
		case "zone":
			sp.Zone = &(o.Zone)
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseWebExtensionConfig to the object.
func (o *WebExtensionConfig) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseWebExtensionConfig)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.AllowProxySettings != nil {
		o.AllowProxySettings = *so.AllowProxySettings
	}
	if so.CreateTime != nil {
		o.CreateTime = *so.CreateTime
	}
	if so.Description != nil {
		o.Description = *so.Description
	}
	if so.ImportHash != nil {
		o.ImportHash = *so.ImportHash
	}
	if so.ImportLabel != nil {
		o.ImportLabel = *so.ImportLabel
	}
	if so.Name != nil {
		o.Name = *so.Name
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.RefreshWebExtensionConfigInterval != nil {
		o.RefreshWebExtensionConfigInterval = *so.RefreshWebExtensionConfigInterval
	}
	if so.ReportVisitedURLsInterval != nil {
		o.ReportVisitedURLsInterval = *so.ReportVisitedURLsInterval
	}
	if so.UpdateTime != nil {
		o.UpdateTime = *so.UpdateTime
	}
	if so.ZHash != nil {
		o.ZHash = *so.ZHash
	}
	if so.Zone != nil {
		o.Zone = *so.Zone
	}
}

// DeepCopy returns a deep copy if the WebExtensionConfig.
func (o *WebExtensionConfig) DeepCopy() *WebExtensionConfig {

	if o == nil {
		return nil
	}

	out := &WebExtensionConfig{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *WebExtensionConfig.
func (o *WebExtensionConfig) DeepCopyInto(out *WebExtensionConfig) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy WebExtensionConfig: %s", err))
	}

	*out = *target.(*WebExtensionConfig)
}

// Validate valides the current information stored into the structure.
func (o *WebExtensionConfig) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = requiredErrors.Append(err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*WebExtensionConfig) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := WebExtensionConfigAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return WebExtensionConfigLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*WebExtensionConfig) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return WebExtensionConfigAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *WebExtensionConfig) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "allowProxySettings":
		return o.AllowProxySettings
	case "createTime":
		return o.CreateTime
	case "description":
		return o.Description
	case "importHash":
		return o.ImportHash
	case "importLabel":
		return o.ImportLabel
	case "name":
		return o.Name
	case "namespace":
		return o.Namespace
	case "refreshWebExtensionConfigInterval":
		return o.RefreshWebExtensionConfigInterval
	case "reportVisitedURLsInterval":
		return o.ReportVisitedURLsInterval
	case "updateTime":
		return o.UpdateTime
	case "zHash":
		return o.ZHash
	case "zone":
		return o.Zone
	}

	return nil
}

// WebExtensionConfigAttributesMap represents the map of attribute for WebExtensionConfig.
var WebExtensionConfigAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"AllowProxySettings": {
		AllowedChoices: []string{},
		BSONFieldName:  "allowproxysettings",
		ConvertedName:  "AllowProxySettings",
		Description:    `Allow the webextension to set the proxy settings in the employee browser.`,
		Exposed:        true,
		Name:           "allowProxySettings",
		Stored:         true,
		Type:           "boolean",
	},
	"CreateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"Description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `Description of the webextension configuration.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"ImportHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"ImportLabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"Name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the webextension configuration.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"RefreshWebExtensionConfigInterval": {
		AllowedChoices: []string{},
		BSONFieldName:  "refreshwebextensionconfiginterval",
		ConvertedName:  "RefreshWebExtensionConfigInterval",
		DefaultValue:   120,
		Description:    `Define the interval in minutes to refresh the configuration browser.`,
		Exposed:        true,
		Name:           "refreshWebExtensionConfigInterval",
		Stored:         true,
		Type:           "integer",
	},
	"ReportVisitedURLsInterval": {
		AllowedChoices: []string{},
		BSONFieldName:  "reportvisitedurlsinterval",
		ConvertedName:  "ReportVisitedURLsInterval",
		DefaultValue:   60,
		Description:    `Define the interval in minutes between two reports of the visited urls.`,
		Exposed:        true,
		Name:           "reportVisitedURLsInterval",
		Stored:         true,
		Type:           "integer",
	},
	"UpdateTime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"ZHash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"Zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// WebExtensionConfigLowerCaseAttributesMap represents the map of attribute for WebExtensionConfig.
var WebExtensionConfigLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"allowproxysettings": {
		AllowedChoices: []string{},
		BSONFieldName:  "allowproxysettings",
		ConvertedName:  "AllowProxySettings",
		Description:    `Allow the webextension to set the proxy settings in the employee browser.`,
		Exposed:        true,
		Name:           "allowProxySettings",
		Stored:         true,
		Type:           "boolean",
	},
	"createtime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "createtime",
		ConvertedName:  "CreateTime",
		Description:    `Creation date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"description": {
		AllowedChoices: []string{},
		BSONFieldName:  "description",
		ConvertedName:  "Description",
		Description:    `Description of the webextension configuration.`,
		Exposed:        true,
		Name:           "description",
		Stored:         true,
		Type:           "string",
	},
	"importhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "importhash",
		ConvertedName:  "ImportHash",
		CreationOnly:   true,
		Description:    `The hash of the structure used to compare with new import version.`,
		Exposed:        true,
		Getter:         true,
		Name:           "importHash",
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"importlabel": {
		AllowedChoices: []string{},
		BSONFieldName:  "importlabel",
		ConvertedName:  "ImportLabel",
		CreationOnly:   true,
		Description: `The user-defined import label that allows the system to group resources from the
same import operation.`,
		Exposed: true,
		Getter:  true,
		Name:    "importLabel",
		Setter:  true,
		Stored:  true,
		Type:    "string",
	},
	"name": {
		AllowedChoices: []string{},
		BSONFieldName:  "name",
		ConvertedName:  "Name",
		Description:    `The name of the webextension configuration.`,
		Exposed:        true,
		Name:           "name",
		Required:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"refreshwebextensionconfiginterval": {
		AllowedChoices: []string{},
		BSONFieldName:  "refreshwebextensionconfiginterval",
		ConvertedName:  "RefreshWebExtensionConfigInterval",
		DefaultValue:   120,
		Description:    `Define the interval in minutes to refresh the configuration browser.`,
		Exposed:        true,
		Name:           "refreshWebExtensionConfigInterval",
		Stored:         true,
		Type:           "integer",
	},
	"reportvisitedurlsinterval": {
		AllowedChoices: []string{},
		BSONFieldName:  "reportvisitedurlsinterval",
		ConvertedName:  "ReportVisitedURLsInterval",
		DefaultValue:   60,
		Description:    `Define the interval in minutes between two reports of the visited urls.`,
		Exposed:        true,
		Name:           "reportVisitedURLsInterval",
		Stored:         true,
		Type:           "integer",
	},
	"updatetime": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "updatetime",
		ConvertedName:  "UpdateTime",
		Description:    `Last update date of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "time",
	},
	"zhash": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zhash",
		ConvertedName:  "ZHash",
		Description:    `Hash of the object used to shard the data.`,
		Getter:         true,
		Name:           "zHash",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "integer",
	},
	"zone": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "zone",
		ConvertedName:  "Zone",
		Description:    `Sharding zone.`,
		Getter:         true,
		Name:           "zone",
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Transient:      true,
		Type:           "integer",
	},
}

// SparseWebExtensionConfigsList represents a list of SparseWebExtensionConfigs
type SparseWebExtensionConfigsList []*SparseWebExtensionConfig

// Identity returns the identity of the objects in the list.
func (o SparseWebExtensionConfigsList) Identity() elemental.Identity {

	return WebExtensionConfigIdentity
}

// Copy returns a pointer to a copy the SparseWebExtensionConfigsList.
func (o SparseWebExtensionConfigsList) Copy() elemental.Identifiables {

	copy := append(SparseWebExtensionConfigsList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the SparseWebExtensionConfigsList.
func (o SparseWebExtensionConfigsList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(SparseWebExtensionConfigsList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*SparseWebExtensionConfig))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseWebExtensionConfigsList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseWebExtensionConfigsList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseWebExtensionConfigsList converted to WebExtensionConfigsList.
func (o SparseWebExtensionConfigsList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseWebExtensionConfigsList) Version() int {

	return 1
}

// SparseWebExtensionConfig represents the sparse version of a webextensionconfig.
type SparseWebExtensionConfig struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// Allow the webextension to set the proxy settings in the employee browser.
	AllowProxySettings *bool `json:"allowProxySettings,omitempty" msgpack:"allowProxySettings,omitempty" bson:"allowproxysettings,omitempty" mapstructure:"allowProxySettings,omitempty"`

	// Creation date of the object.
	CreateTime *time.Time `json:"createTime,omitempty" msgpack:"createTime,omitempty" bson:"createtime,omitempty" mapstructure:"createTime,omitempty"`

	// Description of the webextension configuration.
	Description *string `json:"description,omitempty" msgpack:"description,omitempty" bson:"description,omitempty" mapstructure:"description,omitempty"`

	// The hash of the structure used to compare with new import version.
	ImportHash *string `json:"importHash,omitempty" msgpack:"importHash,omitempty" bson:"importhash,omitempty" mapstructure:"importHash,omitempty"`

	// The user-defined import label that allows the system to group resources from the
	// same import operation.
	ImportLabel *string `json:"importLabel,omitempty" msgpack:"importLabel,omitempty" bson:"importlabel,omitempty" mapstructure:"importLabel,omitempty"`

	// The name of the webextension configuration.
	Name *string `json:"name,omitempty" msgpack:"name,omitempty" bson:"name,omitempty" mapstructure:"name,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// Define the interval in minutes to refresh the configuration browser.
	RefreshWebExtensionConfigInterval *int `json:"refreshWebExtensionConfigInterval,omitempty" msgpack:"refreshWebExtensionConfigInterval,omitempty" bson:"refreshwebextensionconfiginterval,omitempty" mapstructure:"refreshWebExtensionConfigInterval,omitempty"`

	// Define the interval in minutes between two reports of the visited urls.
	ReportVisitedURLsInterval *int `json:"reportVisitedURLsInterval,omitempty" msgpack:"reportVisitedURLsInterval,omitempty" bson:"reportvisitedurlsinterval,omitempty" mapstructure:"reportVisitedURLsInterval,omitempty"`

	// Last update date of the object.
	UpdateTime *time.Time `json:"updateTime,omitempty" msgpack:"updateTime,omitempty" bson:"updatetime,omitempty" mapstructure:"updateTime,omitempty"`

	// Hash of the object used to shard the data.
	ZHash *int `json:"-" msgpack:"-" bson:"zhash,omitempty" mapstructure:"-,omitempty"`

	// Sharding zone.
	Zone *int `json:"-" msgpack:"-" bson:"zone,omitempty" mapstructure:"-,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseWebExtensionConfig returns a new  SparseWebExtensionConfig.
func NewSparseWebExtensionConfig() *SparseWebExtensionConfig {
	return &SparseWebExtensionConfig{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseWebExtensionConfig) Identity() elemental.Identity {

	return WebExtensionConfigIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseWebExtensionConfig) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseWebExtensionConfig) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseWebExtensionConfig) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseWebExtensionConfig{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.AllowProxySettings != nil {
		s.AllowProxySettings = o.AllowProxySettings
	}
	if o.CreateTime != nil {
		s.CreateTime = o.CreateTime
	}
	if o.Description != nil {
		s.Description = o.Description
	}
	if o.ImportHash != nil {
		s.ImportHash = o.ImportHash
	}
	if o.ImportLabel != nil {
		s.ImportLabel = o.ImportLabel
	}
	if o.Name != nil {
		s.Name = o.Name
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}
	if o.RefreshWebExtensionConfigInterval != nil {
		s.RefreshWebExtensionConfigInterval = o.RefreshWebExtensionConfigInterval
	}
	if o.ReportVisitedURLsInterval != nil {
		s.ReportVisitedURLsInterval = o.ReportVisitedURLsInterval
	}
	if o.UpdateTime != nil {
		s.UpdateTime = o.UpdateTime
	}
	if o.ZHash != nil {
		s.ZHash = o.ZHash
	}
	if o.Zone != nil {
		s.Zone = o.Zone
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseWebExtensionConfig) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseWebExtensionConfig{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.AllowProxySettings != nil {
		o.AllowProxySettings = s.AllowProxySettings
	}
	if s.CreateTime != nil {
		o.CreateTime = s.CreateTime
	}
	if s.Description != nil {
		o.Description = s.Description
	}
	if s.ImportHash != nil {
		o.ImportHash = s.ImportHash
	}
	if s.ImportLabel != nil {
		o.ImportLabel = s.ImportLabel
	}
	if s.Name != nil {
		o.Name = s.Name
	}
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}
	if s.RefreshWebExtensionConfigInterval != nil {
		o.RefreshWebExtensionConfigInterval = s.RefreshWebExtensionConfigInterval
	}
	if s.ReportVisitedURLsInterval != nil {
		o.ReportVisitedURLsInterval = s.ReportVisitedURLsInterval
	}
	if s.UpdateTime != nil {
		o.UpdateTime = s.UpdateTime
	}
	if s.ZHash != nil {
		o.ZHash = s.ZHash
	}
	if s.Zone != nil {
		o.Zone = s.Zone
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseWebExtensionConfig) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseWebExtensionConfig) ToPlain() elemental.PlainIdentifiable {

	out := NewWebExtensionConfig()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.AllowProxySettings != nil {
		out.AllowProxySettings = *o.AllowProxySettings
	}
	if o.CreateTime != nil {
		out.CreateTime = *o.CreateTime
	}
	if o.Description != nil {
		out.Description = *o.Description
	}
	if o.ImportHash != nil {
		out.ImportHash = *o.ImportHash
	}
	if o.ImportLabel != nil {
		out.ImportLabel = *o.ImportLabel
	}
	if o.Name != nil {
		out.Name = *o.Name
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.RefreshWebExtensionConfigInterval != nil {
		out.RefreshWebExtensionConfigInterval = *o.RefreshWebExtensionConfigInterval
	}
	if o.ReportVisitedURLsInterval != nil {
		out.ReportVisitedURLsInterval = *o.ReportVisitedURLsInterval
	}
	if o.UpdateTime != nil {
		out.UpdateTime = *o.UpdateTime
	}
	if o.ZHash != nil {
		out.ZHash = *o.ZHash
	}
	if o.Zone != nil {
		out.Zone = *o.Zone
	}

	return out
}

// GetCreateTime returns the CreateTime of the receiver.
func (o *SparseWebExtensionConfig) GetCreateTime() (out time.Time) {

	if o.CreateTime == nil {
		return
	}

	return *o.CreateTime
}

// SetCreateTime sets the property CreateTime of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetCreateTime(createTime time.Time) {

	o.CreateTime = &createTime
}

// GetImportHash returns the ImportHash of the receiver.
func (o *SparseWebExtensionConfig) GetImportHash() (out string) {

	if o.ImportHash == nil {
		return
	}

	return *o.ImportHash
}

// SetImportHash sets the property ImportHash of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetImportHash(importHash string) {

	o.ImportHash = &importHash
}

// GetImportLabel returns the ImportLabel of the receiver.
func (o *SparseWebExtensionConfig) GetImportLabel() (out string) {

	if o.ImportLabel == nil {
		return
	}

	return *o.ImportLabel
}

// SetImportLabel sets the property ImportLabel of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetImportLabel(importLabel string) {

	o.ImportLabel = &importLabel
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseWebExtensionConfig) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// GetUpdateTime returns the UpdateTime of the receiver.
func (o *SparseWebExtensionConfig) GetUpdateTime() (out time.Time) {

	if o.UpdateTime == nil {
		return
	}

	return *o.UpdateTime
}

// SetUpdateTime sets the property UpdateTime of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetUpdateTime(updateTime time.Time) {

	o.UpdateTime = &updateTime
}

// GetZHash returns the ZHash of the receiver.
func (o *SparseWebExtensionConfig) GetZHash() (out int) {

	if o.ZHash == nil {
		return
	}

	return *o.ZHash
}

// SetZHash sets the property ZHash of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetZHash(zHash int) {

	o.ZHash = &zHash
}

// GetZone returns the Zone of the receiver.
func (o *SparseWebExtensionConfig) GetZone() (out int) {

	if o.Zone == nil {
		return
	}

	return *o.Zone
}

// SetZone sets the property Zone of the receiver using the address of the given value.
func (o *SparseWebExtensionConfig) SetZone(zone int) {

	o.Zone = &zone
}

// DeepCopy returns a deep copy if the SparseWebExtensionConfig.
func (o *SparseWebExtensionConfig) DeepCopy() *SparseWebExtensionConfig {

	if o == nil {
		return nil
	}

	out := &SparseWebExtensionConfig{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseWebExtensionConfig.
func (o *SparseWebExtensionConfig) DeepCopyInto(out *SparseWebExtensionConfig) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseWebExtensionConfig: %s", err))
	}

	*out = *target.(*SparseWebExtensionConfig)
}

type mongoAttributesWebExtensionConfig struct {
	ID                                bson.ObjectId `bson:"_id,omitempty"`
	AllowProxySettings                bool          `bson:"allowproxysettings"`
	CreateTime                        time.Time     `bson:"createtime"`
	Description                       string        `bson:"description"`
	ImportHash                        string        `bson:"importhash,omitempty"`
	ImportLabel                       string        `bson:"importlabel,omitempty"`
	Name                              string        `bson:"name"`
	Namespace                         string        `bson:"namespace,omitempty"`
	RefreshWebExtensionConfigInterval int           `bson:"refreshwebextensionconfiginterval"`
	ReportVisitedURLsInterval         int           `bson:"reportvisitedurlsinterval"`
	UpdateTime                        time.Time     `bson:"updatetime"`
	ZHash                             int           `bson:"zhash"`
	Zone                              int           `bson:"zone"`
}
type mongoAttributesSparseWebExtensionConfig struct {
	ID                                bson.ObjectId `bson:"_id,omitempty"`
	AllowProxySettings                *bool         `bson:"allowproxysettings,omitempty"`
	CreateTime                        *time.Time    `bson:"createtime,omitempty"`
	Description                       *string       `bson:"description,omitempty"`
	ImportHash                        *string       `bson:"importhash,omitempty"`
	ImportLabel                       *string       `bson:"importlabel,omitempty"`
	Name                              *string       `bson:"name,omitempty"`
	Namespace                         *string       `bson:"namespace,omitempty"`
	RefreshWebExtensionConfigInterval *int          `bson:"refreshwebextensionconfiginterval,omitempty"`
	ReportVisitedURLsInterval         *int          `bson:"reportvisitedurlsinterval,omitempty"`
	UpdateTime                        *time.Time    `bson:"updatetime,omitempty"`
	ZHash                             *int          `bson:"zhash,omitempty"`
	Zone                              *int          `bson:"zone,omitempty"`
}
