// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/model.gotpl)

package api

import (
	"fmt"

	"github.com/globalsign/mgo/bson"
	"github.com/mitchellh/copystructure"
	"go.acuvity.ai/elemental"
)

// AdminMagicLinkIdentity represents the Identity of the object.
var AdminMagicLinkIdentity = elemental.Identity{
	Name:     "adminmagiclink",
	Category: "adminmagiclinks",
	Package:  "ultradmin",
	Private:  false,
}

// AdminMagicLinksList represents a list of AdminMagicLinks
type AdminMagicLinksList []*AdminMagicLink

// Identity returns the identity of the objects in the list.
func (o AdminMagicLinksList) Identity() elemental.Identity {

	return AdminMagicLinkIdentity
}

// Copy returns a pointer to a copy the AdminMagicLinksList.
func (o AdminMagicLinksList) Copy() elemental.Identifiables {

	out := append(AdminMagicLinksList{}, o...)
	return &out
}

// Append appends the objects to the a new copy of the AdminMagicLinksList.
func (o AdminMagicLinksList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(AdminMagicLinksList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*AdminMagicLink))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o AdminMagicLinksList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o AdminMagicLinksList) DefaultOrder() []string {

	return []string{}
}

// ToSparse returns the AdminMagicLinksList converted to SparseAdminMagicLinksList.
// Objects in the list will only contain the given fields. No field means entire field set.
func (o AdminMagicLinksList) ToSparse(fields ...string) elemental.Identifiables {

	out := make(SparseAdminMagicLinksList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToSparse(fields...).(*SparseAdminMagicLink)
	}

	return out
}

// Version returns the version of the content.
func (o AdminMagicLinksList) Version() int {

	return 1
}

// AdminMagicLink represents the model of a adminmagiclink
type AdminMagicLink struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The namespace of the object.
	Namespace string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The passcode information.
	Passcode *Passcode `json:"passcode,omitempty" msgpack:"passcode,omitempty" bson:"-" mapstructure:"passcode,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewAdminMagicLink returns a new *AdminMagicLink
func NewAdminMagicLink() *AdminMagicLink {

	return &AdminMagicLink{
		ModelVersion: 1,
		Passcode:     NewPasscode(),
	}
}

// Identity returns the Identity of the object.
func (o *AdminMagicLink) Identity() elemental.Identity {

	return AdminMagicLinkIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *AdminMagicLink) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *AdminMagicLink) SetIdentifier(id string) {

	o.ID = id
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AdminMagicLink) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesAdminMagicLink{}

	if o.ID != "" {
		s.ID = bson.ObjectIdHex(o.ID)
	}
	s.Namespace = o.Namespace

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *AdminMagicLink) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesAdminMagicLink{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	o.ID = s.ID.Hex()
	o.Namespace = s.Namespace

	return nil
}

// Version returns the hardcoded version of the model.
func (o *AdminMagicLink) Version() int {

	return 1
}

// BleveType implements the bleve.Classifier Interface.
func (o *AdminMagicLink) BleveType() string {

	return "adminmagiclink"
}

// DefaultOrder returns the list of default ordering fields.
func (o *AdminMagicLink) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *AdminMagicLink) Doc() string {

	return `Administrative API to create magic links.`
}

func (o *AdminMagicLink) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetNamespace returns the Namespace of the receiver.
func (o *AdminMagicLink) GetNamespace() string {

	return o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the given value.
func (o *AdminMagicLink) SetNamespace(namespace string) {

	o.Namespace = namespace
}

// ToSparse returns the sparse version of the model.
// The returned object will only contain the given fields. No field means entire field set.
func (o *AdminMagicLink) ToSparse(fields ...string) elemental.SparseIdentifiable {

	if len(fields) == 0 {
		// nolint: goimports
		return &SparseAdminMagicLink{
			ID:        &o.ID,
			Namespace: &o.Namespace,
			Passcode:  o.Passcode,
		}
	}

	sp := &SparseAdminMagicLink{}
	for _, f := range fields {
		switch f {
		case "ID":
			sp.ID = &(o.ID)
		case "namespace":
			sp.Namespace = &(o.Namespace)
		case "passcode":
			sp.Passcode = o.Passcode
		}
	}

	return sp
}

// Patch apply the non nil value of a *SparseAdminMagicLink to the object.
func (o *AdminMagicLink) Patch(sparse elemental.SparseIdentifiable) {
	if !sparse.Identity().IsEqual(o.Identity()) {
		panic("cannot patch from a parse with different identity")
	}

	so := sparse.(*SparseAdminMagicLink)
	if so.ID != nil {
		o.ID = *so.ID
	}
	if so.Namespace != nil {
		o.Namespace = *so.Namespace
	}
	if so.Passcode != nil {
		o.Passcode = so.Passcode
	}
}

// DeepCopy returns a deep copy if the AdminMagicLink.
func (o *AdminMagicLink) DeepCopy() *AdminMagicLink {

	if o == nil {
		return nil
	}

	out := &AdminMagicLink{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *AdminMagicLink.
func (o *AdminMagicLink) DeepCopyInto(out *AdminMagicLink) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy AdminMagicLink: %s", err))
	}

	*out = *target.(*AdminMagicLink)
}

// Validate valides the current information stored into the structure.
func (o *AdminMagicLink) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if o.Passcode != nil {
		elemental.ResetDefaultForZeroValues(o.Passcode)
		if err := o.Passcode.Validate(); err != nil {
			errors = errors.Append(err)
		}
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*AdminMagicLink) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := AdminMagicLinkAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return AdminMagicLinkLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*AdminMagicLink) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return AdminMagicLinkAttributesMap
}

// ValueForAttribute returns the value for the given attribute.
// This is a very advanced function that you should not need but in some
// very specific use cases.
func (o *AdminMagicLink) ValueForAttribute(name string) any {

	switch name {
	case "ID":
		return o.ID
	case "namespace":
		return o.Namespace
	case "passcode":
		return o.Passcode
	}

	return nil
}

// AdminMagicLinkAttributesMap represents the map of attribute for AdminMagicLink.
var AdminMagicLinkAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"Namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"Passcode": {
		AllowedChoices: []string{},
		ConvertedName:  "Passcode",
		Description:    `The passcode information.`,
		Exposed:        true,
		Name:           "passcode",
		SubType:        "passcode",
		Type:           "ref",
	},
}

// AdminMagicLinkLowerCaseAttributesMap represents the map of attribute for AdminMagicLink.
var AdminMagicLinkLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "_id",
		ConvertedName:  "ID",
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"namespace": {
		AllowedChoices: []string{},
		Autogenerated:  true,
		BSONFieldName:  "namespace",
		ConvertedName:  "Namespace",
		Description:    `The namespace of the object.`,
		Exposed:        true,
		Getter:         true,
		Name:           "namespace",
		Orderable:      true,
		ReadOnly:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
	},
	"passcode": {
		AllowedChoices: []string{},
		ConvertedName:  "Passcode",
		Description:    `The passcode information.`,
		Exposed:        true,
		Name:           "passcode",
		SubType:        "passcode",
		Type:           "ref",
	},
}

// SparseAdminMagicLinksList represents a list of SparseAdminMagicLinks
type SparseAdminMagicLinksList []*SparseAdminMagicLink

// Identity returns the identity of the objects in the list.
func (o SparseAdminMagicLinksList) Identity() elemental.Identity {

	return AdminMagicLinkIdentity
}

// Copy returns a pointer to a copy the SparseAdminMagicLinksList.
func (o SparseAdminMagicLinksList) Copy() elemental.Identifiables {

	copy := append(SparseAdminMagicLinksList{}, o...)
	return &copy
}

// Append appends the objects to the a new copy of the SparseAdminMagicLinksList.
func (o SparseAdminMagicLinksList) Append(objects ...elemental.Identifiable) elemental.Identifiables {

	out := append(SparseAdminMagicLinksList{}, o...)
	for _, obj := range objects {
		out = append(out, obj.(*SparseAdminMagicLink))
	}

	return out
}

// List converts the object to an elemental.IdentifiablesList.
func (o SparseAdminMagicLinksList) List() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i]
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SparseAdminMagicLinksList) DefaultOrder() []string {

	return []string{}
}

// ToPlain returns the SparseAdminMagicLinksList converted to AdminMagicLinksList.
func (o SparseAdminMagicLinksList) ToPlain() elemental.IdentifiablesList {

	out := make(elemental.IdentifiablesList, len(o))
	for i := 0; i < len(o); i++ {
		out[i] = o[i].ToPlain()
	}

	return out
}

// Version returns the version of the content.
func (o SparseAdminMagicLinksList) Version() int {

	return 1
}

// SparseAdminMagicLink represents the sparse version of a adminmagiclink.
type SparseAdminMagicLink struct {
	// ID is the identifier of the object.
	ID *string `json:"ID,omitempty" msgpack:"ID,omitempty" bson:"-" mapstructure:"ID,omitempty"`

	// The namespace of the object.
	Namespace *string `json:"namespace,omitempty" msgpack:"namespace,omitempty" bson:"namespace,omitempty" mapstructure:"namespace,omitempty"`

	// The passcode information.
	Passcode *Passcode `json:"passcode,omitempty" msgpack:"passcode,omitempty" bson:"-" mapstructure:"passcode,omitempty"`

	ModelVersion int `json:"-" msgpack:"-" bson:"_modelversion"`
}

// NewSparseAdminMagicLink returns a new  SparseAdminMagicLink.
func NewSparseAdminMagicLink() *SparseAdminMagicLink {
	return &SparseAdminMagicLink{}
}

// Identity returns the Identity of the sparse object.
func (o *SparseAdminMagicLink) Identity() elemental.Identity {

	return AdminMagicLinkIdentity
}

// Identifier returns the value of the sparse object's unique identifier.
func (o *SparseAdminMagicLink) Identifier() string {

	if o.ID == nil {
		return ""
	}
	return *o.ID
}

// SetIdentifier sets the value of the sparse object's unique identifier.
func (o *SparseAdminMagicLink) SetIdentifier(id string) {

	if id != "" {
		o.ID = &id
	} else {
		o.ID = nil
	}
}

// GetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseAdminMagicLink) GetBSON() (any, error) {

	if o == nil {
		return nil, nil
	}

	s := &mongoAttributesSparseAdminMagicLink{}

	if o.ID != nil {
		s.ID = bson.ObjectIdHex(*o.ID)
	}
	if o.Namespace != nil {
		s.Namespace = o.Namespace
	}

	return s, nil
}

// SetBSON implements the bson marshaling interface.
// This is used to transparently convert ID to MongoDBID as ObectID.
func (o *SparseAdminMagicLink) SetBSON(raw bson.Raw) error {

	if o == nil {
		return nil
	}

	s := &mongoAttributesSparseAdminMagicLink{}
	if err := raw.Unmarshal(s); err != nil {
		return err
	}

	id := s.ID.Hex()
	o.ID = &id
	if s.Namespace != nil {
		o.Namespace = s.Namespace
	}

	return nil
}

// Version returns the hardcoded version of the model.
func (o *SparseAdminMagicLink) Version() int {

	return 1
}

// ToPlain returns the plain version of the sparse model.
func (o *SparseAdminMagicLink) ToPlain() elemental.PlainIdentifiable {

	out := NewAdminMagicLink()
	if o.ID != nil {
		out.ID = *o.ID
	}
	if o.Namespace != nil {
		out.Namespace = *o.Namespace
	}
	if o.Passcode != nil {
		out.Passcode = o.Passcode
	}

	return out
}

// GetNamespace returns the Namespace of the receiver.
func (o *SparseAdminMagicLink) GetNamespace() (out string) {

	if o.Namespace == nil {
		return
	}

	return *o.Namespace
}

// SetNamespace sets the property Namespace of the receiver using the address of the given value.
func (o *SparseAdminMagicLink) SetNamespace(namespace string) {

	o.Namespace = &namespace
}

// DeepCopy returns a deep copy if the SparseAdminMagicLink.
func (o *SparseAdminMagicLink) DeepCopy() *SparseAdminMagicLink {

	if o == nil {
		return nil
	}

	out := &SparseAdminMagicLink{}
	o.DeepCopyInto(out)

	return out
}

// DeepCopyInto copies the receiver into the given *SparseAdminMagicLink.
func (o *SparseAdminMagicLink) DeepCopyInto(out *SparseAdminMagicLink) {

	target, err := copystructure.Copy(o)
	if err != nil {
		panic(fmt.Sprintf("Unable to deepcopy SparseAdminMagicLink: %s", err))
	}

	*out = *target.(*SparseAdminMagicLink)
}

type mongoAttributesAdminMagicLink struct {
	ID        bson.ObjectId `bson:"_id,omitempty"`
	Namespace string        `bson:"namespace,omitempty"`
}
type mongoAttributesSparseAdminMagicLink struct {
	ID        bson.ObjectId `bson:"_id,omitempty"`
	Namespace *string       `bson:"namespace,omitempty"`
}
