// Code generated by elegen. DO NOT EDIT.
// Source: go.acuvity.ai/elemental (templates/relationships_registry.gotpl)

package api

import "go.acuvity.ai/elemental"

var relationshipsRegistry elemental.RelationshipsRegistry

func init() {

	relationshipsRegistry = elemental.RelationshipsRegistry{}

	relationshipsRegistry[AnalyzerIdentity] = &elemental.Relationship{}

	relationshipsRegistry[LatencyIdentity] = &elemental.Relationship{}

	relationshipsRegistry[PrincipalIdentity] = &elemental.Relationship{}

	relationshipsRegistry[PrincipalAppIdentity] = &elemental.Relationship{}

	relationshipsRegistry[PrincipalUserIdentity] = &elemental.Relationship{}

	relationshipsRegistry[RootIdentity] = &elemental.Relationship{}

}
